### ISSUE TITLE
Add keybind for placing a rally point

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#1004]
- [x] Add keybind for placing a rally point

**Comment by cmbasnett** [comment]
Was actually thinking that this might just be redundant. Personally I'd probably find it easier to use the radial menu that hunt-and-peck the rally point button. When we have the rally point indicator stuff on the HUD this will probably seem even less useful.

**Comment by AndrewTheel** [comment]
Its more or less for new SLs, we can just be like hit [%PlaceRallyPoint%] button to place a rally point, etc.

Its also handy for now as we can just hit a single button to see how many seconds left.
