### ISSUE TITLE
Satchels have no effect on obstacles (such as fences)

### ISSUE THREAD

**Issue by kasinobonuksia** [DarklightGames/DarkestHour#1006]
Shouldn't destroyable fences (and barb wire) be destroyable with satchel charges as well? ;-)

**Comment by cmbasnett** [comment]
This is a known bug with *some* of the wooden fences. The root cause is that the origin of the fences are technically under the ground, so the ground is absorbing the hit.

**Comment by AndrewTheel** [comment]
This can easily be resolved by tapping into the "explode" function and doing a radius actors check for obstacles and damaging them based on distance.

**Comment by AndrewTheel** [comment]
Duplicate of https://github.com/DarklightGames/DarkestHour/issues/1006
