### ISSUE TITLE
Implement anti-tank gun rotation functionality

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#1008]
Finally came up with a reasonably easy-to-implement solution for gun rotation.

1. When *off* the gun, if there are sufficient people around, you can hold down a button to go into a "rotation" mode.
2. Going into "rotation mode":
i. Puts a "proxy" gun at the position
ii. Hides the current AT gun (for the owning player)
iii. The proxy that is rotated like you would rotate a construction (Q and E).
iv. Confirming the rotation makes the real gun hidden (we still need to keep it around so it can be destroyed)
v. The visual proxy rotates for everyone to see to the new position
vi. When the proxy rotates to the new position, the original gun instantly teleported to the new position, re-seating itself via the physics

**Comment by AndrewTheel** [comment]
Might need a way to keep someone from getting on the gun when its hidden/rotating.

**Comment by AndrewTheel** [comment]
- [ ] Can crash client when rotating gun and the gun is destroyed
- [ ] Has another crash involving shooting after rotating gun (no reproduction steps yet)

**Comment by shiftycats** [comment]
Implemented in v9.1.0.
