### ISSUE TITLE
i3window manager + full or windowed [LINUX]

### ISSUE THREAD

**Issue by klaus1488** [DarklightGames/DarkestHour#1014]
The game window locks the mouse and the keyboard; and won't let me use the i3wm workpaces, nor the window manager fullscreen modes.
The engine is very rudimentary.
Is there any launch option to override this? What can I do? 
I don't know how can I explain my problem further, but I'll be glad to give more feedback since it's driving me crazy.

In games such as Counter-Strike 1.6 (goldsrc) I'm able to move my mouse outside the game window and do whatever I want.

Thanks in advance!

**Comment by AndrewTheel** [comment]
I hope this helps: https://forums.epicgames.com/unreal-tournament-2003-2004/troubleshooting-technology/44613-two-mouse-cursors-why

**Comment by AndrewTheel** [comment]
Closing this as its not an issue with DH
