### ISSUE TITLE
Improved driver view for Cromwell tank

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#103]
Originally reported by: **Bitbucket: [Matt_UK](http://bitbucket.org/Matt_UK), GitHub: [Matt_UK](http://github.com/Matt_UK)**

---

Buttoned up view is through armoured glass vision block set in circular front hatch. Currently uses a mesh HUD overlay from the KV1 tank to draw a black border for a 'fat letterbox' view, with no glass tinting.

Have modified to remove the mesh HUD overlay and use a simple textured overlay, showing glass tinting effect. This involved switching tank's parent class to DH_ROTreadCraftB, which is abstract class for tanks using a textured overlay. Uses default allied driver's periscope texture, but have modified the DrawPeriscopeOverlay function to adjust the proportions to exactly match the inset glass vision block, which is a noticeably 'fatter' letterbox shape than an allied periscope.

'Unbuttoned' view (actually just front circular vision hatch open) limits are currently very restricted and don't allow driver to look around inside the tank. The modeller has added some nice interior features and it's possible to considerably increase view limits to show them off. Have increased view limits for this position as far as can be allowed before things start to look wrong.

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/104

**Comment by handsm** [comment]
A full interior model view implemented as part of substantial model re-work committed in SVN update no.1161, including working driver's overhead hatch as well as front vision hatch.

See https://github.com/DarklightGames/DarkestHour/issues/530 for more details.
