### ISSUE TITLE
Motor pools make vehicles listed as reserved for the duration of the game

### ISSUE THREAD

**Issue by shiftycats** [DarklightGames/DarkestHour#1035]
The bug does seem to occur when a pool locks up while there's a player about to spawn on it. As a result, the player loses his spawn selection, but the vehicle he picked stays listed as reserved.

This prohibits anyone from spawning that vehicle again until the round ends.

**Comment by cmbasnett** [comment]
The problem is likely that the `UnreserveVehicle` function is not being called along the code path.
