### ISSUE TITLE
Objective spawns need desperately a variable to set which one is the nearest active

### ISSUE THREAD

**Issue by kashash** [DarklightGames/DarkestHour#1049]
Is it ok if we could add this I don't know for how many times I've been asking for it along with Dolas as we recognize a big problem of matches going dull and tedious if you have to spawn on an objective that is practically useless and not much different from the main spawn.

Right now it's set as a default for the second inactive objective to be a spawnpoint.
There must be an option so the first one can be a spawnpoint

And the threshold distance limit could even override the function of the obj spawn of being the first nearest, if for example the objectives are closer to each other than the threshold distance is set to.

So for example if some map has it set so the first nearest objective is a spawnpoint, but also it's set so the threshold distance is set to 100m but two objectives are actually 80m to one another, then as an exception, this would override the 1st nearest objective being the spawnpoint and would make the second objective as an active spawnpoint.

It would improve tons of maps right now that can be very dull and as often as it happens when the rally point is lost and no other spawn is available, objectives seem to be the only option to spawn half the time and it's just way too far to have a steady flow of troops meaningful battle.

**Comment by AndrewTheel** [comment]
I can work on this tomorrow, thanks for making an issue for it.

**Comment by kashash** [comment]
Thank you so much I know there's always some other things in plans and sometimes people have a motivation for example to do some other things.. However I would really appreciate if this was added cause sometimes I feel like it's the only thing left for DH to play fine without problems. BTW me saying I've been asking for it I don't know if this sounded bad but I've been trying to describe it more in the words that it's been needed for a long time that actually would improve the player's experience in DH you know... :P So I'd really appreciate and would be so nice if actually now maps had this option that would make them play better and so convienient to just now spawn with your squad on the nearest cap where it would actually make the battles a lot more tense, dynamic and sensible in play.

**Comment by kashash** [comment]
It's so nice that we have the gametypes Advance and Clash seperated. So I was thinking maybe as a default Clash could be set to 2 (so that the second inactive objective is usually a spawnpoint), whereas Advance would be 1, which would be the first inactive objective. But also would be nice to have an option of having even the active friendly objectives to be a spawnpoint, which would be 0, and I think for certain scenarios this could be used in some cases for some of the maps. And so if it's set to 0, it would pick the active objective to be a spawnpoint but if there isn't any active one than it would pick the first inactive one.

So to make it clear, if an advance map doesn't 1-1 objectives but only 1 that is active (enemy one), and your team objectives are all set inactive on capture, then if the objective spawn on the map is set to 1 then the very first nearest inactive objective would be a spawnpoint right next to the active enemy one. And that's what I think would make many current maps like Butovo, Valko, (even Bridgehead in my opinion cause it could use objectives spawnpoints to be a bit closer I think).

Oh that's another thing, that I think it would be good if there was a choice so for axis for example you could set to be 1 and allies 2, so if axis are attacking they'd the objective spawnpoint closer than the defenders.

**Comment by AndrewTheel** [comment]
I'm closing this as I don't think we need Allies/Axis differences. We can reopen the issue if that is determined to be needed.
