### ISSUE TITLE
Test Session Bugs Found

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#1063]
- [x] Enfield either bolts too fast or 3rd anims are too slow
- [x] Enfield stripper clips dont' work, show just singles
- [x] Log: PlayAnim: Sequence 'open_nagant9130' not found for mesh 'nagant9130'
- [x] FG42 & BAR (and more?) have issue after reload when deployed
- [x] Changing scope type while holding a sniper does not properly update it, you have to drop weapon first
- [x] Look into the AT gun sometimes snapping suddenly to a new rotation from 3rd client?
- [x] AT rotation needs an audible rotation sound
- [x] DZ markers don't appear properly
- [x] Wirecutters has no icon when cutting obstacles/constructions in MP
- [x] Lower/adjust AT rotation speeds
- [x] Wire-obstacles should not be damaged by grenades
- [x] SVT40 accuracy increase
- [x] 30cal has too much recoil
- [x] MG42 is crazy with recoil
- [x] All gamemodes should default to (2) with objective spawns
- [x] Redo collision on the intact wire-obstacle as you can dive prone over them!
- [x] Gun fires after confirming AT rotation with left click (SP only)
- [x] Player can't hear the overheat pitch changes when firing (only other clients)
- [x] MG42 has strange after-firing animation (30 cal too)
- [ ] Enfield has missing anim for reloading single (after a bolt, so a round in the chamber)
- [x] No cut sound for cutting constructions in MP (not necessary for 9.1)

- [x] BAR recoil when rested is extremely low
- [x] Accessed None `Attachedto`

**Comment by DanMakesGames** [comment]
sorry miss pressed button.
