### ISSUE TITLE
Automatic Weapon code enhancement to support Shoot_End_Empty animations.

### ISSUE THREAD

**Issue by DanMakesGames** [DarklightGames/DarkestHour#1067]
The current automatic weapon code delays idle_empty animation after firing because the Shoot_End animation needs to take place. This can be seen clearly on the mp40 (the bolt snaps forward a couple seconds after the final round in the mag is shot. This is incorrect, it should snap immediately.)

**Comment by dynamittt** [comment]
The MP 40 Fires from **_open bolt._**

**Comment by GarlicAAZ** [comment]
we know that..

**Comment by dynamittt** [comment]
But after the final round is shot and the mag is empty, the bolt returns to forward position (aka closed). It's how the weapon works.
Same for the PPSh...

**Comment by GarlicAAZ** [comment]
we know that too

**Comment by DanMakesGames** [comment]
Go into the shooting range, mag dump the mp40, and you will see what I'm talking about. There is a long delay from after firing the last shot on the mp40, and the bolt coming forward. That delay looks bad. It's not a matter of realism.

**Comment by DanMakesGames** [comment]
My original description is worded funny. The problem is the DELAY from firing the last shot, and the bolt coming forward.
