### ISSUE TITLE
cant lock/unlock squad

### ISSUE THREAD

**Issue by GarlicAAZ** [DarklightGames/DarkestHour#1070]
clicking on the lock symbol does nothing (often) 
![image](https://user-images.githubusercontent.com/46670708/59968421-edfd8480-9539-11e9-8f21-927a4892b7bb.png)

**Comment by cmbasnett** [comment]
This isn't actually a bug, per se. You are unable to lock your squad if you have less than a certain amount of players in your squad. This is probably more an issue with conveyance. We could perhaps not display the lock icon if you are unable to lock the squad.

**Comment by GarlicAAZ** [comment]
so it doesnt allow to create proper tank squads with 2/3 people?

**Comment by cmbasnett** [comment]
@mimiski Perhaps this can be tackled if you get a chance. The lock icon should either not be visible *or* it should be visibly greyed out with a tooltip that explains why the squad cannot be locked.

**Comment by mimiski** [comment]
@cmbasnett ok, can you assign this issue to me?

**Comment by shiftycats** [comment]
Resolved in #1127.
