### ISSUE TITLE
Main menu does not load the correct level, leaving the previous level loaded

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#1097]
**Reproduction steps:**
1. join a server 
2. open menu & click 'servers' then 'main'

**Comment by mimiski** [comment]
Hi, I was playing with this bug and came up with the above commit. I assumed that the player should be disconnected (I'm not sure if that's correct).

**Comment by shiftycats** [comment]
Fixed in: #1118
