### ISSUE TITLE
Replacing literals with `bFlaming` and `bThrowRagdoll` leads to undesired effects

### ISSUE THREAD

**Issue by shiftycats** [DarklightGames/DarkestHour#1113]
The changes merged from pull requests #1108 and #1109 result in tank shells setting players on fire and crashing their games. Similarly, PR #1111 affects all the tank shells, making them slightly more "explosive".

For some reason, `bFlaming` is enabled in a number of RO parent damage types. For example, `ROTankShellExplosionDamage`, which is what all the shell damage types derive from, has this flag on. The same goes for the `bThrowRagdoll` flag.

I'm not sure why fires induce crashes though: whether replacing things with `bFlaming` cause this, or it's a bug with fire emitters in general. I was unable to reproduce the crashes with WP and the pull requests reverted, so I'd assume it's the former. 

Anyways, I'm reverting #1108, #1109, and #1111 from `master`.

**Crash reports:**
```
 Build RedOrchestra_Build_[2005-11-27_10.48]

OS: Windows NT 6.1 (Build: 7601)
CPU: GenuineIntel PentiumPro-class processor @ 2894 MHz with 4095MB RAM
Video: Intel(R) HD Graphics 4000 (4425)

General protection fault!

History: USpriteEmitter::UpdateParticles <- AEmitter::Tick <- TickAllActors <- ULevel::Tick <- (NetMode=3) <- TickLevel <- UGameEngine::Tick <- Level Target Range <- UpdateWorld <- MainLoop <- FMallocWindows::Free <- FMallocWindows::Realloc <- 00000013 0 FArray <- FArray::Realloc <- 0*2 <- FMallocWindows::Free
```
```
 Build RedOrchestra_Build_[2005-11-27_10.48]

OS: Windows NT 6.1 (Build: 7601)
CPU: GenuineIntel PentiumPro-class processor @ 2894 MHz with 4095MB RAM
Video: Intel(R) HD Graphics 4000 (4425)

General protection fault!

History: SkeletalMeshGet <- USpriteEmitter::UpdateParticles <- AEmitter::Tick <- TickAllActors <- ULevel::Tick <- (NetMode=3) <- TickLevel <- UGameEngine::Tick <- Level Target Range <- UpdateWorld <- MainLoop <- FMallocWindows::Free <- FMallocWindows::Realloc <- 00000013 0 FArray <- FArray::Realloc <- 0*2 <- FMallocWindows::Free
```

**Comment by andrew-raphael-lukasik** [comment]
![oh no](https://i.imgflip.com/2tfqlx.jpg)

**Comment by andrew-raphael-lukasik** [comment]
Both crash reports seems to be from level "Level Target Range" am I right? Does it happen on other levels too?
