### ISSUE TITLE
Godolloi Push

### ISSUE THREAD

**Issue by GarlicAAZ** [DarklightGames/DarkestHour#1161]
This is a collective issue for all the bugs and proposed changes related to this level.

## Critical priority (level is off rotation until these are resolved)
--

## Low priority
- [ ] Missing spawn protection.
- [ ] ~~Missing nation (hungarians)~~.

**Comment by shiftycats** [comment]
The missing nation can be resolved by simply renaming the map to something else. It's a generic forest map.

**Comment by GarlicAAZ** [comment]
the map is quite big and wide, so perhaps making it advance would be an improvement

**Comment by shiftycats** [comment]
> the map is quite big and wide, so perhaps making it advance would be an improvement

Wouldn't mind it.
