### ISSUE TITLE
Weapon animation code fixes

### ISSUE THREAD

**Issue by GarlicAAZ** [DarklightGames/DarkestHour#1218]
- SMGs need "last fire" functionality just like pistols, so that the bolt would appear closed immediately after the magazine empties, and not after the "fire" animation ends playing

- there should be "aim_to_bipod" animation reference for BAR and similar weapons

**Comment by shiftycats** [comment]
> SMGs need "last fire" functionality just like pistols, so that the bolt would appear closed immediately after the magazine empties, and not after the "fire" animation ends playing

Pistols use `idle_empty` animation to achieve this. Every weapon has this functionality.

**Comment by GarlicAAZ** [comment]
pistols dont use `idle_empty` for the fire animation though

**Comment by GarlicAAZ** [comment]
for example luger has `shoot_empty` animation

**Comment by cmbasnett** [comment]
@GarlicAAZ is right, the only weapons that have a "last shot" animation is the pistols. This can be easily remedied.

**Comment by cmbasnett** [comment]
Committed in 7d5e2380.

**Comment by GarlicAAZ** [comment]
there is still this though
> there should be "aim_to_bipod" animation reference for BAR and similar weapons
