### ISSUE TITLE
SU-76 Collision Issues With Gunner Position

### ISSUE THREAD

**Issue by GDrukenmiller** [DarklightGames/DarkestHour#1222]
SU-76 has noticeable collision issues with its exposed gunner position. Unlike the Marder, bullets bounce right off as if the collision is not matching the model itself, resulting in the gunner being invulnerable. Additionally, if the gunner turns out and attempts to place markers with binoculars, they place on his own position.

**Comment by cmbasnett** [comment]
Confirmed. It appears to be caused by an extraneous hitbox that is attached to the commander bone.
![su76bug](https://user-images.githubusercontent.com/5035660/106058414-10586c00-60a6-11eb-8665-2eb5e4e95019.gif)
