### ISSUE TITLE
Gun shot sounds sometimes don't originate from weapon operator

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#128]
Originally reported by: **Andrew Theel (Bitbucket: [AndrewTheel](http://bitbucket.org/AndrewTheel), GitHub: [AndrewTheel](http://github.com/AndrewTheel))**

---

Seems to occur often when testing.  Requires operator to drop weapon and pick back up before sound is fixed.  It seems the sound comes from the players spawn point/teleport exit instead of current location.  Who knows how often this occurs in standard gameplay without being detected.

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/129

**Comment by AndrewTheel** [comment]
I just remembered, this had something to do with viewing a player in spectate first.

```
BartBear - Today at 7:48 AM
well it is basic RO bug, but if it could be fixed for DH would be nice - in spectator mode with camera stuck to the player when he goes away of the starting (view) point all sounds play well except his own weapons shoots (which seem to be "left at place" where the observer "joined" the player)
```

**Comment by AndrewTheel** [comment]
Closing as it won't fix and we want to keep open bug reports minimum.
