### ISSUE TITLE
Implement target selection

### ISSUE THREAD

**Issue by mimiski** [DarklightGames/DarkestHour#1283]
Artillery operators should be able to choose the target they want to fire at from the list of artillery map markers.

To do:
 - [ ] add a drop down option when an artillery operator clicks on an artillery map marker to select that marker as the active target

To be decided:
 - what should happen when the target disappears? should the 'active target' feature be on squad level so that whenever a squad leader changes their artillery marker the artillery operator gets the new position without selecting it again?
 - how should ruler markers work? should they always be visible as a target widget or should they be first chosen like squad-level artillery requests?

**Comment by shiftycats** [comment]
> what should happen when the target disappears? should the 'active target' feature be on squad level so that whenever a squad leader changes their artillery marker the artillery operator gets the new position without selecting it again?

Correct. It should update the position while keeping the marker selected.

>how should ruler markers work? should they always be visible as a target widget or should they be first chosen like squad-level artillery requests?

Always visible as long as ruler marker is placed. This way operator can see data for both markers simultaneously. For example, he can set the ruler at a splash location, compare the values, and accurately calculate how far he's off from his target
