### ISSUE TITLE
Add a selected marker toggle in the spotting scope view

### ISSUE THREAD

**Issue by mimiski** [DarklightGames/DarkestHour#1304]
When in the spotting scope view the artillery operator should be able to toggle the selected artillery marker by using a key.

To do:
 - write an exec function that toggles the selected target
 - intercept key event like so https://github.com/DarklightGames/DarkestHour/blob/6ecad3355cbfc7c596c13385f3f6d9b8037639a1/DH_Interface/Classes/DHMainMenu.uc#L329
 - add an entry in the Settings > Controls here https://github.com/DarklightGames/DarkestHour/blob/6ecad3355cbfc7c596c13385f3f6d9b8037639a1/DH_Interface/Classes/DHTab_Controls.uc#L308
 - handle the case when the artillery operator is an artillery spotter and selects their own target (should not be possible)

**Comment by cmbasnett** [comment]
In addition, prompt the user (via an on-screen keybind hint) that they are able to toggle the map markers. Have this happen contextually (i.e. no point in showing it if there are no markers to toggle to or the user already has the only marker already selected).

This prompt should be near where the target markers are displayed in the top left of the interface when in the spotting scope.
