### ISSUE TITLE
[Bug] SL's command markers appears on compass

### ISSUE THREAD

**Issue by randomguy3174** [DarklightGames/DarkestHour#1344]
**Description**
Command markers(move, attack, defend) that've been put on map by squad leaders, appears/overlap on compass of other leaders.
Noticed on myshkova_river at the time this report written.

**To Reproduce**
1. Boot in map
2. Different SL's place markers
3. Check compass

**Expected behavior**
Only command markers of current squad leader appear on compass.

**Screenshots**
![System Screenshot 2021 10 21 - 23 08 07 66](https://user-images.githubusercontent.com/67280527/138352168-8ba8a0bd-83a8-43e4-abc9-efeeb0bee45b.png)
![System Screenshot 2021 10 21 - 23 01 54 24](https://user-images.githubusercontent.com/67280527/138352051-80420245-7151-4eb5-a971-6de4c976f653.png)

**Comment by mimiski** [comment]
I don't know how to solve that but I just wanted to say I love the new bug reporting template lol
