### ISSUE TITLE
[Map Bug] DH-Flakturm_Tiergarten_Defence - Missing collision detection for objects

### ISSUE THREAD

**Issue by X2T5** [DarklightGames/DarkestHour#1455]
**Describe the bug**

Two tank wrecks (T34-85) and a house wall (near the allies start point) have no collision detection on the map "DH-Flakturm_Tiergarten_Defence".

I have made a [video ](https://mega.nz/file/yb4WnJzT#M95l7zxMuxGTyqMv1yodcGzJSgm_WcIoeY_vuZ4ciBk)recording please watch it.

**Comment by GDrukenmiller** [comment]
Thanks for the report, this will be fixed next update.
