### ISSUE TITLE
[Map Bug] DH-Fox_Green_Defence - Missing Minimap

### ISSUE THREAD

**Issue by X2T5** [DarklightGames/DarkestHour#1456]
**Describe the bug**
The Minimap is missing for the map: DH-Fox_Green_Defence

![DH-Fox_Green_Defence](https://user-images.githubusercontent.com/108025605/175335144-a565f8e4-997f-4d87-a3be-a56677984aa7.png)

**Comment by GDrukenmiller** [comment]
Known issue, there wasn't enough time to get one made before these maps were pushed for events. It will be fixed in the next update.
