### ISSUE TITLE
[Map Bug] DH-Donner_Stalemate - faulty flag layout

### ISSUE THREAD

**Issue by X2T5** [DarklightGames/DarkestHour#1470]
**Describe the bug**

The flag layout is faulty the map can not be won

![1](https://user-images.githubusercontent.com/108025605/177002539-c2ae0e59-e702-4e1b-8d09-78dc917908ff.png)

**Comment by GarlicAAZ** [comment]
you can win, you just need to secure most objectives when time runs out
