### ISSUE TITLE
[Map Bug] DH-Donner_Bolts - faulty match layout

### ISSUE THREAD

**Issue by X2T5** [DarklightGames/DarkestHour#1471]
**Describe the bug**

there are no flags
there are no tickets
there is no game goal? time limit? how is the winner decided?

The allied weapons layout is faulty - us soldiers have various weapons from other nations to choose from as well as grenades - the weapons of the USSR have double entries

**Solution?**
Remove this map version and use only the DH-Donner_Stalemate map with flags?

![1](https://user-images.githubusercontent.com/108025605/177003309-acc6805f-8273-4615-8c23-9337f7e015b2.png)
![2](https://user-images.githubusercontent.com/108025605/177002815-33ef9ddd-76db-46fe-9a73-26f80b29ac1e.png)
![3](https://user-images.githubusercontent.com/108025605/177002817-da8a8d8d-517a-4308-9082-b0400266cd61.png)
![4](https://user-images.githubusercontent.com/108025605/177002820-8225c0d6-f8d6-4dc3-abd6-51f3d3e9873f.png)
![5](https://user-images.githubusercontent.com/108025605/177002825-3d8f148b-36ec-4048-baa5-3577fe309f9e.png)

**Comment by GarlicAAZ** [comment]
winner is decided by kills; 
grenades are a flaw indeed
