### ISSUE TITLE
[Feature Request] Remove Bridgehead from rotation.

### ISSUE THREAD

**Issue by randomguy3174** [DarklightGames/DarkestHour#1479]
**Is your feature request related to a problem? Please describe.**
Map in current state does not provide fun expirience, since server is always struggling running map:
-map always suffer from poor tickrate;
-enormous respawn time past few objectives, 1-2 mins for rifleman;
-time to get into action is pretty high, walking from spawn to objective can take up to 2mins and considering previous point even more.

**Describe the solution you'd like**
Remove map from rotation on both infantry servers.

**Describe alternatives you've considered**
Remove map from rotation and get it back for weekends and/or events.

**Additional context**
In future map could use some updates and comeback refined in rotation, right now it's just not plays well.

**Comment by cmbasnett** [comment]
Closing this since we now have a better server that can run it fine.
