### ISSUE TITLE
[Map Bugs - Thread is maintained] Report/Collection of Bugs/Flaws from INFANTRY Maps -- Update -- 20.09.2022

### ISSUE THREAD

**Issue by X2T5** [DarklightGames/DarkestHour#1506]
### --=== DH-Donner_Bolts ===--

**_-- Bug Description 1 of 2 --_**

- [ ] Change "Allied Nation" from Britain to USA in the "Map Vote Screen" of this map

![0](https://user-images.githubusercontent.com/108025605/186184783-bf7bf427-a62e-4625-b206-5c94944d7b79.png)

**_-- Bug Description 2 of 2 --_**

- [x] The weapon class slots for the allied nation "USSR" are _**duplicated**_, the difference is only in the order of the weapon listing (?)

![11](https://user-images.githubusercontent.com/108025605/182638871-656ca4a5-4cb0-471b-9fc1-f4efca1ca29f.png)

### --=== DH-Vossenack ===--

**_-- Bug Description 1 of 1 --_**

- [ ] Invisible wall + climbing through the window not possible [VIDEO Report](https://mega.nz/file/TLZREJoC#4KDLwLkQ-M7GmaUrMwRMCZFPU1uN_5gVxbrIsMcjC2Y)

**Comment by MadDeathHound** [comment]
On Bug report #2, the reason they appear duplicated is because one role is for Polish riflemen and another is for USSR riflemen. They use the same guns in-game
