### ISSUE TITLE
Tank cannon - keep fire key pressed while cannon reloads & subsequent rounds don't show muzzle flash

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#153]
Originally reported by: **Bitbucket: [Matt_UK](http://bitbucket.org/Matt_UK), GitHub: [Matt_UK](http://github.com/Matt_UK)**

----------------------------------------

Just noticed this. It's obscure, probably never noticed & doesn't effect gameplay. Really just making a note of it for any future release fix.

----------------------------------------
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/154

**Comment by handsm** [comment]
Fixed as part of commit https://github.com/DarklightGames/DarkestHour/commit/f6b577cb464c7677900b4ca51b036fffe3b6ee38.
