### ISSUE TITLE
DH-Makhnovo_Advance - The "anti-tank soldier" class, has no AT weapon

### ISSUE THREAD

**Issue by DHFan45** [DarklightGames/DarkestHour#1549]
- [ ] **-== Bug Description 1  /  DH Version: 11.3.0  /  Last updated: 24.01.2023  ==-**

- The Soviet "Anti-Tank Soldier" class has **no anti-tank weapon at all**. My suggestion would be to replace the main armament with a PTRD-41, since there are already two "Combat Engineer" with Satchels.

![1](https://user-images.githubusercontent.com/123426586/214318945-af58c64e-7de2-4484-a455-203da6e529e0.png)

**Comment by GarlicAAZ** [comment]
PTRD did not exist at the time of this map; Satchel is an anti-tank weapon and serves as a placeholder for RPG-40

**Comment by DHFan45** [comment]
Thank you for your answer. Would you add a Satchel or remove the "Anti-Tank Soldier" class ?

**Comment by GarlicAAZ** [comment]
there used to be a satchel, it is now gone due to changes made to default role loadouts. Either me or someone else will add satchel back at some point
