### ISSUE TITLE
DH-Dzerzhinsky_Tractor_Factory_Advance [Improvement Proposal]

### ISSUE THREAD

**Issue by DHFan45** [DarklightGames/DarkestHour#1555]
- [ ] **== Improvement Report/Description 01 -- DH Version: 11.3.0 -- Last updated: 25.01.2023 ==**

- The red marked areas are a "meat grinder" for the german team. Often the team can't attack beyond the first objective without having used up the tickets too much.

If the yellow marked building becomes walkable throughout, it would be easier for the germans to advance under cover. The fighting would not be concentrated in just two places. House-to-house fighting is also casualty intensive, but the soldiers would have cover against tanks and the fighting would be more spread out.

![1](https://user-images.githubusercontent.com/123426586/214652198-8dec86bc-42e4-4035-9c96-95c92a48bbe4.png)

**Comment by GDrukenmiller** [comment]
This is being addressed in an update soon.
