### ISSUE TITLE
DH-Champs_d'Agonie_Advance [Report about Bugs/Improvements - Thread is maintained]

### ISSUE THREAD

**Issue by DHFan45** [DarklightGames/DarkestHour#1557]
- [ ] **== Bug Report/Description 01 -- DH Version: 11.3.0 -- Last updated: 25.01.2023 ==**

- The parachute is missing, the soldier simply floats in the air

![1](https://user-images.githubusercontent.com/123426586/214717248-a67401b0-cebc-4068-834d-fe48a360720c.png)

**Comment by MadDeathHound** [comment]
Just for reference, there are several of these figures ‘floating’ around the map. Found one earlier in the East Flank area.

**Comment by GDrukenmiller** [comment]
lol, I see why this happened. I'll fix it.
