### ISSUE TITLE
Tanks & Vehicles [Report about Bugs/Improvements - Thread is maintained]

### ISSUE THREAD

**Issue by DHFan45** [DarklightGames/DarkestHour#1560]
- [ ] **== Bug Report/Description 01 -- DH Version: 11.3.0 -- Last updated: 27.01.2023 ==**

- When you start in a new tank and switch to the gunner, there is usually already a projectile selected and loaded.
I noticed so far two russian tanks where this is not the case. Only after pressing "reload" the total number of rounds carried appears and a projectile is finally loaded.

Affects the following tanks:
T34/76 m42
KV-1S

![t1](https://user-images.githubusercontent.com/123426586/215212455-d80d7fae-3ab3-4640-968f-b48b3a0f58bc.png)
![t2](https://user-images.githubusercontent.com/123426586/215212468-7f06cc89-1b69-4173-b4df-47e30dc4e6d2.png)

**Comment by cmbasnett** [comment]
@DHFan45 Please do not make these "maintained" issues. Issues are supposed to be able to be *closed*, whereas I can't do that if all issues are rolled into one mega-ticket.
