### ISSUE TITLE
DH-Kharkov_Advance + DH-Armored_Kharkov_Advance [Bug Report]

### ISSUE THREAD

**Issue by DHFan45** [DarklightGames/DarkestHour#1563]
- [x] **== Bug 01 -- DH Version: 11.3.1 -- Last updated: 05.02.2023 ==**

- Faulty texture

![1](https://user-images.githubusercontent.com/123426586/216852389-1fe1321b-7006-4909-8896-eed955aa7462.png)

- [x] **== Bug 02 -- DH Version: 11.3.1 -- Last updated: 05.02.2023 ==**

- Faulty texture

![2](https://user-images.githubusercontent.com/123426586/216852396-0e3e7616-67f7-4067-aa4a-b61ce480016d.png)

- [x] **== Bug 03 -- DH Version: 11.3.1 -- Last updated: 05.02.2023 ==**

- Missing "Map Size" Database entry

![3](https://user-images.githubusercontent.com/123426586/216853241-bdbf1a39-ebe5-40fc-a43e-3be0fc8dd68a.png)

- [x] **== Bug 04 -- DH Version: 11.3.1 -- Last updated: 05.02.2023 ==**

- Faulty textures on the building + A hole in the map through which the player can fall off the map (tested)

[Please watch the Video Documentation of the Bug](https://mega.nz/file/XKQHGYya#8_2XZV4rLLZrUcf_AosVGUHoZYogIjB1tuk1OdKUl2s)

- [x] **== Bug 05 -- DH Version: 11.3.1 -- Last updated: 05.02.2023 ==**

- A hole in the map through which the player can fall off the map

[Please watch the Video Documentation of the Bug](https://mega.nz/file/GPgUmIpD#rIjA1AvZEsIMRJsRzmWA8R3wVvDpowRSX0OKLfoN-xE)

**Comment by GDrukenmiller** [comment]
Resolved hopefully all of these issues.

**Comment by DHFan45** [comment]
unfortunately not all bugfixes worked
