### ISSUE TITLE
Minefields are ineffective on Ten Aard Advance

### ISSUE THREAD

**Issue by DHFan45** [DarklightGames/DarkestHour#1577]
### Describe the bug
**== DH Version: 11.4.0 -- Information as of 03.03.2023 ==**

From a gameplay point of view, is it wanted to cross the destroyed railroad bridge? If not..

It is relatively easy, there is a "minefield" warning on the bridge, you have enough time (about 20 seconds) to cross the bridge without any problems.
Arrived on the other side of the shore there are no more mine warnings, except for a small section you can sprint across without dying.

### Steps to reproduce

N/A

### Screenshots

[**Video Record of the Bug**](https://mega.nz/file/qHZRGLIY#aRZ5nUs1pBsqiLyMX9D7EhRXn1jsS7a_o1rJMvX1uAU)

![0](https://user-images.githubusercontent.com/123426586/222788431-54208d1e-a049-4fff-aea0-fe3d1fed34c6.png)
![1 1](https://user-images.githubusercontent.com/123426586/222788525-b62a0fe5-4183-4080-9bf2-a95b058b6882.png)
![1 2](https://user-images.githubusercontent.com/123426586/222788552-ea18623a-8b12-436b-8f74-d29c4cacfbbf.png)
![2](https://user-images.githubusercontent.com/123426586/222788569-b15f74dd-72d1-442e-aebd-a0e6738111b1.png)
![3](https://user-images.githubusercontent.com/123426586/222788580-70592b98-2eba-4515-a83d-6be2516ddc93.png)
![4](https://user-images.githubusercontent.com/123426586/222788600-70378189-96ca-413e-8874-c1898d3ddaf1.png)
![5](https://user-images.githubusercontent.com/123426586/222788622-423cd55c-2b66-40b9-83e3-280fc0ccac6b.png)
![6](https://user-images.githubusercontent.com/123426586/222788634-9f0c8247-a651-49de-9364-64fb33d72957.png)

### OS

None

**Comment by GDrukenmiller** [comment]
I think this shouldn't be possible anymore? Have you tried since the last patch?

**Comment by DHFan45** [comment]
> I think this shouldn't be possible anymore? Have you tried since the last patch?

it was tested with the latest version. it was supposedly fixed in 11.4.0 but unfortunately that did not work

**Comment by DHFan45** [comment]
Here is a gameplay [video ](https://mega.nz/file/qHZRGLIY#aRZ5nUs1pBsqiLyMX9D7EhRXn1jsS7a_o1rJMvX1uAU)from today

**Comment by GDrukenmiller** [comment]
Yeah, something went wrong, the version on the server is not the correctly updated version. It seems I somehow committed the wrong one.
