### ISSUE TITLE
DH-Armored_Kommerscheidt_Clash

### ISSUE THREAD

**Issue by DHFan45** [DarklightGames/DarkestHour#1579]
### Is your proposal related to a problem?

I would like to make a suggestion about the map "DH-Armored_Kommerscheidt_Clash" in order to improve the quality and popularity of the map.

I have noticed the following:

Outdated minimap (the "infantry" version of the map has an updated minimap)
The map is very outdated and of low quality compared to the revised "infantry" version of the map

### Describe the solution you'd like

If you want to keep the map "Kommerscheidt" as an "Armored" version duplicate the "infantry" version of the map and change/update the vehicle layout and gametype.

**Comment by cmbasnett** [comment]
This map has been removed.
