### ISSUE TITLE
Missing Mapvote Database Entries - Update

### ISSUE THREAD

**Issue by DHFan45** [DarklightGames/DarkestHour#1585]
### Describe the bug

**-- INFANTRY Server 1**

DH-Endsieg_Advance => The map is completely missing in the map list 

**-- INFANTRY Server 2**

DH-Endsieg_Advance => Missing Mapvote Database Entries (Source, Allied Nation, Game Type, Map Size)

 **-- ARMORED Server**

DH-Armored_La_Feuillie_Advance => Missing Mapvote Database Entries (Source, Allied Nation, Game Type, Map Size)
DH-Armored_Black_Day_July_Clash_Event => Missing Mapvote Database Entries (Source, Allied Nation, Game Type, Map Size)

 **-- OTHERS**

DH-Arnhem_Bridge_Push => The map is completely missing in the map list, but is still present in the DH-Maps folder >> Please remove the file "DH-Arnhem_Bridge_Push.rom"

### Steps to reproduce

N/A

### OS

None

**Comment by MadDeathHound** [comment]
Arnhem was removed last year, due to it being both a buggy map, as well as poorly laid out

**Comment by DHFan45** [comment]
It is still in the DH Maps Folder thanks for the clarification
