### ISSUE TITLE
Missing Mapvote Database Entries MAY

### ISSUE THREAD

**Issue by DHFan45** [DarklightGames/DarkestHour#1600]
### Describe the bug

**-- INFANTRY Server 1**

DH-Endsieg_Advance 
==> The map is completely missing in the map vote list 

**-- INFANTRY Server 2**

DH-Endsieg_Advance
 ==> Missing Mapvote Database Entries (Source, Allied Nation, Game Type, Map Size)

 **-- ARMORED Server**

DH-Armored_La_Feuillie_Advance
 ==> Missing Mapvote Database Entries (Source, Allied Nation, Game Type, Map Size)

DH-Armored_Black_Day_July_Clash_Event
 ==> Missing Mapvote Database Entries (Source, Allied Nation, Game Type, Map Size)

 **-- OTHERS**

DH-Arnhem_Bridge_Push
 ==> The map was classified as deprecated, but is still present in the DH-Maps folder >> Please remove the file "DH-Arnhem_Bridge_Push.rom"

**_Please close this thread when the problem is solved. Thank you_**

### Steps to reproduce

N/A

### OS

None

**Comment by shiftycats** [comment]
Resolved in e26b2345042e37964edc12153e4e8139ac8a0ac1. 

Event maps don't need to be in the database. The rest is not relevant to missing map entries.

If a map is completely missing from the voting list, it was removed from the roster by the server admin.
