### ISSUE TITLE
Illogical maximum carrying capacity of Grenades

### ISSUE THREAD

**Issue by DHFan45** [DarklightGames/DarkestHour#1601]
### Hand grenades

Quantity that a player can carry at the same time:
Maximum amount of hand grenades belonging to your own faction = 3
Maximum number of hand grenades belonging to the enemy faction = 3

Total = 6
Thus the player can carry up to 6 hand grenades at the same time

Why is it then not possible to carry 6 faction-owned hand grenades at the same time?

### Smoke grenades

Quantity that a player can carry at the same time:
Maximum amount of smoke grenades belonging to your own faction = 1
Maximum number of smoke grenades belonging to the enemy faction= 1

Total = 2
Thus the player can carry up to 2 smoke grenades at the same time

Why is it then not possible to carry 2 faction-owned smoke grenades at the same time?

### Describe the solution you'd like

There should be a maximum and realistic amount of grenades a player can carry regardless of which faction the grenade belongs to
Suggestion:
Max 3  hand grenades per player
Max 2  smoke grenades per player

**Comment by Enfield-303** [comment]
You can have up to the maximum ammo count of any grenade you pick up, the maximum is defined on the weapons class and not on the pawn or the players faction, using the variables MaxAmmo, and InitialAmount.

**Comment by DHFan45** [comment]
Hello sorry but its not working like you say. please test it yourself.

If you a e.g. a German Rifleman you can carry max. 3  "Stielhandgranate 24"  not  6
But you can pick up additional 3 enemy grenades  = in total 6 grenades

you understand what i am trying to say?

**Comment by Enfield-303** [comment]
yes, that is how it is intended, you are capable of having more than 6 as well , each  grenade has a maximum of three, i.e. three stick grenades, three f1 grenades, three mills bombs and so on

**Comment by Enfield-303** [comment]
having 6 of your own grenades is illogical, the limits are to stop players from dumping grenade crates and running into a battle grenade spamming, to find and capture 6 grenades on your own is a feat

**Comment by DHFan45** [comment]
Ok i just do not understand the point of this system and also not the realism

how many hand grenades would and could a soldier carry in reality?

If it would be 6 why is it not possible to carry 6 grenades of the same type?

**Comment by DHFan45** [comment]
Ok i just do not understand the point of this system and also not the realism  **except to avoid nade spam**
how many hand grenades would and could a soldier carry in reality?
If it would be 6 why is it not possible to carry 6 grenades of the same type? 

with the hand grenades it might be good to limit them to a maximum of three in general in this case?

With the smoke grenades it is annoying when I as a squad leader already have one with me and another carrier next to me dies and I am not allowed to take a second of the same type.

Would it be possible to change this so that you can carry a maximum of 2 regardless of type?

**Comment by Enfield-303** [comment]
The system was carried over from red orchestra, it has been like this for 14 years.

There is no limit to the amount of grenade TYPES you can pick up, there is no hard cap at the number 6, there is however a limit to the amount of each grenade TYPE you can pick up. shown here.

![image](https://github.com/DarklightGames/DarkestHour/assets/112338501/4bb17321-7ddf-49df-b5b3-1e01e11a1b24)
![image](https://github.com/DarklightGames/DarkestHour/assets/112338501/062c0282-9796-4a46-a10c-f9c5735e51b3)
![image](https://github.com/DarklightGames/DarkestHour/assets/112338501/8b888674-0951-43c7-a504-f8d5a4d6dd6f)

^^
seen here

The system, from my point of view doesn't need changing. if you are capable of scavenging 6 grenades all without using them then it is at the power of you to do what you want with them. allowing every person to take 6 grenades from a crate would cause havoc, and limiting them to three takes away the fun from scavenging corpses for gear.
