### ISSUE TITLE
Offset error in bullet's player hit detection

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#260]
Originally reported by: **Andrew Theel (Bitbucket: [AndrewTheel](http://bitbucket.org/AndrewTheel), GitHub: [AndrewTheel](http://github.com/AndrewTheel))**

---

Today MattUK and I noticed a very large offset of the player hit boxes.  I was able to kill him by shooting a good foot to his right, and shots on his left could miss even though they looked like they should hit.  Happened with rifleman/garands.  I've noticed similar occurrences in the past, but though it was in the projectile code, but this time it felt like a hit-box issue.

MattUK is going to look into the hit boxes for both pawns and driver/commanders/passengers.  But I think this is important enough for all of us to resolve and ASAP.  We may also be able to use debug commands in MP to debug this issue.

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/261

**Comment by dynamittt** [comment]
Hello, I see this "issue" is closed long time ago but I have some questions regarding tracing HPs on Pawns.
First of all I don't understand how HPs are represented in the "ingame" world. Of course they are somewhat "part" of the pawn, connected to certain bones and moved in real-time with them, but I dont know what type of "actors" are they considered to be(if they can even be labeled as Actors at all)? What Collision params to they have? How can I trace/interact with them using custom funcs()?

What will happen if I hypothetically set the BWAttachment's radius to be so _small_, that the pawn will actually "protrude" through it and be "bigger"?

Can't we trace the HP's at all without using BWA? Example: launch a trace and see if we hit a Pawn, and if so, just do the normal HPTrace() to see which HP we hit?
What's so special about class ROCollisionAttachment extends Actor
	native;
That is the actual Parent of ROBWAttachment?
The only info we have is: // An additional collision cylinder to assist in detecting special traces
Thanx.

**Comment by dynamittt** [comment]
OK, I did a test with friend today, I set the BWAttachments radius to just **ONE**, and HitPoints seemed to work just fine. We shot couple of thousand of rounds with normal BWA radius and radius set to 1 and HitPoints registered hits exactly the same way. Anyone?
