### ISSUE TITLE
The Half-Track exploded many times when destroyed

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#322]
Originally reported by: **Andrew Theel (Bitbucket: [AndrewTheel](http://bitbucket.org/AndrewTheel), GitHub: [AndrewTheel](http://github.com/AndrewTheel))**

----------------------------------------

When testing Freyneux I was driving an Axis HT around along the edge of the map and took a Stuart round which killed my HT & me.  However, the HT began to explode over and over very quickly.  Not sure if this is a network problem or client, however it could be very dangerous when happening on a large scale.  The only thing I can think of on why it wasn't happening 100% of the time, is it was done from far range and I was along side a blocking volume/tree line.

----------------------------------------
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/323

**Comment by AndrewTheel** [comment]
Unless we get more reports or progress into what could be causing this, I'm closing for now, as I have not seen this issue in a long time.
