### ISSUE TITLE
Voice chat no longer works correctly after 32 players and is broken for some players

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#372]
Originally reported by: **Andrew Theel (Bitbucket: [AndrewTheel](http://bitbucket.org/AndrewTheel), GitHub: [AndrewTheel](http://github.com/AndrewTheel))**

---

**Here are the issues:**
- Public and Local channels will break after 32 players are on the server (break for everyone).
- It is perceived that players that join a server when it already had 64 players do not have the ability to talk or hear voice.  And must reconnect once player count is below 64 to regain voice.

**Goals:**
- Stop local channel from breaking after 32 players.  Public is of little concern.
- Prevent any issue with a 64 player cap on voice chat
- Stop any unnecessary network/server memory usage by creating private channels, unless we find a way to support them so players in a tank crew or squad can form their own channels.  However it might be best to create a new entity that manages the "group" channel.

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/373

┆Issue is synchronized with this [Trello card](https://trello.com/c/W6qU8NAA)

**Comment by cmbasnett** [comment]
As a result of working on squad channels, we discovered conclusively why local chat breaks after 32 players. A lot of the logic surrounding whether or not the server thinks a user is in a voice chat channel hinges on masking and bit-wise operations. Here's an explanation of how it works:

Upon connecting, each player is assigned a `VoiceID`, from `0` to `31`. This value is assigned to the `PlayerReplicationInfo` of the player.

Every voice channel has it's own "mask", which is a 32-bit integer, each bit indicating whether or not players are in that channel or not. As a result, it can only keep track of the membership status of 32 players. What happens when the player count exceeds 32 is beyond me. As far as my memory serves, no one is able to talk in that channel anymore.

Anyways, in order to fix this, it seems the trick is to override `IsMember` in `VoiceChatRoom`, and completely bypass any bit-masking or any such scheme. This is how the "Team" chats work past 32 players, and subsequently how our Squad chat works as well. At the time of this writing, we haven't actually yet tested the squad channel with 32+ players, but we suspect with a high degree of confidence it will work.

Fixing local chat *may* be possible if we can get it to simply always say all members are a part of the channel. Our local chat, however, is vastly inferior to other games (no 3D positional sound, no volume attenuation), and ditching it outright in favor of squad chat is probably a more pragmatic solution.

**Comment by dynamittt** [comment]
Hello, haven't been here for quite a long time.
I saw you made some changes to the voice system, and although I may not agree with some of the functionality, that's not the reason I'm writing this.
I have always known that there is no locational 3D voice within the 'Local' chat, BUT....
last couple of days I've been tampering with custom voice code, including DH one,
and while testing with a friend we stumbled upon something .....weird?
Working stereo voice, but no idea how this is happening. I continue going through various pars of the voice code, but still can't replicate this on my own system, even with exactly the same setup:
Here's a video recorded by a friend , please use stereo headphones: https://yadi.sk/i/X7GYoLR53L5vEk
I can't even find where in code the player location is used to determine how the voice should sound. (except the distance limitation for voice chat). If you have any idea where this might be happening, some light may be brought upon this mystery....

**Comment by cmbasnett** [comment]
This was fixed a while ago, just closing it off now.
