### ISSUE TITLE
Bullet pre-launch trace does not play any bullet whiz/snap sounds

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#381]
Originally reported by: **Bitbucket: [Matt_UK](http://bitbucket.org/Matt_UK), GitHub: [Matt_UK](http://github.com/Matt_UK)**

----------------------------------------

A successful PLT, i.e. hit something valid and fairly close range, means the bullet projectile never gets spawned. An optimisation, mainly for the network, with the server handling any damage directly from the PLTand telling clients to show relevant hit effects.

But it never players any whiz/snap sounds, which would normally occur if a bullet projectile was spawned. The trace passes WhizType 0 into the HitPointTrace() that would normally handle these effects, with the comment "it's close", i.e. range. WhizType 0 means no sounds.

The problem is that to know what WhizType to use, you have to know how far away the bullet was fired from the player that the PLT may hit, and also whether it was fired by a friendly player. A bit chicken and egg, as the PLT doesn't know what it might hit when it does the trace !

----------------------------------------
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/382

**Comment by handsm** [comment]
I've been working on a fix for this and believe I have a good system. Will commit, so we can test, although I've tried on my own dedicated server with 2 clients connected and it seems ok.

I've thoroughly explored how RO whizzes are handled and traced how the system works on server, clients and single player. There is considerable duplication and inefficiency in the current system, with quite a lot of pointlessly replicated variables, as well as some needless server and client processing. So we can get the added bonus of reduced net and CPU load.

I will post a thorough explanation.
