### ISSUE TITLE
Infantry binocular overlay vastly different from vehicle binocular overlay

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#405]
Originally reported by: **Colin Basnett (Bitbucket: [cmbasnett](http://bitbucket.org/cmbasnett), GitHub: [cmbasnett](http://github.com/cmbasnett))**

---

Almost not worth mentioning because I've never noticed this until now! Note also the the magnification levels are different as well.

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/406

┆Issue is synchronized with this [Trello card](https://trello.com/c/uJUbTsvo)

**Comment by dynamittt** [comment]
Hello, the "classic" binocs that incorporate the "triangles" overlay, are a Zeiss WWII binoculars.
The triangles are placed on top of enemy vehicles, and after the crewmember recognizes the vehicles, based on vehicles length he can estimate the approximate distance to the enemy vehicle. Same goes for tank sights on most german and soviet tanks. Unfortunately I cannot find information whether the Zeiss binoculars had an actual overlay, but I guess Alan Wilson from TWI already did this research.
Also is there any correct way to calculate zoom, FOV and the scaling of the texture itself?
Lets you have a 4x50 binoculars (4x magnification and 50 mm lense, how is the FOV calculated ingame, to represent the real-world feeling when using such optics?

**Comment by handsm** [comment]
Removed v8 milestone as a minor issue and no idea what's involved without spending some time on it. Suspect substantial changes required, perhaps involving textures etc.

**Comment by shiftycats** [comment]
Resolved.
