### ISSUE TITLE
Add to Favorites button does not work

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#419]
Originally reported by: **Colin Basnett (Bitbucket: [cmbasnett](http://bitbucket.org/cmbasnett), GitHub: [cmbasnett](http://github.com/cmbasnett))**

---

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/420

┆Issue is synchronized with this [Trello card](https://trello.com/c/iyJ5Tw4f)

**Comment by handsm** [comment]
This works fine for me and as far as I recall it always has. Is it a problem for others?
