### ISSUE TITLE
Hull machine-gun traverse speed seems too slow

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#426]
Originally reported by: **Colin Basnett (Bitbucket: [cmbasnett](http://bitbucket.org/cmbasnett), GitHub: [cmbasnett](http://github.com/cmbasnett))**

---

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/427

**Comment by handsm** [comment]
Proper fix for this ancient issue in commit https://github.com/DarklightGames/DarkestHour/commit/d590562b1aab6c9828185ca65cecd7ec54e55e5b !!

This has always bothered me and I'm so glad to have finally got to the bottom of it. Vehicle MGs now rotate at desired rate, with no difference between multiplayer and single player and irrespective of frame rate. Means 1st person weapon rotation perfectly matches 1st person rotation speed, so all players see the MG facing the same direction.

:)
