### ISSUE TITLE
Can hear AT gun reload from very long distance away

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#436]
Originally reported by: **Andrew Theel (Bitbucket: [AndrewTheel](http://bitbucket.org/AndrewTheel), GitHub: [AndrewTheel](http://github.com/AndrewTheel))**

----------------------------------------

This may be the case on all AT guns, not just the Flak38

----------------------------------------
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/437

**Comment by dynamittt** [comment]
Similar issue: can hear smoke grenade emitter sound from very far away. Was in a tan on bridgehead, and I could hear a smoke emitter which was at more than 150 meters away. Never had such an issue before. Cannot say if it was tank smoke shell or smoke grenade.

**Comment by handsm** [comment]
This certainly isn't happening now, so I'm closing this issue. I'm sure the problem cropped up in the past, but the vehicle/gun cannon code has changed substantially since then, and whatever problem caused this must have been fixed.
