### ISSUE TITLE
Players are sometimes unable to fire or reload AT guns

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#449]
Originally reported by: **Colin Basnett (Bitbucket: [cmbasnett](http://bitbucket.org/cmbasnett), GitHub: [cmbasnett](http://github.com/cmbasnett))**

----------------------------------------

Note how there is no ammo switching indicator in the screenshot.

----------------------------------------
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/450

**Comment by handsm** [comment]
Closing this one as I believe it is resolved & doesn't require further work. Any future problems will be immediately apparent and we can re-open if required (but fingers crossed !).
