### ISSUE TITLE
Anti-tank rockets can appear to have been fired when no round was actually fired

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#460]
Originally reported by: **Colin Basnett (Bitbucket: [cmbasnett](http://bitbucket.org/cmbasnett), GitHub: [cmbasnett](http://github.com/cmbasnett))**

---

This is a bizarre bug that happens very infrequently, but just enough to be annoying.

The firing sound and animation happens for the client, but no round is actually fired. The round is able to fired afterwards, however, as though nothing ever happened. Wild speculation, but this could be some sort of inconsistency between when the client thinks it can fire and when the server thinks it can fire.

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/461

┆Issue is synchronized with this [Trello card](https://trello.com/c/l2hozCVz)

**Comment by AndrewTheel** [comment]
This might be related to (but not the same bug oviously) the same issue with the FOV getting stuck (zoomed in) after sprinting right when being assisted for reload.

**Comment by AndrewTheel** [comment]
In a no lag environment I can almost say this happens 100% of the time on the first 1 or 2 shots from a AT weapon after being assist reloaded.

**Comment by cmbasnett** [comment]
This is almost certainly a problem where the client believe he can fire (and so does the firing animation and sound), but the server disagrees and the projectile is never spawned.

**Comment by cmbasnett** [comment]
I think the cracked the case on this one here. Here's an explanation:

It all starts here:

    simulated function bool CanFire(optional bool bShowFailureMessage)
    {
        if (!bUsingSights)
        {
            // ...
            return false;
        }
    
        return true;
    }

This function is run on *both the server and the client* before attempting to fire the weapon. Seems innocuous enough, but there's a very subtle bug going on!

The variable `bUsingSights` is defined in `Weapon`. It's a simple, replicated, server-to-client `bool`. Easy enough, right? Well, let's have a look at the code that actually modifies the state of this variable:

    simulated function ZoomIn(optional bool bAnimateTransition)
    {
        //...
        bUsingSights = true;
        //...
    }

This also gets run on both the client and the server..._wait a minute_, wasn't this supposed to be a server-to-client replicated bool? Why is the client modifying it? **Surprise**!

    simulated function PerformZoom(bool bZoomIn)
    {
        // ...
        if (bZoomIn)
        {
            // ...
            ZoomIn(true);
    
            if (Role < ROLE_Authority)
            {
                ServerZoomIn();
            }
        }
        else
        {
            ZoomOut(true);
    
            if (Role < ROLE_Authority)
            {
                ServerZoomOut();
            }
        }
    }

`PerformZoom` is called on the client, modifying it's own version of `bUsingSights` and then sending the `ServerZoomIn` client-to-server function call. This opens the gate for *timing issues* where the client has `bUsingSights` set to `true`, but the server hasn't yet gotten the message and its `bUsingSights` is still set to `false`. This client/server inconsistency is why we see the bug manifest as it does.

The "true" solution would be to never directly modify `bUsingSights` on the client, and move to a server-authoritative model. However, virtually all of the weapon code makes the assumption that the client is going to be setting its own version of `bUsingSights`. As a compromise, a decent (but dirty) solution would be to omit the `bUsingSights` check from the server, relying entirely on the client.

**Comment by cmbasnett** [comment]
Fixed in commit 44bf2af.
