### ISSUE TITLE
Turret machine-gun firing effects can become stuck and remain

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#461]
Originally reported by: **Andrew Theel (Bitbucket: [AndrewTheel](http://bitbucket.org/AndrewTheel), GitHub: [AndrewTheel](http://github.com/AndrewTheel))**

---

This is actually a bug that can happen on many hull/turret MGs also.  However in the case of the quad 50, it doesn't fix if the gunner fires again.  Even once the gun was destroyed and deleted it remained.  I'm not sure of how to reproduce, but it might have something to do with spectating it.

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/462

**Comment by handsm** [comment]
Is this ever an issue? If no one has seen it or can re-create it, I think we should close it. Can always re-open if seen/reproduced in future. Originally this was mostly related to a specific bug in the M45's setup, prior to the DH 6.0 release, but that was fixed ages ago.

**Comment by handsm** [comment]
Closed as per above comment. Re-open if anyone finds bug still present and can be reproduced.
