### ISSUE TITLE
Passenger name text HUD position is now overlapped with the capture bar for the commander

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#466]
Originally reported by: **Andrew Theel (Bitbucket: [AndrewTheel](http://bitbucket.org/AndrewTheel), GitHub: [AndrewTheel](http://github.com/AndrewTheel))**

----------------------------------------

I moved the passenger names around so it would not overlap with anything, but I guess I never thought about the capture bar.  This bug may not be worth fixing for 6.0, as this is kinda rare at least compared to how often the text was overlapped before.

----------------------------------------
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/467

**Comment by AndrewTheel** [comment]
This may be fixed with the squad HUD changes we've been making, so for now I'll put this on hold.

**Comment by AndrewTheel** [comment]
Assigning to Basnet as this will need to be reviewed along with squad features in the future.

**Comment by AndrewTheel** [comment]
Closing for now, as we will revisit this "issue" when we implement the squad system.
