### ISSUE TITLE
Opel Blitz front left wheel bolts are not parented correctly to the wheel

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#48]
Originally reported by: **Colin Basnett (Bitbucket: [cmbasnett](http://bitbucket.org/cmbasnett), GitHub: [cmbasnett](http://github.com/cmbasnett))**

----------------------------------------

----------------------------------------
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/49

**Comment by cmbasnett** [comment]
I want to have Piotr re-make this vehicle entirely.

**Comment by handsm** [comment]
Fixed in SVN update 1084.

Noted that intention is to re-make vehicle, but as discussed, it was a 10 minute fix to a small file and once the glitch had been pointed out it was just kinda looking at me whenever I saw an Opel in a map ! :)
