### ISSUE TITLE
Several allied turrets are off centre, sunken, or clash with the hull mesh.

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#484]
Originally reported by: **Bitbucket: [Matt_UK](http://bitbucket.org/Matt_UK), GitHub: [Matt_UK](http://github.com/Matt_UK)**

---

Several are off centre in X and or Y.
Some are slightly sunken into the hull.
Some clash, sometimes badly, with hull mesh as the turret turns.

Shermans are nearly all affected, with all the problems. M4A1 and especially the 75mm turret are particularly bad. (Suggest both are candidates for a re-make for a future release; they have several issues).

Also Jackson (off centre) and Cromwell (off centre & sunken).

Suspect some problems are caused by modeler/animator assuming turret's 'Turret_placement' bone would attach to hull mesh's 'Turret_placement' bone, but that doesn't happen. An attached actor like a turret is always attached with its own origin on the base actor's attachment bone. Any turret model with it's 'Turret_placement' bone (or other root bone) away from the origin is suspect, as it suggests the modeler/animator may have been trying to use that as an attachment offset, which won't work.

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/485

**Comment by handsm** [comment]
A thorough/proper fix for the Cromwell's turret implemented as part of substantial model re-work committed in SVN update no.1161. Everything centered and symmetrical.

See https://github.com/DarklightGames/DarkestHour/issues/530 for more details.
