### ISSUE TITLE
Primary weapon combo box can appear empty upon entering the deploy menu

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#495]
Pretty sure this is a multi-player only bug. Happened on Stoumont while I was playing as a Combat Engineer.

![2015-12-29_00007](https://cloud.githubusercontent.com/assets/5035660/12048216/edde570a-ae8c-11e5-8907-4c5fd0f082a9.jpg)

┆Issue is synchronized with this [Trello card](https://trello.com/c/6nuYLvd2)

**Comment by AndrewTheel** [comment]
If you get this again, try hitting esc and then esc again and see if it reappears.

**Comment by AndrewTheel** [comment]
I'm pretty sure we fixed this bug.
