### ISSUE TITLE
Cap points in tank/combined arms maps are broken

### ISSUE THREAD

**Issue by magicdutchman** [DarklightGames/DarkestHour#502]
Several maps are uncappable after the first objectives are captured.

**Comment by cmbasnett** [comment]
You'll have to be more specific. Which maps?

**Comment by AndrewTheel** [comment]
This is an issue with all maps.  It is because for us to support more than 16 objectives (6.0 supports 32 objectives) we had to change the MasterObjectiveManager.  We now have a DHObjectiveManager which the MasterObjectiveManager will NEED to be converted to for the objectives to flow correctly.

**Comment by magicdutchman** [comment]
Since it's closed I hope it is fixed in the current update?
