### ISSUE TITLE
Environmental tank sounds are indistinguishable

### ISSUE THREAD

**Issue by magicdutchman** [DarklightGames/DarkestHour#503]
The engine sounds the tank produce are identical making it impossible to tell the difference anymore.

**Comment by AndrewTheel** [comment]
Well it's not the engine sounds, as I have not changed those.  However, the track sounds (even though I've set them to be different sounds) sound very similar and can "drown" out the engine sound making them much harder to differentiate.  I agree and I don't like that I can't even tell a different myself, I will look into this at a later time.

**Comment by magicdutchman** [comment]
Cheers!
