### ISSUE TITLE
Players can still receive "rally point set" message

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#507]
Rally points can be set, internally, but we don't ever display them anymore (will be re-instated in some form when we implement the squad system). Disable this message from displaying.

![2016-01-01_00004](https://cloud.githubusercontent.com/assets/5035660/12078198/053d2448-b1bd-11e5-9aaa-d7ded9812163.jpg)

┆Issue is synchronized with this [Trello card](https://trello.com/c/RT0pVtId)

**Comment by dynamittt** [comment]
Another ancient RO bug, I have been able to set a RP even while playing as rifleman. No idea how it happens though.......

**Comment by dynamittt** [comment]
I made an interesting discovery recently: while you are opening the map, start clicking fast "on the map", you can hear the sound that is played when you set a rally point. Of course nothing happens, but the sound is clearly there. It only happens while the map is being "opened".

**Comment by AndrewTheel** [comment]
Gonna close this as I think its now invalid.
