### ISSUE TITLE
Players are able to spawn without weapons

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#508]
I have no idea how this is happening, but I've seen a few reports here and there of players spawning without weapons. Happened on Bridgehead to an Axis player, will update with more info if more reports come in.

┆Issue is synchronized with this [Trello card](https://trello.com/c/htrHLjNh)

**Comment by magicdutchman** [comment]
It might have been on the Arnhem bridge beta map, where I spawned as a sniper class without a rifle, and the pistol was classified as the rifle.

**Comment by AndrewTheel** [comment]
I think this issue could be several different issues.  On DH-Vierville as Allies, I often seem like I don't have a weapon, but actually do.  I cannot seem to select or bring up the weapon, or drop it either.  But when I go to pick up another weapon it suddenly appears and everything functions like normal.  This issue might be related to parachutes or teleporting, or both.  Other times I've spawned as AT guy on Bridgehead to realize I don't have it at all.  

I'm not sure how this happens at all, but I think I remember it happening with MDVs before 6.0.0 update and I'm pretty sure I've heard others in 5.1 complain about not having a weapon after spawn.  So I'm not sure we should blame MDVs, 6.0.0 update, or anything in particular.  We may have to solve this by a long term debug method, which will take lots of time and effort to resolve.

**Comment by AndrewTheel** [comment]
I'm pretty sure this has to do with packet loss and the client not know to called PostBeginPlay() or something.  Packet loss can occur when the packet to the client is just too big.  As I've been doing some testing and if I spawn a lot of bots (even on a local server), some of them fail to run the PostBeginPlay() function, or something to that extent.  More special testing to get to the bottom of this bug will be required.

**Comment by cmbasnett** [comment]
Without a reliable way to reproduce this this will probably need to be kicked down the road. Removing the 8.0 milestone on this.

**Comment by AndrewTheel** [comment]
Going to close this as I think it is just a packet loss problem and is either the individual player's fault (poor connection), which can have an ocean of other problems. Or its a problem with the server network overhead, which can be improved with level optimization and server performance maintenance.

Also I think my original point about parachutes stands, but that should be a separate issue and probably already is.
