### ISSUE TITLE
Mortars can "disappear" when operator un-deploys

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#509]
This has been in since v5.0 and, though it's happening less, it's still happening. It almost certainly only happens in a multi-player environment; replication issues are almost certainly the issue. The mortar doesn't actually "disappear", but the player un-deploys and they have no weapon selected. The only way to bring it back is to drop all other weapons.

┆Issue is synchronized with this [Trello card](https://trello.com/c/VdQPHcwZ)

**Comment by cmbasnett** [comment]
Taking off of 8.0 milestone as this happens quite infrequently and we got bigger fish to fry. Changes coming to the mortar system in a 8.x update might make fixing this a waste of time anyways.

**Comment by AndrewTheel** [comment]
Yea this is a packet loss issue, which is either the individual's network issue or the server. The server issue can be resolved by level optimization and network performance maintenance.
