### ISSUE TITLE
Machine-guns can fire "blanks" if deployed while changing stances

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#513]
This is a long-standing RO and DH bug for years, and I **finally** figured out what causes it.

On a multiplayer server, deploy your machine-gun _while_ changing stances (from crouch to stand or vice versa). There is a very high probability that the machine-gun will be shooting blanks.

It's interesting to note that the "bipod deployed" icon doesn't appear when the deployment actually fails.

![2016-01-06_00003](https://cloud.githubusercontent.com/assets/5035660/12140480/2b11c338-b41d-11e5-916c-1a695da50cc0.jpg)

![2016-01-06_00002](https://cloud.githubusercontent.com/assets/5035660/12140494/473945f4-b41d-11e5-9c39-104af28a20c3.jpg)

┆Issue is synchronized with this [Trello card](https://trello.com/c/cmsdtjtk)

**Comment by dynamittt** [comment]
This is fixed since 5.1 or possibly earlier. I haven't seen it in DH for a loooong time.

**Comment by cmbasnett** [comment]
Nope, still around.

**Comment by cmbasnett** [comment]
I believe I know what the problem is here. In the `StartCrouch` and `EndCrouch` events in` ROPawn`, there are calls for the weapon to un-deploy. Since you are essentially able to bipod while transitioning between being crouched and un-crouched, I believe there's an opening for the bipod state to be established and then subsequently undone a couple frames later via the crouching functions. This can result in the client and server disagreeing as to whether or not the player has their bipod deployed, resulting in "firing blanks" we see, where the client believes they are deployed but the server disagrees and never fires the bullets.

Not sure how to *truly* fix this, but a workaround has been done that should cover us for 99% of cases. It's a two-part fix. First, we limit the rate at which players can toggle between crouching and standing (frankly, it's a wonder this was never done to begin with). Doing this will ensure that there won't be tons of rapid toggle-crouches (which can get out of sync easily when not throttled). Secondly, and most importantly, we don't allow the client to deployif they have recently crouched or un-crouched. This should allow plenty of time for the crouched state to propagate to the server and, importantly, it doesn't allow the client to bipod the weapon *during* the transition from crouch to stand of vice versa, which is very likely the source of the bug.

Fixed in commit 49668b94d62f74659d334fd6ded0924f17ec694b.

**Comment by dynamittt** [comment]
I have no idea why on earth Theel has not relayed all the info to you when we did online tests with him (this was probably more than a year ago). This problem was reliably fixed in previous versions. Anyway I will contact you on Steam to talk about it in detail
In the meantime...
The vanilla deploy mechanic **automatically** moves the player to crouched position if he is standing while deploying to a cover/obstacle/window/sandvag whatever that is "**crouch-heighted**"
This was of course a good solution, but it caused _other_ problems, that's why people simply disabled it  years ago using mutators/custom code....
