### ISSUE TITLE
Implement a way for vehicle crewmen to call out directional warnings

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#514]
# Problem

One of the biggest problems with team tanking is the lack of easy communication channels. Unless players have microphones, even the most trivial of communication is needlessly arduous to perform.

The most common thing you'll want to communicate to your crew-mates is the direction of enemy threats. To aid in this, we want to create a system whereby tank crewmen can quickly (with the press of an easily accessible button) call out the "o'clock" direction of enemy threats to all occupants of the vehicle.
# Solution

Player 1, 2 and 3 all crew a tank together. They take their tank out to front and are gunning down infantry to the tank's 10 o'clock. Suddenly, the driver notices an enemy tank off in the 2 o'clock direction moving to flank them. Now the driver _could_ fumble around to type in "enemy tank 2 o'clock" as fast as his pudgy fingers can, or he could try and remember the exact key combination needed to call out "Enemy to the right!" in the voice menu. Both are cumbersome; we can do better than that!

Instead, our sharp-witted driver would look in the direction of the threat and simply press F, for example, and the entire tank crew would be alerted via voice command (eg. "Enemy to the right!"), and a flashing red indicator would briefly (1 or 2 seconds) appear on all of the crew's vehicle status HUD display, like so:
![callout_example](https://cloud.githubusercontent.com/assets/5035660/12139591/5d7366e4-b416-11e5-84c9-cf759d898be2.png)
Now, in an instant, the commander (and any other crewmen) know the general direction of the approaching enemy and can turn the cannon to deal with the threat.
# Important Notes
- Vehicle passengers should not be able to make call-outs.
- Call-out frequency must be limited to mitigate the potential for abuse.
- This is not a "spotting" system like in other games; the call-out is meant to simply indicate the general direction of a threat. The precision of the call-out would be limited by the player's directional accuracy when he made the call-out as well as the imprecise nature of the voice command and HUD warning that would follow.
- The voice commands to accompany the call-out would be "Enemy to the left/right/front/rear". 11-1 o'clock would be considered the "front", 1-4 o'clock would be the "right", 4-8 o'clock would be the "rear", and 8-11 o'clock would be "left".

┆Issue is synchronized with this [Trello card](https://trello.com/c/USYuefo5)

**Comment by AndrewTheel** [comment]
Gonna close this, as its nearly pointless, just use a damn microphone and say enemy at 1'o'clock, if players don't have a mic and are team tanking, they have much larger fish to clean before getting to this.
