### ISSUE TITLE
 Resupply area icons should indicate their type

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#515]
We have multiple different kinds of resupply areas: mortar-only, infantry-only, vehicle-only and universal. Unfortunately, on the situation map, they all have the same icon. This means that you have to guess or find out the hard way if a resupply point has the type of ammunition you want.

To eliminate this frustration, we need only create a handful of different icons for the various types!

**Comment by Silentspy** [comment]
Maybe a utility color ? #F38630 or #D79A27

I can do it if you guys need a hand :)

**Comment by cmbasnett** [comment]
A (slightly) different color could be used for each in addition to having a different icon for each, that is a good idea.

The specifications are simple, a `64`x`64` circular icon. They need to be easily distinguishable even when viewed at a thumbnail resolution.

We need 3 types:

* Mortar (a silhouette of a shell for the icon)
* Vehicle (a top-down/profile silhouette of a tank for the icon)
* Infantry (perhaps two crossed rifles or some other icon)
* All (we will just use the existing one)

The 3 types should have a similar visual style as the existing one.

**Comment by AndrewTheel** [comment]
This is on our roadmap.  The idea was not only to have it distinguishable on the map, but also in the level.  

- Need obvious mortar ammo box (indicates that mortar ammo is available)
- Need obvious tank ammo box (indicates that tank ammo is available)
- Need obvious infantry ammo box (indicates infantry ammo is available)
- Need separation of Allies, Axis and Both.
- Could also include variant icons, to indicate ammo type on the overview.
- Ammo caches are destructible by the enemy and must be protected
- Ammo Trucks can drop ammo caches

**Comment by AndrewTheel** [comment]
We will visit this feature when we setup a new supply system.
