### ISSUE TITLE
Some tanks' hull machine-guns have pitiful lateral range

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#517]
Something seems off here. The lateral range of a lot of (especially German) tanks seem to be inconsistent, erring on the side of too-narrow. The Panzer IVs, for example, seem to only have about 20 degrees of total arc to work with, while similar hull-machine gun configurations on other tanks (Tiger I, Panther etc.) seem to have a much wider arc of fire.

_Assuming_ that these were all essentially the same, I would expect the arc of fire to be more or less comparable.

This could very well be historically accurate. If it is, we should leave it as is. If not, we should definitely increase the arc of fire on a number of these hull machine-guns.

**Comment by handsm** [comment]
30 minute job if there is agreement to make the changes - it is basically a historical research/consensus issue. Pretty sure none of the MGs have changed in version 6; I haven't changed any like this.

The only think I can think of is perhaps the lateral range on a hull MG is dependent on how roomy the internal compartment is, i.e. how much room does the MG operator have to twist sideways? If that is the case then I'd think the operator in a large tank like a tiger or panther would probably have more 'elbow room' that in smaller vehicles. Maybe .....

**Comment by AndrewTheel** [comment]
The issue is really only with 1 PIV, I believe the other PIV types are fine.  Which is what concerned us, why is 1 PIV limited in yaw and others not?

**Comment by cmbasnett** [comment]
It's actually most PIVs.

**Comment by handsm** [comment]
All panzer IV's share a common MG & always have (at least since DH 5.1). Code classes are DH_PanzerIVMountedMGPawn & DH_PanzerIVMountedMG.

**Comment by cmbasnett** [comment]
Gonna close this then.
