### ISSUE TITLE
Ally tank armor to weak!  Game is DOOMED!!!

### ISSUE THREAD

**Issue by AZREIAL9** [DarklightGames/DarkestHour#519]
One major problem is that the ally tank armor is way to weak.  Everyone wants to play Axis becasue of this.  The creators should "Armor Up" the Ally tanks so that this game does not die.  There is only a hand full of servers out there as it is.  I was going to start a server, but am having 2nd thoughts about it becasue as it is, this game id doomed!  Nobody wants to play  a game, or start a server that is totally one sided.  Thin hard about your next move Developers!

**Comment by cmbasnett** [comment]
Welcome to our GitHub. This issue board is for reporting technical issues or enhancements. This is neither of those. If you want to start a discussion on this topic, please post on our [Steam Community forum|https://steamcommunity.com/app/1280].
