### ISSUE TITLE
Player is protected behind breakable glass

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#521]
A destroyable static mesh actor (class RODestroyableStaticMesh) can be set with bWontStopBullets=true, meaning a bullet will break it and carry on in flight, hitting anything behind it.

Typically this will be glass, for example there are several breakable glass panes on the target range map, on the low walls next to each spawn building.

A player standing behind the glass and fairly close to it, will not be hit by a bullet fired at him, through the glass. This is due to the special way player hit detection is handled, by detecting hits on the player's bullet whip attachment instead of the payer, then doing a special HitPointTrace to check if the bullet actually hits any body parts. The bullet collides with the surrounding whip, in front of the glass, then traces a hit on the glass, not the player, so ignores the collision and carries on. Next the bullet collides with the glass and breaks it, again carrying on. The bullet then passes through the player, because bullets don't detect hits on players, only on their whip attachments.

**Comment by handsm** [comment]
I have a fix for this, which I have tested as part of modifying bullet whiz handling, especially for pre-launch trace. I have tested and it seems ok, but best tested along with PLT/whiz changes, as are bound up and can't be readily (or productively) separated.

**Comment by dynamittt** [comment]
I think you might have just made it possible to add non-bugged bullet penetration haha!
There was a problem, where the player would not get hit if he was standing right behind a wall or SM that was penetrated. Had to do something with RoBulletWhip attachment, and I guess you nailed it. Should we expect penetration in the next major update? :)

**Comment by cmbasnett** [comment]
Going to close this down unless anyone notices more problems.
