### ISSUE TITLE
Vehicle: Coax MG fire long delay.

### ISSUE THREAD

**Issue by dynamittt** [DarklightGames/DarkestHour#524]
Played as tanker couple of rounds today, and I noticed that there is delay between "fire" and actual coax MG operation. Is this how its supposed to be?
Another complaint I have is the low pivoting speed of tank hull MGs. Tried tampering with mouse sensitivity settings, I can barely look straight forward through scoped weapons now, but the coax MGs still feels extremely clumsy.

**Comment by handsm** [comment]
There's certainly no deliberate delay on firing a coaxial MG. Any delay in purely down to the multi-player network environment.

When you fire, the signal has to get to the server. Then it has to do its business, including spawning a bullet projectile. Then it has to check that bullet actor for network relevance for all net clients, then replicate the actor over the network to all those clients, along with various other information relating to firing, as well as the fire sound. By the time the bullet gets replicated to you, it will have traveled a certain distance - how far depends on the current network load - so it doesn't even spawn from your muzzle position.

I've marked this one as 'won't fix' as it's an inherent network lag issue. I'm aware of the hull MG pivot speed and will check them all & adjust as necessary, probably in the next release after 7.0. But I have to close this issue as the original report relates to coaxial MG fire (we can't muddle up multiple issues).
