### ISSUE TITLE
Level design improvement needed(+firefight ballance suggestion): Maupertus

### ISSUE THREAD

**Issue by dynamittt** [DarklightGames/DarkestHour#525]
Hi again. The ladder in Maupertus church is too steep, causing players' vertical speed when climbing the ladder to be ridiculous! Hope this can be fixedby using different style ladder or multi-level storey styled tower with shorter stairs. 

Also, please consider reducing the smoke grenades for the attackers (in this case Allies).
I have played this map multiple times in 6.0, and everytime I palyed for attackers but I feel the defenders get just "crowded" at close range by attackers just charging through endless smoke. All the attack routed get immediately smoke-clogged, giving no opportunities for defenders to use their rifles effectively.
Also, every smoke spot turns into a grenade hotzone, because every one wielding an auto weapon charges into the smoke, being safe from MG and rifle fire, and the opposite team's players who use "low chance of survival" one shot weapons are just spamming nades at the attackers as last resort.
OR may be the map is just too small for 64 players and it needs longer respawn "wait time"?
Map is gorgeous, intense and good for implementing teamplay in close quarters, and I just wish riflemen and MGs could still take their part in the gameplay respectively and fulfil their duties without such struggle.

**Comment by cmbasnett** [comment]
Maupertus is not an official level. Closing this.

**Comment by dynamittt** [comment]
Hello, my mistake, but still can I ask you: is there anything preventing you from making a good level "official"?
Over the years, there have been number of Map Contest packs released for the base game, and most of these levels became official ones, since the devs added them
Problem is that since the update we see almost no custom maps, almost no modders and designers left
