### ISSUE TITLE
Using AdminMenuMutator

### ISSUE THREAD

**Issue by khaun** [DarklightGames/DarkestHour#529]
Hiya

I've enabled the adminMenuMutator following the basic server setup guide from the wiki, changing DH_AdminMenuMutator_WIP to DH_AdminMenuMutator.

But I can't figure out how to open the menu on my client. Do I need to set a hotkey somewhere? any help would be appreciated. Thanks!

**Comment by cmbasnett** [comment]
The issue tracker is used to track tangible issues with the game, it is not a help forum. Please post your question on the Steam community forum. Closing.
