### ISSUE TITLE
Has anyone ran UnCodeX on the source?

### ISSUE THREAD

**Issue by DeadlyDad** [DarklightGames/DarkestHour#531]
- UnCodeX is a combination of a couple of old tools for UnrealScript development: UClasses and UnDox, but it has much more features.
- UnCodeX can create a class and package tree from the UnrealScript sources, analyse the content of each class for later use.
- UnCodeX also gives you the ability to create a high detailed HTML API reference from your code. It includes all definitions made in classes, syntax highlighted source code, links to the type declarations, automatic JavaDoc-like documentation from your source code and much more. 

http://uncodex.ut-files.com/

**Comment by cmbasnett** [comment]
The issue tracker is used to track tangible issues with the game. Closing.
