### ISSUE TITLE
Mortar operator is able to kill himself with own shells

### ISSUE THREAD

**Issue by dynamittt** [DarklightGames/DarkestHour#532]
Hello! I am just playing Stoumont and a guy started dying from his own shells! I asked him a couple of questions, and I even found exactly where he was standing. No walls or buildings close. 
Guy's shell is exploding the moment it leaves the tube (the fire emitter is played of course). He died like this couple of times, and later he killed a bunch of guys (may be 5-6 people) and immediately got kicked for TK. (I have screenshots of this).
During our talks he said to me that he is playing on a Mac, no idea if this could be the issue.
Bug was replicated 2 times in a row (before his shell killed all of these people and he got kicked).

By the way, even if a guy is standing in front of a wall, and the mortar shell hits the wall it should not explode, there should be a protective fuse that prevents this from happening. (needs confirmation though). So if shell flies more that x amount of seconds, only then the shell's ignition cap should be activated. At least this is how modern stuff is supposed to work.

**Comment by cmbasnett** [comment]
Without proper reproduction steps this will be near impossible to fix.

**Comment by AndrewTheel** [comment]
Without a response or similar additional reports, I'm going to close this issue as it is either a random fluke or solved.
