### ISSUE TITLE
"There are too many active mortar targets" when none are marked

### ISSUE THREAD

**Issue by kuopassa** [DarklightGames/DarkestHour#537]
A small nuisance happened in Foy today when I joined and chose Mortar Observer. I couldn't mark targets for the Mortar Operator.

[Here's a clip showing what happened](https://youtu.be/zRRQkT34eO4)

**Comment by cmbasnett** [comment]
This is likely caused by the target slots not being reset when the player leaves or moves to another team.

**Comment by cmbasnett** [comment]
Fixed in commit 462f268e3d9596596a0c1a904551825170f77b81.

**Comment by cmbasnett** [comment]
This wasn't actually fixed before. Don't know how I missed this, but it's now fixed in commit 0db36184d6b39c9ab8c22d31fbe824198d4615dd.
