### ISSUE TITLE
Cannon ammo HUD display is not in the correct order

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#546]
As per the picture below from a 75mm Sherman, it lists the 3rd ammo choice (smoke in this case) above the 2nd ammo choice (HE).

Cycling through the ammo choices works correctly, moving from 1st choice APCBC to HE then to smoke, but that means the HUD ammo indicator goes from 1st in the displayed list to 3rd then back to 2nd.

![image](https://cloud.githubusercontent.com/assets/16405443/14763034/cd8cfea2-0981-11e6-85c4-6428ba05c872.png)

**Comment by cmbasnett** [comment]
What is the intended fix for this?

**Comment by handsm** [comment]
Ammo list order: currently lists primary, then tertiary, then secondary. Just an oddity in the way the drawing logic loops. Easily fixed.

**Comment by handsm** [comment]
Fixed in commit referenced above.

Now displayed logically: primary ammo on top, then secondary, then tertiary.

![image](https://cloud.githubusercontent.com/assets/16405443/14766236/d5126aea-09f9-11e6-895c-5cef91cd2ae7.png)
