### ISSUE TITLE
Players might create "tower of power" in spawn

### ISSUE THREAD

**Issue by kuopassa** [DarklightGames/DarkestHour#549]
Happened in La Monderie when at one of the first spawn points US players were spawning on top of each others. Maybe it was a glitch, or maybe the spawn point is above ground level so player A is spawned in air and he lands on ground, then players B, C etc. are spawned on top of A.

**Comment by AndrewTheel** [comment]
More information is required.  Players can create these towers through a simple technique, it does not require a level bug.  La Monderie has no floating spawn points or nodes, so this leaves me to assume you either were playing a custom version, played with custom mutators, or players were doing this technique to make a tower.
