### ISSUE TITLE
Client mis-reporting location of vehicle, possibly network issue

### ISSUE THREAD

**Issue by clad** [DarklightGames/DarkestHour#554]
I'm encountering an issue when driving vehicles on my client (linux). I'll be traveling in a vehicle (usually with tanks, occasionally with other vehicles), the vehicle will stop immediately, although engine sound continues.  Vehicle is immobile to my client, but still moving and responsive to my controls in game (I can disconnect, reconnect and vehicle will be in its new correct position). Hit detection reports correct position of tank, e.g. I can walk through the visible but immobile position vehicle (and enter), and can get blocked by the invisible but correct position of vehicle.  All vehicle controls work. Only thing that is not working is that for some reason my client will not show the correct position of the vehicle. I can step out of vehicle and usually re-enter it, vehicle will still be immobile. I can also switch seats, let someone else drive, and exit vehicle normally. Also happens when I'm a passenger, but rarely.

I also occasionally experience the turret not being reported correctly, so that turret position and shot are out of sync, i.e. when I fire the shell will go off to the right or left of the crosshair.

I've tried enabling/disabling dynamic net speed, and all rate setting options. My ping is usually under 100ms but I do see a high ping in the 900ms range on occasion (which doesn't align to what's getting reported by my background console ping command). I had a succession of vehicle glitches on GoodGuys Celles map over the weekend, without a high ping being shown (I have not been able to correlate this to packet loss or a network glitch). 

Possibly related, but I've seen similar behavior with vehicles in spawn driven by other players - tank will appear to me as if it is in spawn, frozen in one spot but turning, firing, reversing...but only on my client. 

Reported on steam forum as well, updating info here. It's a long-standing issue, pre-6.0 update. When I first started playing, I thought it was a feature of simulating mechanical failure and bogging.

Thanks for any assistance.

**Comment by dynamittt** [comment]
Please observe carefully stat-net params while experiencing this issue and while having ping spikes. Sounds like you might be losing packets on the way.

**Comment by AndrewTheel** [comment]
This sounds like either a linux issue, a connection issue of some sort, or a individual client issue.  We cannot fix a linux specific issue, that is out of our hands.  A connection issue of some sort is also out of our control.  As for a individual client issue, we may help you fix this, but that is not a bug with the game per say, please post your technical issue on our steam hub and you may get further assistance with other players who have experienced similar problems.  http://steamcommunity.com/app/1280/discussions/3/

**Comment by clad** [comment]
Yep, all signs point to a linux client issue, just fyi, not reopening this. Still occurred after changing isp and hardware. Another linux player has same desync issue, and I cannot reproduce it on windows.

**Comment by AndrewTheel** [comment]
Well damn, that sucks.
