### ISSUE TITLE
Ladders Cause Strange State Preventing Player From Crouching/Proning

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#559]
After climbing a ladder, players cannot prone or crouch and generally feel like something is wrong.  Jumping seems to fix this issue, but this behavior did not exist in previous versions.

Ladders known to be problematic: all in La Cambe, Caen, but I believe all ladders are doing it.

**Comment by handsm** [comment]
Fixed in commit mentioned above.
