### ISSUE TITLE
General Protection Fault (DHHud.PostRender)

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#564]
Build RedOrchestra_Build_[2005-11-27_10.48]

OS: Windows NT 6.1 (Build: 7601)
CPU: GenuineIntel PentiumPro-class processor @ 3506 MHz with 4095MB RAM
Video: NVIDIA GeForce GTX 770 (5306)

General protection fault!

History: UObject::ProcessEvent <- (DHHud DH-Caen.DHHud, Function DH_Engine.DHHud.PostRender) <- FPlayerSceneNode::Render <- UGameEngine::Draw <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- ClientTick <- UGameEngine::Tick <- Level Caen <- UpdateWorld <- MainLoop <- FMallocWindows::Free <- FMallocWindows::Realloc <- 00000013 0 FArray <- FArray::Realloc <- 0*2 <- FMallocWindows::Free

This is a client only crash that seems to be random, but I bet it has a way to repeat consistently.  I was noticing it would often have something to do with the deploy menu, usually entering it, after being dead.  However, do not limit it to my experience as I've only had this crash 2-3 times.  Also this is a long time crash, that would happen in 6.0 as well (not just 7.0).  I may also have seen it in 5.1, but it was very rare.

**Comment by cmbasnett** [comment]
The function specified in the report is very innocuous, I don't think it's possible for anything in the function itself to be creating problems, as this is called literally every frame.

    simulated event PostRender(Canvas Canvas)
    {
        if (DHGRI == none && PlayerOwner != none)
        {
            DHGRI = DHGameReplicationInfo(PlayerOwner.GameReplicationInfo);
        }

        super.PostRender(Canvas);
    }

**Comment by AndrewTheel** [comment]
Next one I get, I'll look at the client log and see if there is more helpful info.

**Comment by AndrewTheel** [comment]
I'm starting to agree, this may just be occurring because we don't have a full bin build on the live version?  If that is the case, In the future it is absolutely important to do a full rebuild before updating.

**Comment by dynamittt** [comment]
Hi, I see you are taking actions against these bugs but I have no clue how are you supposed to track down the actual problem because the GPF log itself isn't specific enough.
I would like to know how you find the exact reason why this is happening because sometimes I am making something and I get the same errors...

**Comment by AndrewTheel** [comment]
Well you are right, it is completely unhelpful.  These crashes are caused by all sorts of strange bugs that exist in unreal script and tracking them down is trial and error.

**Comment by AndrewTheel** [comment]
We should find out soon whether or not we fixed this.  If crashes stop happening, then we know it was with how we were drawing player names, if it keeps happening, then we know it is something else.

**Comment by cmbasnett** [comment]
It will be pretty apparent when we push the patch.

**Comment by AndrewTheel** [comment]
This was fixed in 7.0.2
