### ISSUE TITLE
DH-Vierville map need less invisible walls and smoke for Allies approach.

### ISSUE THREAD

**Issue by zeepster** [DarklightGames/DarkestHour#567]
After parachuting in, Allies have limited means of advancing. It's like a choke point.
Too many invisible walls block most covered approaches for Allies. There we are with great camo, and nowhere to actually sneak up. Like Paratroopers did. Also, no smoke grenades.

We just finished a round here and Allies never got through the first cap. Most of us were talking about these issues during the round.

I'm not saying it's unbalanced, it's just the map messing too much with movement.
Just be less generous with all those invisible walls and let Allies approach more unseen, and less narrow. And give Allies smoke.

I love the idea of the Paratroopers being in the unfavorable position, Germans clearly in the advantage. Awesome. And amazing job mapping. Just get rid of those walls and add smoke.

**Comment by AndrewTheel** [comment]
Should be changed in 7.0.1

Added smokes and moved some walls a bit to allow allies to be a bit more in the bush.
