### ISSUE TITLE
Machine-guns sometimes fire incessantly after round ends

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#57]
Originally reported by: **Colin Basnett (Bitbucket: [cmbasnett](http://bitbucket.org/cmbasnett), GitHub: [cmbasnett](http://github.com/cmbasnett))**

---

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/58

**Comment by AndrewTheel** [comment]
My latest attempt to fix this was to delete all inventory when the round ends, so far I have no clue if it worked.  Has well its hard to replicate the problem.

**Comment by AndrewTheel** [comment]
I haven't noticed this happening in a good while, perhaps something we/I did fixed it.  Gonna close for now, reopen if you notice it.
