### ISSUE TITLE
Problems with Canadian arty observer

### ISSUE THREAD

**Issue by JaKHamer** [DarklightGames/DarkestHour#570]
Testing on the Goodguys server today we noticed on Bridgehead the Canadian arty observer was not functioning. The actor was unable to plot arty strikes. We ended up taking out the Canadian observer and radioman and replaced them with Brit actors.

**Comment by cmbasnett** [comment]
This is almost certainly related to this warning I found in the log:

    Warning: Failed to load 'Class DH_Equipment.DH_USRadioItem': Failed to find object 'Class DH_Equipment.DH_USRadioItem'

**Comment by cmbasnett** [comment]
Fixed in commit d6ccaa696216d8f4d77c359d9591ac61232d6da6.
