### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by magicdutchman** [DarklightGames/DarkestHour#574]
I have noticed a general performance issue when playing the latest issue of Darkest Hour V7.
Keep in mind that I have been playing this great mod almost since the beginning.
I'm talking about the relative lag issues with high ping. Now I know that ping and connection speed affects with the way the players move over the battlefield. But since the latest issue this has become a bigger nuisance then before the update. Truth be told I don't seem to be the only one who has noticed this. I hope this can be fixed in some way or another. Gameplay should come over eye-candy or other additions to the game IMO.

**Comment by cmbasnett** [comment]
Without specific details, there's nothing here that can be investigated. Where (map) does this take place and under what circumstances (lots of players)?

**Comment by magicdutchman** [comment]
This isn't map specific. It might be specific to the amount of players but it's not general lag. Only certain players tend to show lag spikes while walking on the battlefield. The general ping lies around 120 with 40+ players. This kind of anomilies usually happens to players with extravagantly high ping but this doesn't seem to be the case here. I'm just posting this out there. Hope you guys take the time to investigate this. Like I said before, I'm not the only player noticing this.

**Comment by AndrewTheel** [comment]
Though I've noticed this, I've also noticed much much smoother game play (better performance).  It seems to be linked to time of day more than player counts.  I'm going to chalk this up to random connection issues, server issues, or otherwise internet anomalies.  I'll close for now, unless we can recreate this problem consistently.
