### ISSUE TITLE
Misunderstanding of bAllowOpposingForceCapture setting in old-style factories can make vehicles spawn back to front

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#581]
bAllowOpposingForceCapture is an obsolete vehicle factory setting that can cause an unwanted effect. A mapper can assume the setting means the vehicle can be captured by the enemy, which is a fairly logical assumption. So it may be set for soft skinned vehicle like jeeps, kubels or trucks, which previously could be used by both teams. On some maps the mapper still wants that, so tries to enable  it with this.

But it doesn't do that. Instead, some obsolete but still working functionality makes any German vehicle spawn back to front, every time ! It must have originally been intended to allow the factory itself to be captured, in which case the idea was that it would spawn vehicles facing the opposite way, towards the new enemy. Of course this has no place in RO/DH, although oddly the new functionality was added in the ROVehicleFactory class. 

The bAllowOpposingForceCapture  simply needs to be removed to neutralise this unwanted effect. Attached screenshot shows the result:

![backtofrontkubelspawn](https://cloud.githubusercontent.com/assets/16405443/16358069/63f8f0bc-3b00-11e6-83f8-831ced55644a.jpg)

**Comment by cmbasnett** [comment]
What completely ridiculous functionality.

**Comment by handsm** [comment]
Indeed !

Anyway, fixed in commit https://github.com/DarklightGames/DarkestHour/commit/16c5a436098379a695367d359c3bee85a8b725b2.
