### ISSUE TITLE
Server can end up 'jammed' & players can't join a team (related to no map vote at game end)

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#584]
Server can end up jammed, where players cannot join a team, and it will remain that way indefinitely. So this is a bit of a server killer.

Players attempting to join a team receive the screen message "An error occurred when changing teams. Please retry in a few moments or select another team." Unfortunately that is an 'unknown error' message, not indicating a specific cause.

A symptom of the problem is that you can only move the spectator camera for a split second, then it snaps you back to one fixed point.

From Investigating and trying to reproduce, it seems to be caused at round end when no map vote takes place and the server fails to instigate a map change or restart.

Not certain of the exact circumstances, but seems related to the timing of when a single (or last on) player exits the server, in relation to when the end of game map vote comes up. Will update here if get exact timing/repro steps, but it's not too hard to reproduce if you try a few round ends, timing your exit differently. Easiest way on a test server is to use admin menu mutator options to change the remaining round time to 1 minute, then increase game speed so it passes very quickly.

Using the admin option ResetGame (console option as logged in admin, giving the 10 second countdown) appears to un-jam the server, as you can choose a team without error message. But you never spawn and just see a permanent screen message saying "You will deploy as an X in 0.00 seconds".

Switching maps or re-starting the map un-jams the server.

**Comment by handsm** [comment]
Should be fixed in commit https://github.com/DarklightGames/DarkestHour/commit/25371656151b1a5c47b7b32cf220b554c6baff81.

The problem was caused by the 'swap teams and restart map' option. By the time we get to a map vote, the GameInfo class has set its bGameRestarted bool to true. If 'swap & re-start' is chosen, the level doesn't reload and this bool was not being reset to false.

So the server-stopping problem occurred at the end of the NEXT round, because bGameRestarted=true was making the GameInfo think that had already happened. So in state 'MatchOver', the timer did nothing, didn't start a new round/map, and the server just hung there indefinitely. That caused the 'can't join teams, try again later' error.

This critical bug occurred if the 'swap & re-start' option was chosen manually. But would have more commonly occurred on an empty server when the server made a random selection of 'swap & re-start' at the end of a round. At that point the server would be jammed up and no one could play.

Effective fix appears to be simply resetting bGameRestarted to false, in the DHVotingHandler().ExitVoteAndSwap() function.

Note this is perhaps linked to, or a fix for, a 2nd issue https://github.com/DarklightGames/DarkestHour/issues/579 (abnormal vote menu wait after 'swap teams and restart' option).

**Comment by AndrewTheel** [comment]
I was about to suggest it was the Swap Teams and Restart option.  That option was a completely new concept that I kinda just hacked in.  It has actually caused more issues than this, which have been fixed slowly over time.  This should also solve 579 I'm going to assume?
