### ISSUE TITLE
AT Guns Move After Spawning

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#587]
After spawning the AT gun falls a bit, can glitch and angle in odd ways, or otherwise not be unuseful.  Seems to happen randomly, so no repo steps.  The gun can also move on you in odd ways after getting on it.  Mostly affecting AT guns that have objects near them.

https://www.youtube.com/watch?v=U7HcMXWV3mQ

**Solution:**
Make boolean option (to start with) to make the vehicle completely unable to move or be affected by gravity.  The reason to make it a bool, is because there are some AT guns that are setup to fall into position.  It should default to false, and we'll need to one by one look at AT guns in maps and ones that are perfectly set in the editor set to true.

┆Issue is synchronized with this [Trello card](https://trello.com/c/2NL31ppb)

**Comment by cmbasnett** [comment]
Not sure if this is a reasonable solution, vehicle physics don't work the same as other physics in the game. I'm not sure we can override the default behavior of the vehicle physics without causing even more problems. @handsm would know. ;)

**Comment by AndrewTheel** [comment]
I can't imagine another solution.  The AT guns do not need to move, setting their physics to none and not allowing the move tick to do anything should suffice.  But, I agree lets let Matt decide on the best course of action.

**Comment by cmbasnett** [comment]
Another option is to artificially make the guns able to depress the guns *slightly* lower than their historical values (a degree or two). This would likely fix most cases and wouldn't cause any knock-on bugs as a result of fundamentally changing the AT guns' physics.

**Comment by AndrewTheel** [comment]
I don't see that at all a solution to the problem in the video.

**Comment by cmbasnett** [comment]
Sorry, you're right, I thought this was purely about how the guns angle "up" slightly and on some levels it becomes impossible to use it properly because the gun is aiming into the sky.

**Comment by AndrewTheel** [comment]
Actually that could also be solved by having an optional bCannotMove, but it needs to be optional as I originally said as there are many AT guns placed to fall into position.  Part of the problem with those guns being either aimed too high or low is that when the gun spawns it isn't where the editor placed it.  Or moves randomly when a player jumps on it.

I can't just make that AT gun in the video fall onto the ground, because the idea is to use the sandbags to solidify its position.

**Comment by kuopassa** [comment]
Maybe putting AT gun on top of a static mesh sheet and depressing terrain so it's under the mesh could fix it.

**Comment by dynamittt** [comment]
I have experienced the same problem when trying to place a gun on top of uneven terrain, for example if gun is being dug-in terrain.  I think it may have something to do with the gun's origin, but have no clue on how gravity affects vehicles in game. I think Theel's proposition to prevent the gun being affected by gravity/physics or whatever will be a simple and robust solution. Gun must "spawn" wherever the leveler put it and not move at all!

**Comment by cmbasnett** [comment]
Not important for 8.0, removing milestone.

**Comment by handsm** [comment]
Sorry, I've somehow missed this one before. Don't think we can disable physics so it doesn't move. The gun is a new actor, or actually a collection of actors, that spawns in game from the factory. It's a vehicle actor and has karma collision. Would expect all kinds of problems by disabling.

But, I imagine it could probably be solved by revising the collision boxes on affected gun bases to give them a more stable karma collision base. On new guns we've added in game, I put extra collision on the back to give at least 3 point spread ground contacts. I don't think conventional AT guns with split trails have any collision on the trails, so they sit on their wheels or a solid block representing both wheels.

Fairly easy thing to do and can be safely worked on after v8.0 code lock, as it only involves editing collision boxes on the animation mesh and effects are immediately apparent.

ps - I'd like to see the problem shown in the video with the 'show collision' option in single player. The gun looks like it has toppled forward. I notice there are two sandbags right under where the ends of the trails should be resting on/in the ground. Is that gun still in position on that map? If so, what's the map and the grid or a location description?

**Comment by AndrewTheel** [comment]
I'm going to close this issue as its not specific enough, this seems to be a problem with specific AT guns. An issue should be created for each gun in that case.
