### ISSUE TITLE
Vierville spawn camping issues

### ISSUE THREAD

**Issue by magicdutchman** [DarklightGames/DarkestHour#588]
I hope you guys can adress some balance issues in the map Vierville. I just came out of a game that was transformed into a spawncamp fest. The First AA gun/ German side (cap point) could fire directly into the position of the place where the parachutes dropped. Also there is no way to outflank the AA gun because appearantly I'm leaving the map when I try to do that. Either move the spawn point or position the AA gun further back from the place where the parachutes drop. At this point it's ridiculous.

**Comment by cmbasnett** [comment]
I've also witnessed this to be more prevalent an issue since we made the level official. Perhaps the German spawn needs to be moved back considerably?

**Comment by AndrewTheel** [comment]
I already moved it back once.  I think it's a problem with having a poor team that fails to quickly rush the objective.  Letting the objective fill with Axis will create this problem.  However, I will try to balance it one more time.

**Comment by cmbasnett** [comment]
There's an argument to be made that the first capture should be relatively easy to take, both from a historical "element of surprise" angle and a purely fun angle; after a few minutes fighting over what should be an easy cap becomes demoralizing for the attackers and boring for the defenders.

**Comment by AndrewTheel** [comment]
I moved the spawns back and increased the Axis reinforcement timer to 25, so it's a bit higher than Allies.
