### ISSUE TITLE
Springfield sniper rifle fire sound is much quieter than other weapons

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#594]
Not sure if this is a code or asset issue.

┆Issue is synchronized with this [Trello card](https://trello.com/c/EAUVFmJy)

**Comment by cmbasnett** [comment]
Do you mean that the *distant* sound is quieter? Because the up-close sound is pretty damn loud.

**Comment by AndrewTheel** [comment]
Yea it is basically a silencer if you are in the distant sound range

**Comment by AndrewTheel** [comment]
Closing this, I don't think its too bad of an issue.
