### ISSUE TITLE
Can no longer have infantry spawns where players can spawn into infantry vehicles as well as on foot

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#596]
The spawn point system doesn't allow configuration of a SP where infantry can spawn on foot or into infantry vehicles (halftracks, cars, trucks). An 'infantry' spawn now means any role spawning on foot, not into a vehicle. So it is no longer possible to have effective infantry forward spawns ahead of (or just in a different place to) tank crew spawns.

Especially on larger, tank-oriented maps this is an important tactical option. On such maps infantry rarely spawn on foot and usually drive some distance into action. It can be desirable for tanks and other armoured fighting vehicles to spawn further back than the infantry, or at least in a different place. Infantry commonly get into the active cap(s), while tanks often operate further back to provide support and interception of enemy armour. Good map examples are OP-Tractable and Raid to Bastogne.

Separate infantry spawns, with vehicles, are probably beneficial sometimes on different types of map as well. I just give a prominent example on larger, tank-oriented maps, as it's something I'm more familiar with.

I think it's important that the new spawn point functionality needs to do at least what the old spawn areas system did, then build on that, giving additional options and flexibility, but taking nothing away.

**Comment by handsm** [comment]
Have done a simple, light touch implementation; will commit shortly. Suggest needs more fundamental consideration of split between infantry/vehicles and infantry/tank crew - we can discuss when all on at the same time.

**Comment by handsm** [comment]
In the commit mentioned above I have done a simple, light touch implementation, by adding an extra `ESPT_InfantryVehicles` option to spawn point type. This type of spawn allows anything except a tank (or similar armoured fighting vehicle), using the vehicle's bMustBeTankCommander setting. So actually any player can spawn there in an infantry vehicle or on foot, just not into a tank.

I'd suggest this is more of a 'sticking plaster' fix for a more fundamental problem, which is that the distinction between tank crew spawns (or at least spawns where it possible to deploy into a tank) and infantry spawns has become distorted into a distinction between deploying into a vehicle or on foot.

I don't see any benefit in designating a SP as either vehicle or infantry, because the SP already has separate tag names for associated vehicle and infantry (i.e. player start) LocationHint actors.
So we have already told the SP whether or not it can spawn vehicles and/or infantry, by its assigned tags, and we are just repeating ourselves by specifying it as a vehicle or infantry spawn. If we need a bool function like CanSpawnVehicles(), it can give an answer based on whether the SP has a populated                 VehicleLocationHints array.

I suggest a full solution by renaming SP type ESPT_Vehicles to ESPT_Tanks and making it so that SP type can spawn tanks, but should also allow players to spawn on foot so they can form a tank crew (Basnett has already built that option into the existing 'vehicle' SP type and its very valid). The ESPT_Infantry SP type would then allow players to spawn into infantry vehicles only, or on foot. This requires very limited change and I don't think will cause backward compatibility problems. The existing structure of the enum ESpawnPointType is maintained, with value no.1 simply being assigned a different text identifier. Then the code changes are minimal.

We can discuss when all on at the same time; best done with voice I think.

**Comment by AndrewTheel** [comment]
Interesting point about the repeating ourselves with the HintTags and SP type.  

If the SP is either "Infantry/LightMech" or "Tanks" and veh nodes decide if vehicles can actually be spawned.  And inf nodes decide if inf can spawn, then yet we have the same system we currently do.

If infantry SP has no nodes at all, then it should be inf only (no vehicles).

I concur to this change.

**Comment by handsm** [comment]
Just a quick bump to get my own attention!

**Comment by handsm** [comment]
Just a quick bump to get my own attention!

**Comment by handsm** [comment]
Want to finish this properly before 7.2, as never did more than the simple addition of the ESPT_InfantryVehicles option, which was more of a holding thing. I found out afterwards that we can and do have SPs without LocationHints, where players (and potentially vehicles too) fall back to spawning on the SP itself. While I think that isn't great, it is possible and I understand a reality, so we cannot rely on the SP's infantry/vehicle location hint tags to tell us whether it can spawn infantry and/or vehicles. I've added an 'EDIT' note in my earlier outline to reflect this.

@Theel I like your ideas about using the existence (or not) of LocationHints to adjust what the basic spawn point type can spawn. I think that can gives us the extra flexibility I was was looking for, but with even less change to the existing structure. I can delete the ESPT_InfantryVehicles option I added (bit of a stopgap really, very unlikely ever used) and can easily make the ESPT_Infantry spawn point do what I need, using your suggestions, like this:

ESPT_Infantry: Can always spawn on foot even if has no InfantryLocationHintTag (just spawn on SP itself), as now. But extend to allow spawning into infantry vehicles only if the SP has a specified VehicleLocationHintTag. So by default an infantry SP will be purely infantry on foot, as now, but a leveller can easily set up one which also allows spawning into infantry vehicles, simply by adding LocationHints for vehicles. I really like that.

ESPT_Vehicles: If has been used instead of ESPT_All then the leveller must actively want to make it vehicles only. There's no point allowing player's to spawn on foot if the SP has a specified InfantryLocationHintTag, because that would just make it the same as ESPT_All. So basically leave this alone and the only exception to spawning on foot here is the existing one added by @colin.basnett, where tank crewmen can spawn on foot to allow them to form a tank crew and share a tank. I drop the idea of renaming this to ESPT_Tanks. This type of spawn will probably be used for separate tank spawns anyway.

**Comment by handsm** [comment]
Implemented as above in commit https://github.com/DarklightGames/DarkestHour/commit/66ac61e54085b04754ae79f504dcb410a2669e4b.

Deleted the ESPT_InfantryVehicles spawn point type option. Thought I'd end up deleting the CanSpawnInfantryVehicles() function that went with it, but actually it works really well with the change. That function now simply returns:

`return VehicleLocationHints.Length > 0 && Type == ESPT_Infantry;`

In other words it's relevant to an infantry spawn where the leveller has included some vehicle location hints. It checks for a valid VehicleLocationHints array rather than just a specified VehicleLocationHintTag, so it makes sure at least 1 valid LH has been found and registered.

Technically it could also return true if the spawn point type is vehicles or all. But in practice it's only ever checked after these options have first been checked and found false. So it is only ever relevant to an infantry spawn and including the other options would only duplicate checks.

Still includes the same check to make sure the selected vehicle can be used by non-tank crew, so it will only ever allow a player to spawn into a half-track, car or truck.

**Comment by handsm** [comment]
Re-opened as (1) has been glitched in merge between master and squad branch and (2) doesn't work in multiplayer as client never builds VehicleLocationHints array (client doesn't run logic that uses it).

Have fixed and it's pretty simple. Will commit soon when separated out various code work.

**Comment by handsm** [comment]
Fixed bad merge and made previously discussed functionality work in multi-player in commit https://github.com/DarklightGames/DarkestHour/commit/fa4ad95ea769c150ebca7dc593946cb601f7385a.

**Comment by handsm** [comment]
In commit https://github.com/DarklightGames/DarkestHour/commit/3be150b6b249a66e1cfcbbb6e0bae63781a66969 I've added an extra bNoSpawnVehicles mapper option for spawn points, which as the name says will prevent it from being used to spawn into spawn vehicles (MDVs in old language).

This is intended for forward area spawns, which will generally be for infantry and infantry vehicles, where it isn't appropriate to have spawn vehicles so close to the action and so easy to bring up if destroyed. As an example, some of Rekrut's tank-heavy maps made good use of advanced spawns like this, e.g. on OP_Tractable and Raid to Bastogne.

The fundamental problem here is that the old vehicle factory system allowed fine control over the vehicles at each different spawn, where the new DH spawn manager system, although much more efficient and with big advantages, does not allow such control. But there are some options to control, the vehicle pool based on captured/lost objectives, and now there is extra control to have infantry vehicle spawns and to prevent spawn vehicles where required, so we're perhaps about there.
