### ISSUE TITLE
Nasty quadmount bug, screens available.

### ISSUE THREAD

**Issue by dynamittt** [DarklightGames/DarkestHour#603]
This is the first time I use the Qadmount, the map was Targnon.
As I got in I immediately got switched to a "spectatory flying view" over the battlefield, and could not do anything. Switching positions from 1 to 2 just restored the initial Viewrotation. Cannot turn the cannon, cannot shoot while in this bugged state. Got screenshots but can't post right now. Can get in-out without problem. Re-spawning did not fix this.

**Comment by dynamittt** [comment]
http://oi63.tinypic.com/ear2tk.jpg

http://oi65.tinypic.com/30iamok.jpg

**Comment by AndrewTheel** [comment]
I've used and seen used the quad cal many times without incident (on targnon specifically).  Unless you can provide repo steps, I'm gonna say this is a net specific problem and nothing to do with the gun code.
