### ISSUE TITLE
Various specularity overlays for weapons are not being used

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#610]
This affects some 1st person infantry weapons, as well as some vehicle MG HUD overlays:

C96 - specularity overlay exists but not used.
MG42 - exists but not used, even in RO.
PPD40 SMG -  exists but not used, even in RO.
SVT40 sniper rifle - uses the wrong overlay shader: the one for the standard SVT40, not the different sniper version.
Bren - used in infantry weapon but not in HUD overlay used in Bren carrier.
Soviet DT MG - exists but not used in vehicle MG's HUD overlay.

Enfield rifle - uses weapon overlay but not a separate one for the bayonet.
Enfield & Springfield sniper rifles - use weapon overlay but not a separate one for the ammo.
MG34 -  uses weapon overlay but not a separate one for the bipod.

Bazooka - exists for weapon & rocket, but probably never used as doesn't look quite right (shiny areas actually appear as quite white).

**Comment by handsm** [comment]
RO added a HighDetailOverlay system that natively swaps normal diffuse textures for specularity shaders that add shininess to certain parts and make weapons seen in close up (1st person models) look better, using a specularity overlay mask. It only does this if your PC is set to high detail.

The ideal for this system is to use normal diffuse textures (i.e. not specularity) in the animation meshes (or in the default properties Skins array for the weapon class). And then specify the spec shader as the HighDetailOverlay and assign it to the correct Skins index number (almost always 2 for weapon models) in def props.  hat way the non-spec texture gets used when not in high detail, but the native code switches to the spec overlay in high detail. 

Nearly all RO weapons are set up that way, but most DH weapons have the spec shader in the anim mesh. That still works in that the spec shader is used, but it bypasses the HD overlay set up. This is rendered (geddit?) less important by modern graphics cards, but we may as well make sure it is set up for our weapons without errors.

**Comment by handsm** [comment]
Fixed in commits https://github.com/DarklightGames/DarkestHour/commit/617be96cc4b851e65edd80e3311b2e45031cf46a and https://github.com/DarklightGames/DarkestHour/commit/cb1e2ebbc03ab91ce45b06d441ec0651133a0cdb.

**Comment by cmbasnett** [comment]
We'll have to look at all of these in game to make sure they're kosher. I know for a fact the C96 specular map looks like absolute garbage and was omitted purposefully.

**Comment by handsm** [comment]
Yeah, I noticed the unused bazooka one looked iffy. We should at least comment them out with an explanation as to why they aren't used. Others look good though; the RO specs are generally very pukka.

Re the C96, I'm not sure it's the spec map that's wrong, I think it's probably that a spec map simply highlights flaws in the model, which aren't so obvious without it. I'm no modeler and only use Milkshape for basic editing, but when I run its 'model clean' option on the C96 mesh it reports "61 flat triangles removed, 4 orphaned vertices removed & 11 vertex pairs welded". After that the model looks fine with the spec mask applied.

I would simply import the fixed C96 mesh into the editor. Problem is that the 'psk mesh file extracted from the anim file gets corrupted, with part of the player's arms missing. This is using UModel software to extract and I don't know any other way (there's no mesh export option in the editor). If we can find a way to get an uncorrupted .psk mesh out of the editor I can fix this quickly.

An odd thing is if I re-import the extracted, corrupted mesh back into the editor then the bad geometry on the sights (and elsewhere) is fixed, even when viewed with a super-shiny shader. It looks like the bad geometry got stripped away (or smoothed or welded or whatever) in the UModel extract process or the editor re-import.

**Comment by handsm** [comment]
Re C96 mesh problems, note related update and possible fix in https://github.com/DarklightGames/DarkestHour/issues/40.

**Comment by handsm** [comment]
C96 mesh fixed in commit https://github.com/DarklightGames/DarkestHour/commit/ac14477667455d16b11c8eb747e3289bcf34661a.

Applied simple model clean option. Now looks fine, demonstrating that there wasn't anything wrong with the specularity overlay, we just have some bad meshes that need a little clean up.
