### ISSUE TITLE
Coaxial MG reload continues after commander leaves turret

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#621]
A cannon's coaxial machine gun does not have a multi-stage reload like the cannon or a hull-mounted MG (we introduced it for hull MGs in DH v6). So when the coax MG runs out of ammo it starts reloading and continues regardless of whether there is actually a player to do it.

A coaxial reload should pause if there is no longer a player in place & only resume when there is, same as the other vehicle weapons. It should probably also pause if the cannon is reloading, as the player can only do one thing at once and the cannon would take precedence.

**Comment by handsm** [comment]
Fixed/implemented in commit https://github.com/DarklightGames/DarkestHour/commit/fc15a89b00605b90a48385edb1d3f96739dd06f3.

This has been a big millstone around my neck and I'm relived to be rid of it! I first wrote the code, at least on paper, nearly 2 years ago. Never had time to finish and test it prior to the release of v6 and then something always came along near every other release that forced me to shelve it.

Anyway .... coaxial MG now has multi-stage reload process, same as cannon or hull MG, with pause/resume built in. Coax reload will not start/progress if cannon is reloading, or if cannon begins reloading during coax reload. Both can't happen at once and cannon reload takes precedence.

Coax functionality is almost identical to cannon and hull MG reload, but all have been reworked to some degree. VehicleCannon actor has to interweave the cannon and coax reload processes. Made some process improvements to existing reload processes.

Have tested everything I can think off in MP, including manual cannon reloads and autocannons.
Please let me know if you find any issues, but all seems reliable.

Updated the existing LogCannon debug exec to include coax and added a similar LogMG exec for hull MGs.

**Comment by cmbasnett** [comment]
Brilliant. Have always found it bizarre that you could reload both at the same time.
