### ISSUE TITLE
Spawn manager can't handle spawn vehicle ('MDV') and the ordinary version of same vehicle

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#623]
The spawn manager for vehicles still cannot handle the same vehicle class being in the list more than once, e.g. a normal half track and a spawn vehicle version of that half track, which is a common requirement.  When one of those vehicles is destroyed the index can get confused, screwing up the vehicle counts and effectively breaking the map.

This was believed to have been fixed in version 7.1 but it was only a partial fix.  I'm not familiar with this part of the code but from the screenshot below and the resulting problem, it seems the 'front end' was fixed (allowing the same vehicle class to appear twice in the list), but the 'back end' was not (updating the vehicle count when a vehicle is destroyed).

In the screenshot we have a normal M3 half-track and a spawn vehicle M3 half-track. Both worked fine initially and could be selected and spawned into. But we see what happened after the ordinary half-track was destroyed. The spawn manager tried to decrease the count of how many of that type of vehicle was in use, but it incorrectly found the spawn vehicle in the list and decreased that's counter by one.

Because the spawn vehicle counter was zero and the counter is a byte with a value of 0 to 255, decreasing 0 by one looped it back up to 255.  That is a nonsense value and the spawn manager thinks that 255 spawn vehicles are in use, so it won't allow another to be spawned, ever.  Also the normal half-track's counter has not been decreased as it should, so the server thinks that one remains in use even though the vehicle has been destroyed, so again it will not allow the vehicle to re-spawn, ever, as in this map only one is allowed in use. At this point the map is broken.

I expect to fix will be in the spawn manager functionality that happens when a vehicle is destroyed, to update the vehicle count.  The code there will need to distinguish between a vehicle class that has been designated re-spawn vehicle and the same vehicle class that has not.

![spawnvehiclebug](https://cloud.githubusercontent.com/assets/16405443/21293275/5081279c-c517-11e6-83d3-b5b6a18d3221.jpg)

**Comment by handsm** [comment]
Only had a quick look but I think the problem and fix is in DHSpawnManager.VehicleDestroyed() function where it checks:

`if (V.class == VehiclePools[i].VehicleClass)`

Think it needs to be expanded to something like:

`if (V.class == VehiclePools[i].VehicleClass && DHVehicle(V).bIsSpawnVehicle != VehiclePools[i].bIsSpawnVehicle)`

I'll give it a test.

**Comment by cmbasnett** [comment]
Good catch.

**Comment by handsm** [comment]
Thanks. I tested the fix above and it seems to work as expected.

Trawled through for other potential similar problems. Only found the GRI function GetVehiclePoolIndex(VehicleClass). For the same reason, this function in its current form clearly can never work, as vehicle class is not guaranteed to be unique in the list of vehicles. It's only called from DHVehicle function IsFactorysLastVehicle() and will currently fail in this situation, although not catastrophically.

I could simply delete GetVehiclePoolIndex() and do the required logic in DHVehicle, but on balance I think it's better to have a generically accessible function in the GRI and make it work reliably. As the function is only called by a DHVehicle actor, the obvious change is to pass the vehicle actor reference into GetVehiclePoolIndex() instead of passing the vehicle class. Then we can simply check for a match against both that vehicle actors' class and bIsSpawnVehicle setting. Tested that and it also seems to work fine.

The only other function I picked out was DHDeployMenu's GetSelectedVehiclePoolIndex(). It gets a vehicle pool index using GUI functionality. From my memory of looking into the surreal, entangled GRI classes a few months ago (yuk!), I think this will work ok. But Basnett would you mind taking a quick look and confirming that please, just to save me spending time delving into the GUI (you remain afflicted with the GUI curse :) ) @cmbasnett @colin.basnett

**Comment by handsm** [comment]
Fixed in commit https://github.com/DarklightGames/DarkestHour/commit/b110a0dba7c2e53571271be985a8aff9c0a3d1e1.

**Comment by handsm** [comment]
Basnett believes the GetSelectedVehiclePoolIndex() will work ok, as expected, so closing this issue.
