### ISSUE TITLE
Player who is spawn killed is supposed to be able to re-spawn quickly in a vehicle but it does not work

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#629]
The spawn kill protection system is designed so the victim is allowed to re-spawn as quickly as possible, and with no penalty to their team's reinforcements, while the offender is penalised by locking his weapons and reducing his score. But part of this does not work: where the victim is supposed to be able to re-spawn quickly into a vehicle.

This is a bug in the Killed() function in the DarkestHourGame class. The NextVehicleSpawnTime is reduced for the offender, not the victim, so it's back to front. Naming of local variables and use of casting is not very clear, which has probably led to this error.

**Comment by AndrewTheel** [comment]
Yep spot on.  Please clean up as you see fit.  My mistake, but I'll prob just screw it up more.

**Comment by handsm** [comment]
Simple fix in commit https://github.com/DarklightGames/DarkestHour/commit/b6ec0d354fe6a4b405bbec876081b56d6fe2bfff.

Will re-factor for clarity next.

**Comment by handsm** [comment]
Re-opened as changes has been corrupted in merge between master and squad branches and it will no longer work in multiplayer. Just need to add back and delete a coupe of things. Will commit soon, when separated out other code work.
