### ISSUE TITLE
Weapon lock doesn't take effect if offender keeps holding the fire button with an automatic weapon.

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#631]
If a player is weapon locked for spawn killing they get the screen message saying they can't fire, but if they are firing an auto weapon and keep firing the weapon lock has no effect, or at least not until the player stops firing.

Problem is the current weapon lock checks are only in functions that are called when the player wants to start firing. Need to insert something to force player to stop firing when weapon locked, either detected passively in appropriate weapon functionality, or perhaps an active cease fire instruction on player's current weapon when his weapons are locked.

**Comment by AndrewTheel** [comment]
I was aware of this issue when designing the weapon locking system.  It isn't a huge deal, if players aren't aware of it.  Even still, only the 30 cal could fire for long enough to make it harmful enough to require fixing.  Up to you though, if you know a good fix, go for it.

**Comment by handsm** [comment]
Well, any MGs can carry on firing and do lots of spawn killing. Vehicle MGs could be especially harmful. Mainly though, I'm thinking of the weapon behaviour being consistent with the message that the player's weapons are locked, i.e. if the game says they are locked then it's off if they keep firing.

Seems fixed as part of an 'as is' (meaning keeps to existing code structure, for now) re-factor of the weapons lock system in commit https://github.com/DarklightGames/DarkestHour/commit/3eeb27bd726cdabe26e19e49537451570eb51d0d. But I'll maybe add something a little more thorough in later, as part of a more fundamental refactor and extra functionality.

**Comment by handsm** [comment]
Final fix in commit https://github.com/DarklightGames/DarkestHour/commit/4fb28c0cb5700045d585bc84d326a60ce5a101c4.

Actually, simply setting bFire and bAltFire to false on the local machine seem to handle this perfectly. I had a load more complex server & client StopFire/CeaseFire functionality in draft, but this simple intervention does it just as well and a lot shorter and more elegantly.

Moved the bFire stuff out of the message class though and added it to LockWeapons() and AreWeaponsLocked(), as more appropriate and direct there, although does exactly the same thing.

**Comment by handsm** [comment]
For reference, in commit https://github.com/DarklightGames/DarkestHour/commit/cefde2fe6b4ed1c355616bb60a585d93da6c677a I had a re-think and changed the forced 'release' of the fire button from the AreWeaponsLocked() function to the message class. The initial fire button 'release' is done in LockWeapons() and that is to stop automatic fire from continuing - it is highly relevant to have that where it is. But after the initial weapon lock, the forced fire button release is purely to stop the player holding down the button and receiving continuous spammed warning message/sounds. So it is actually very appropriate and direct to have that 2nd release button functionality in the message class.
