### ISSUE TITLE
Suicide, team kill, and spawn kill death messages dissappear too quickly

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#645]
My attempt to fix them wasn't successful so assigning to Basnett.  The code isn't setup to handle messages that arrive earlier than expected and remain for same amount of time as expected.

**Comment by cmbasnett** [comment]
In what commit was this "fix" made? Will help me identify was done wrong more quickly.

**Comment by AndrewTheel** [comment]
```    // If a suicide, team kill, or spawn kill then have the kill message display ASAP
    if ((Killer != none && Killer.Team.TeamIndex == Victim.Team.TeamIndex) || DamageType == class'DHSpawnKillDamageType')
    {
        O.EndOfLife = Level.TimeSeconds + (ObituaryLifeSpan - ObituaryDelayTime);
    }
    else // Otherwise have it wait the delay time (the entire life span)
    {
        O.EndOfLife = Level.TimeSeconds + ObituaryLifeSpan;
    }```

I set the EndofLife lower, which I assume is correct.  The message does display immediately like the comment suggests, but it goes away too quickly.  So I assume the display function logic will need adjusted.

**Comment by cmbasnett** [comment]
Just had a thought, there's probably not anything wrong with your code; I think it is quite possibly a problem with the logic that displays the death messages, perhaps some assumption made that the list has a strict temporal ordering, when in fact it's a bit more wishy-washy.

**Comment by AndrewTheel** [comment]
Fixed in https://github.com/DarklightGames/DarkestHour/commit/b7969a40e9bb1db5348b9585a60ab9bffecff782
