### ISSUE TITLE
Fullscreen Bug (Solved)

### ISSUE THREAD

**Issue by Kongusko** [DarklightGames/DarkestHour#646]
When i put game to fullscrean it will crash

**Comment by AndrewTheel** [comment]
Thanks for reporting a bug, please provide the report it gives you when you crash.

**Comment by Kongusko** [comment]
It does not show me any crash report only Windows tells me ,,RedOrchestraLargeAddressAware.exe" stop working

**Comment by AndrewTheel** [comment]
Well I'm going to assume at some point you've been about to go full screen and changed the full screen resolution to a resolution your monitor doesn't support.  Now when you change the game to be full screen it crashes.  You need to follow this guide here: http://steamcommunity.com/app/1280/discussions/3/351660338707154175/

All monitors should support the default full screen resolution of 1024x768.  Make sure when you change it, you change it to a resolution your monitor supports.

If the fix doesn't help you, we will need more info to help resolve the issue.

**Comment by Kongusko** [comment]
Thanks in 1024x768 it works perfect.

**Comment by AndrewTheel** [comment]
Glad it worked, again find out what resolutions your monitor supports.  You might be able to get a higher res than 1024x768.
