### ISSUE TITLE
Situation map should display spawn points

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#647]
The user should be able to see the location and status of spawn points on the situation map, to better help with situational awareness without having to hit escape and go into the deploy menu proper.

┆Issue is synchronized with this [Trello card](https://trello.com/c/Km8UlNWC)

**Comment by dynamittt** [comment]
Colin hi, I partially agree with this, but if you are going to add this please make the icons smaller than the original ones (from the deploy menu) or user-toggleable. Making them semi-transparent may be?

**Comment by AndrewTheel** [comment]
Yea I'm on the fence about this one too.  Really it doesn't matter, I often just bring up the deploy menu to look at the map these days anyways.

**Comment by cmbasnett** [comment]
Implemented in commit de88e2ae.
