### ISSUE TITLE
DHIntro removal

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#661]
This file seems to be required by the game some how.  It seems to show up on vote lists and causes me frustration.  If someone can figure out how to remove it without the game having errors on start, I'd appreciate it.

┆Issue is synchronized with this [Trello card](https://trello.com/c/IEl0yfwU)

**Comment by dynamittt** [comment]
The 'Intro' and 'Entry' levels should not be visible in the server maplist at all! This is usually caused by poor server set-up.

**Comment by handsm** [comment]
Same as dynamittt - I've never seen DH-Intro listed as an available map to even add to the server's map list, even if I wanted to. I don't see it listed in any of the public server's vote lists. Although I do see it when I start up my own PC as a dedicated server - not certain it was like that before (may have been and I just never noticed it). So would say this is only an issue if the server's map list isn't set up correctly.

**Comment by AndrewTheel** [comment]
I guess its required by native to have an intro map.  No way to fix.
