### ISSUE TITLE
Objectives that use clearing logic are broken

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#667]
It seems that some sort of event logic is not properly firing on these objectives. This is obviously a result of the recent (and unwarranted) changes to the objective code. This is live in v7.2.

![20170222193414_1](https://cloud.githubusercontent.com/assets/5035660/23244719/22ea5ffc-f93c-11e6-86bb-e693bdb8704e.jpg)
![20170222183002_1](https://cloud.githubusercontent.com/assets/5035660/23244720/22fef458-f93c-11e6-8f92-74997f82f592.jpg)
![20170222192534_1](https://cloud.githubusercontent.com/assets/5035660/23244721/23006c48-f93c-11e6-9a85-9264a6e47131.jpg)

┆Issue is synchronized with this [Trello card](https://trello.com/c/grq9p6g5)

**Comment by cmbasnett** [comment]
Found at least one of the problems, and the cause is quite obvious just by looking at the code. Very easy to reproduce.

1. Capture an objective that is set to disable on clear with an enemy still in the cap.
2. Leave the capture area and let the defending team capture the point back.

At this point, the objective will be disabled, blocking it from being recaptured, thus breaking the map.

**Comment by cmbasnett** [comment]
Fixed in commit 17c4b550.

**Comment by AndrewTheel** [comment]
I have fix for this bug, just re-opened so we know it is currently back.  It seems there are 2 bugs here though.  I fixed the simple one where defender is in cap and captures back the objective at which point the obj deactivates.  The other I'm not sure what it even is yet.

**Comment by AndrewTheel** [comment]
Possibly fixed in: https://github.com/DarklightGames/DarkestHour/commit/f81d1ffe7734121a774fcdce1cb0010a50c2cafa

Will keep open as I'm not 100% sure "both" issues are fixed.

**Comment by AndrewTheel** [comment]
It think this was resolved, if it isn't it needs to be reported with reproduction steps.
