### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by chuckwc** [DarklightGames/DarkestHour#668]
Recently, whenever I open DH I get this message:
 Build RedOrchestra_Build_[2005-11-27_10.48]

OS: Windows NT 6.2 (Build: 9200)
CPU: GenuineIntel PentiumPro-class processor @ 3395 MHz with 4095MB RAM
Video: No Video

General protection fault!

History: UWindowsViewport::TryRenderDevice <- UWindowsViewport::OpenWindow <- UGameEngine::Init <- InitEngine <- FMallocWindows::Free <- FMallocWindows::Free

obviously this means I am unable to play the game, and verifying game files or any of the other easy fixes I know do not work. I'd greatly appreciate some help. Thanks

**Comment by cmbasnett** [comment]
It says that there is "No Video", meaning that the engine can't find a GPU to use, which suggests there's a hardware or a device driver issue. Have you tried updating your GPU's drivers?

**Comment by dynamittt** [comment]
Hi, delete User.ini and Game.ini (RedOrchestra.ini for RO, or DarkestHour.ini for DH), run the game and report back.

**Comment by cmbasnett** [comment]
Was this resolved @chuckwc?
