### ISSUE TITLE
DHVoiceChatRoom runaway loop crash

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#672]
Critical: DHVoiceChatRoom DH-Bridgehead.DHVoiceChatRoom (Function UnrealGame.UnrealChatRoom.GetTeam:0001) Runaway loop detected (over 10000000 iterations)

Happened on the Darklight Server, wasn't a full server, but was fairly close.

┆Issue is synchronized with this [Trello card](https://trello.com/c/jRfzU3ue)

**Comment by AndrewTheel** [comment]
This must be what is crashing BH constantly or nearly every time it's played.

**Comment by cmbasnett** [comment]
Haven't seen this in ages, going to close this.
