### ISSUE TITLE
darkest hour crashes since 7.2

### ISSUE THREAD

**Issue by IAMNOOB123** [DarklightGames/DarkestHour#683]
i dont if its an issue with my game or the server but sometimes the game would crash randomly sometimes i can play fine sometimes and sometimes when the map changes a few minutes later the game would crash to desktop.I would then get this error
" Build RedOrchestra_Build_[2005-11-27_10.48]

OS: Windows NT 6.1 (Build: 7600)
CPU: AuthenticAMD Unknown processor @ 2813 MHz with 2047MB RAM
Video: NVIDIA GeForce 210  (3489)

ReadFile failed: Count=0 BufferCount=1024 Error=Data error (cyclic redundancy check).

History: ULinkerLoad::Serialize <- TArray<< <- TArray<< <- TArray<< <- UMeshAnimation::Serialize <- (MeshAnimation 29thCharacter.29thanims) <- LoadObject <- (MeshAnimation 29thCharacter.29thanims 20041728==20041728/29479317 47976 27467702) <- ULinkerLoad::Preload <- PreLoadObjects <- UObject::EndLoad <- UPackageMap::PairToObject <- UPackageMapLevel::SerializeObject <- (Class Core.Object None) <- FInBunch<<UObject <- InitialClientActor <- UActorChannel::ReceivedBunch <- (Actor None) <- UChannel::ReceivedSequencedBunch <- Direct <- UChannel::ReceivedRawBunch <- DispatchDataToChannel <- BunchData <- UNetConnection::ReceivedPacket <- UNetConnection::ReceivedRawPacket <- UTcpNetDriver::TickDispatch <- UpdatePreNet <- ULevel::Tick <- (NetMode=3) <- TickLevel <- UGameEngine::Tick <- Level D-Day 0600hrs - Omaha Beach: Dog Green Sector <- UpdateWorld <- MainLoop <- FMallocWindows::Free <- FMallocWindows::Realloc <- 00000013 0 FArray <- FArray::Realloc <- 0*2 <- FMallocWindows::Free"

**Comment by cmbasnett** [comment]
This could be a problem with your machine. Have a look at [this thread](http://boards.lineage2.com/showthread.php?t=243346).

In short, do a file verification on your Steam files to make sure that all your files are not corrupted. If you do that, and the problem persists, I'd hate to tell you that it might actually be a problem with your hardware. I noticed you have a fairly old GPU, and I'm willing to bet the machine is probably more than 8 years old, it might be a good idea to replace the HDD if the problem persists.

**Comment by IAMNOOB123** [comment]
thanks and yes this potato is really old coz most of my money go to my psychiatric meds will try that thanks
