### ISSUE TITLE
Weird cube in St-Clement

### ISSUE THREAD

**Issue by kuopassa** [DarklightGames/DarkestHour#696]
[As demonstrated here](https://www.youtube.com/watch?v=S_flzan0Wk0). It's close to the middle German spawn area when the round begins.

**Comment by AndrewTheel** [comment]
Sorry to say this is a hardware issue not an issue with the game.  Basically its your GPU is drawing artifacts for some reason.  Try updating your drivers or downgrade, make sure the temp is fine, and if not fixed do some diagnostics on your GPU.
