### ISSUE TITLE
Bow machine guns on US tanks use a fake 'peephole' sight view that did not exist

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#698]
![30calbowmg_falsepeepholeview](https://cloud.githubusercontent.com/assets/16405443/25846373/7d2f1f54-34a9-11e7-8230-25561402f910.jpg)

In game this affects the Shermans and Stuart, but would be common to any US vehicle with a bow MG, e.g. Chaffee light tank. US tanks did not have any sights on their bow MGs and nor did they have a peephole view to aim the MG. Bow MGs were aimed by looking through the co-driver's overhead periscope or while unbuttoned, and then walking the tracers or the bullet impacts onto the target.

Currently in game these MGs use a plain, unmagnified 'peephole' overlay, i.e. a circle of vision in a black background, which is shared by the jagdpanzer IV and now the T34 (changed from RO). Both those vehicles had simple peepholes through which the MG operator sighted and aimed the hull MG. The vision area, i.e. the diameter of the circle, is probably a bit too big and could do with narrowing to better reflect the restricted view firing these weapons. But it is a reasonable representation of the firing view offered by a jagpanzer IV or T34, while in a US tank it is completely unrealistic. On Shermans and Stuarts the view is made worse by using an even bigger view circle.

As we don't have bow MGs with unbuttoned positions, the MG will have to be aimed through the periscope only. I imagine that is how the operator would usually want to do it in real life anyway, as it offers a decent view and you stay safely shut inside.

┆Issue is synchronized with this [Trello card](https://trello.com/c/7qq7oM3y)

**Comment by cmbasnett** [comment]
This will make things a little more difficult to use (as it should!), but I like the idea in princinple. This will make it a little bit dangerous to use because you'll need to fire a few times to know where your gun is aiming, potentially hitting friendlies. In addition, it also won't necessarily be (as) obvious to the gunner that he is able to actually shoot anything since there's no reticle or gunsight to look down. I'll reserve judgement until this is implemented though.

**Comment by handsm** [comment]
Hmmm .... I suppose the difference from real life is that in RL even though the bow gunner on the periscope couldn't see where his MG was pointing, he at least knew the rough direction because he was holding it in his hands. Where in game there'll be no feedback until, as you say, the first burst.

Without over-complicating it with something on the HUD to indicate the direction it's pointing, a reasonable compromise with reality would probably be to move the player's camera position a bit lower down so he can see the 30 cal barrel. Then he'll know roughly where's he's got the gun pointing. I currently have the camera (locally, not committed) positioned exactly on the co-driver's periscope, for the Sherman and Stuart. Wouldn't be quite as realistic, but still certainly a lot better than the entirely fake view we have now.

I'll do the Sherman one way and the Stuart the other, re the camera location, so anyone can easily compare the two.

**Comment by handsm** [comment]
Implemented in commit https://github.com/DarklightGames/DarkestHour/commit/943554765a33580f3739fc39533a3fea2717ce91.

I've done both the Stuart and all the Shermans using a camera position that allows the player to see the tip of the gun, although only when it's elevated.  While firing he'll usually just sees the muzzle flashes in the bottom of his periscope view, which looks plausible (remember his periscope is above and back from the bow MG). But when entering the MG position he can now 'waggle' the gun a bit and will see where it's been left aimed, then swing it broadly onto the target, fire a burst, and walk the tracers or round impacts onto the target.

This avoids the problem Basnett raised, where the player may initially shoot anywhere, even at friendlies. I think this works well as a good compromise between strict reality of the camera position and the need to give the player some visual feedback/cue as to where his gun is pointing before he fires the first burst. The camera offset I've picked works well for the Stuart and all Sherman variants. See what you think.

 This is the note I've included in the file, which explains it pretty well:

> This bow MG did not have a sight or even a peephole to aim through, & was instead aimed using co-driver's overhead periscope. Looking through that view (or while unbuttoned but that's not modeled in game), co-driver had to aim by walking tracers or round impacts onto target.
> 
> Note that the first person camera position (set by FPCamPos) is not quite positioned where the co-driver's overhead periscope is. It's deliberately lowered slightly so the player can just see the MG barrel if he waggles it up. This is a small compromise so the player can check roughly which way his MG is facing before he begins to fire. Otherwise he has to open fire not knowing which way the gun is aimed, & only then can he correct the aim (so he may hit friendlies).
> 
> In real life he would know where the MG was pointing because he would be holding it in his hands
> So this camera adjustment is just an effective form of substitute feedback about where the gun is pointing.
