### ISSUE TITLE
Vehicle pools with bIgnoreMaxTeamVehicles still count towards the MaxTeamVehicles

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#708]
I think this was desired in the concept behind bIgnoreMaxTeamVehicles, but its severely limiting and doesn't work the way it sounds.

Ignore should mean it doesn't check MaxTeamVehicles to spawn and doesn't count towards it either.  Otherwise I have no way of allowing a side to have 1 tank (with multiple types) + other types of vehicles.

**Comment by AndrewTheel** [comment]
Trying to think of a case where changing this would harm other levels.  Honestly not many maps use that bIgnoreMaxTeamVehicles, so perhaps it is clear to go ahead and make the change.

**Comment by cmbasnett** [comment]
Fixed in commit b012e0e54dd11eda307e93fc6e6f4f033026b075.

Please give it a shot and if it works they way you expect, close it off.

**Comment by AndrewTheel** [comment]
Seems to be working.
