### ISSUE TITLE
Players should be able to see supply truck locations on the map

### ISSUE THREAD

**Issue by NathanBLewis** [DarklightGames/DarkestHour#710]
somebody occasionally misplaces the truck and can take forever to find it to build stuff.

**Comment by NathanBLewis** [comment]
another suggestion, more supply trucks per team for every squad to get one

**Comment by cmbasnett** [comment]
This was actually implemented in c9cdc1a8, but there's a small bug with it (shared rotation values for all visible supply trucks) that needs to be fixed, so I'm gonna leave it open until that gets fixed.

**Comment by cmbasnett** [comment]
Bug fixed in 8e4b57a9f03f049da8dd7689dacb853ec6bbc99f. All done!
