### ISSUE TITLE
Incremental vehicle throttle options - if enabled for vehicles but not for tanks, player drives a tank with an incremental throttle but it isn't shown on the HUD

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#712]
The 'incremental throttle' option is a player choice and it means the player can set the throttle to a position and then leave it, with the vehicle then continuing to drive at that throttle setting without holding down a key. If the option is disabled, the vehicle will drive at full throttle as long as the forward key is held down, dropping to zero throttle and slowing rapidly as soon as the forward key is released. This is RO functionality, as is this bug.

The option is enabled or disabled on the game settings screen from the settings menu and the player is given two check box choices: one for 'vehicles' and one for tank throttles. The meaning of enabling it for 'vehicles' is unclear: does it mean it's then enabled for all vehicles, including tanks, or is it only for non-tanks (and tanks then have their own check box)? It is used in two areas of code and those two areas choose to interpret this in contradictory ways:

The actual driving functionality (PlayerController class, state PlayerDriving, function PlayerMove()) treats it that if incremental throttle is enabled for 'vehicles', that means all vehicles and it's irrelevant whether the tank option is enabled or not. So if the vehicles option is enabled, the player always drives a tank or other armoured vehicle with an incremental throttle, regardless of the tank checkbox.

But the vehicle HUD functionality (HUD class, DrawVehicleIcon() function) treats it that the two options are for separate and mutually exclusive types of vehicle, so the 'vehicles' option only affects non-tanks. It only draw a throttle gauge if it considers it enabled for that type of vehicle.

The result is that if a player enables it for vehicles but not for tanks, he ends up driving a tank with an incremental throttle, but with no throttle gauge.

**Comment by handsm** [comment]
PLACEHOLDER - have fixed, will commit today/

**Comment by handsm** [comment]
Fixed in commit https://github.com/DarklightGames/DarkestHour/commit/db008dec075f9914d42f2d8114cccf80f492b619.

I've resolved the contradiction by aligning both areas of functionality to treat the two choices as being for separate types of vehicle, i.e. the 'vehicles' option means non-tanks only.

There's actually a strong and probably stronger argument for the opposite, where 'vehicles' means all vehicles, including tanks. But that way just does not fit logically with the current set up of having two check boxes, because you can end up with the contradictory situation of having it unchecked for tanks on the screen, but still applying to tanks because of the overriding vehicles option being checked. To go that way requires either the tanks option to be greyed out as irrelevant if 'vehicles' is enabled, or better still to replace the check boxes with a pick list of three choices: no vehicles, tanks only, or all vehicles.

But on another note, maybe we ought to remove the option of not having incremental throttles altogether? Usually I'm all for player choice and also for not removing existing functionality, but in this case I struggle to see any advantage in the non-incremental throttle option. To drive vehicles like that doesn't feel in keeping with RO/DH and more like an arcadey game. And anyone who's been a passenger in a vehicle driven by someone with the throttle disabled, always knows it as soon as anyone types a question to the driver and then you wait as it coasts to stop as the driver takes their finger of the forward button to type a reply. Then you usually get killed.

At the very least we should probably change the default setting so that the incremental throttle is enabled for all types of vehicles. At the moment the default is enabled for tanks and other armoured vehicles, but not for other vehicles, which is hard to make sense of, in my opinion.

Leaving this open for a bit as (1) I'm probably going to clarify the option meanings on the config screen, and (2) for any discussion and changes from the points I raised above re getting rid of the non-incremental throttle.

**Comment by handsm** [comment]
Clarified the wording for the throttle options on the config screen in commit https://github.com/DarklightGames/DarkestHour/commit/b53863e4cfebd10e1a8774d90a45215fd1815cc2.

**Comment by cmbasnett** [comment]
Just getting to this now, but yes I agree that the incremental throttle should be enabled for all tracked vehicles, at the very least. There really shouldn't be an option to enable/disable here because having it non-incremental requires more micromanaging of the controls and is altogether sloppier and clunkier than the alternative.

I'm am, however, in favor of having non-incremental throttle for small vehicles like the Jeep and Kubelwagen, if only for the reason that this is how we, and probably the vast majority of players, have come to use the controls.

**Comment by handsm** [comment]
Incremental throttle is already enabled by default for tanks, meaning any DHArmoredVehicle class, and has been since RO. You're suggesting extending that to all tracked vehicles? If so, that would change the distinction from tanks/other vehicles to tracked/fully wheeled vehicles, which could easily be determined by the existing bHasTreads bool in the DHVehicle class. Requires some minor changes in the game options screen to match.

Although I suggested removing the option to not use the incremental throttle, I'd say it's probably all or nothing, i.e. either no option or existing options for both  vehicle types. So if we don't remove it completely, I wouldn't remove the option only for tanks or tracked vehicles (however we make the option distinction), leaving it only for wheeled vehicles. If a non-throttle options is going to remain, I'd say let players continue to choose for any vehicle type

**Comment by AndrewTheel** [comment]
Yes closing as original report is resolved.

We can open a new issue about having a single user options which will turn on/off throttle for all bHasTreads vehicles, not just armored tanks.
