### ISSUE TITLE
Removal of Weapons lock and implementing safe spawn zones

### ISSUE THREAD

**Issue by NathanBLewis** [DarklightGames/DarkestHour#717]
Weapons lock is not very effective at preventing spawn killing and it also happens even when killing enemies on the frontlines, foy, stoumont, and maupertus being great examples.

A better method would be to turn every spawn into a safe zone, with a radius that grants invincibility indefinitely or on a timer of 1 minute. 

Once the player steps out of this small zone, they are vulnerable. Returning back to the safe zone WILL NOT revert the player back to being invincible.

**Comment by AndrewTheel** [comment]
Good suggestion, but the radius in question creates issues on some maps.  For instance, on Foy too far a radius will result in how Foy used to be with immortal enemies running out in the open.  Too short of a range and its basically not even spawn protection.  

You say the current system is not very effective at preventing spawn killing, but actually from my experience it does the trick.  The entire point of the current system though is to prevent a situation where you are shooting an enemy countless times and they don't die.  Its really annoying to shoot someone in greater than lethal ways and them not die.  

The current spawn protection system is nearly obsolete anyways.  In Advance nearly every spawn is considered a combat spawn.  The main spawn in Advance acts the exact way you mention, but its actually longer than 1 min.

As for changing the Push spawn protection system, we are actually happy with how it is.  It allows for you to kill enemies that just spawned, but little to no punishment for the victim and eventually punishing you.  I agree its not perfect, it sorta forces levelers to setup the Push spawns to be a bit further away, but I think that is how it should be.  If spawn camping keeps being a significant reoccurring thing we can adjust the weapon lock punishments.  We toned it down greatly in the 7.2? update so the live version doesn't punish as strictly as it once did.  We can turn it back up a bit though if its determined it is needed.  What do you think?

**Comment by AndrewTheel** [comment]
I went ahead and increased the weapon lock times a bit in this commit: https://github.com/DarklightGames/DarkestHour/commit/f332311db06892b181f885e62228b9fc9866e5c6

Closing this now.
