### ISSUE TITLE
Drop supply crates so the truck can be freed up

### ISSUE THREAD

**Issue by NathanBLewis** [DarklightGames/DarkestHour#718]
I think pr has the system nailed pretty well, I guess squad does too, never played that though. Dropping supply crates will let the truck get the hell out of dodge and restock quicker, leader to better fortifications.

The driver of the truck could be rewarded 1 point or 2 points per crate dropped to encourage to help team out as logistics, even form a logistics squad dedicated to that.

**Comment by cmbasnett** [comment]
We already have this actually, but it requires that the team "builds" a supply cache to drop the supplies at. Admittedly it's a bit much to handle, and a simpler "drop and go" feel might be better.

**Comment by AndrewTheel** [comment]
Where would it drop though, what if the player wanted it in a specific spot?

**Comment by AndrewTheel** [comment]
Closing this.
