### ISSUE TITLE
Some obstacles need to be crush-able and perhaps we should make it mass based

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#720]
A perfect candidate for being crush-able is the wooden barbed wire obstacle.  Which shouldn't be crushed by jeeps/kubels, but should be crush-able by 2.5 ton trucks and other larger vehicle/tanks.

**Comment by cmbasnett** [comment]
Implemented in c0edc910994883373d38f87c244857d523916227.

You can now ram some constructions with vehicles to do damage to them and ultimate destroy them.
