### ISSUE TITLE
Turn the health up on some obstacles to make them less prone to tank HE

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#721]
Mostly the hedgehog should not be very easily destroyed to HE.  Even sandbags seem too easily destroyed and go fly up in the air when the HE lands 10m away.  This will make infantry more important to remove obstacles and cover and makes tanks less effective (which they are very effective already).

**Comment by cmbasnett** [comment]
Implemented in commit b0001b36a4a1b742fbcbe7dc12dde5c7a2de4dac.
