### ISSUE TITLE
Constructions pop into view too late

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#723]
Many obstacles, even ones that provide cover, pop into view too late.  Sandbags may end up being really annoying and confusing, when players hiding behind them begin taking fire asking, "How did he know I was behind this sandbag???"

**Comment by cmbasnett** [comment]
This is still a problem, we may have to force `bAlwaysRelevant` on certain constructions (namely those that are large and/or provide cover).

**Comment by cmbasnett** [comment]
This could actually be somewhat related to https://github.com/DarklightGames/DarkestHour/issues/775.

**Comment by cmbasnett** [comment]
Fixed in commit 4323df4512de78dc044176991597f4187c649fa9.

Constructions are now always relevant.
