### ISSUE TITLE
Platoon HQs should be harder to capture

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#725]
The rules on default HQs should be like so:
1 enemy...
1) In the block radius does not block
2) In the capture radius blocks
3) Cannot capture a platoon HQ

3 enemies...
1) In the block radius will block
2) In the capture radius captures
3) Can capture a platoon HQ

**Comment by cmbasnett** [comment]
Implemented in commit 4e9b9159b499b43e035ea9065eeaede2eb5c7514.
