### ISSUE TITLE
Pavlovs House-Cutoff Map Idea for 8.0

### ISSUE THREAD

**Issue by NathanBLewis** [DarklightGames/DarkestHour#732]
"Pavlov's House was a fortified apartment building in which Red Army defenders held for 60 days against a heavy Wehrmacht offensive during the Battle of Stalingrad."

This would be a genius map idea for the cutoff game mode. A limited Russian team defends the apartment against a larger german team. 

https://en.wikipedia.org/wiki/Pavlov%27s_House#/media/File:Pavlov%27s_House.jpg

**Comment by AndrewTheel** [comment]
There is a Pavlov's House map for RO, its pretty rough, vehicles get stuck constantly and it has some pretty bad lighting.  Want to clean it up and give it a shot?

**Comment by NathanBLewis** [comment]
download link?

**Comment by AndrewTheel** [comment]
http://www.red.orchestra.pl/archiwum/plug.php?e=maps&mtype=sch&sch=RO-Pav&x=GUEST
