### ISSUE TITLE
M1A1 Thompson has incorrectly textured geometry on stock

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#74]
Originally reported by: **Colin Basnett (Bitbucket: [cmbasnett](http://bitbucket.org/cmbasnett), GitHub: [cmbasnett](http://github.com/cmbasnett))**

---

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/75

**Comment by handsm** [comment]
Re-opened as still an issue. Looked at the mesh and there are extra triangles laid over that corner of the wooden stock, with effectively random UV mapping that appears black. It's pretty simple to delete those excess triangles and the wood underneath is revealed.

However - the 'psk mesh file extracted from the anim file gets corrupted, with part of the player's arms missing. This is using UModel software to extract and I don't know any other way (there's no mesh export option in the editor). If we can find a way to get an uncorrupted .psk mesh out of the editor I can fix this quickly.

**Comment by handsm** [comment]
See related update & possible fix on https://github.com/DarklightGames/DarkestHour/issues/40.

**Comment by handsm** [comment]
Now we have been able to extract an uncorrupted mesh, I have fixed this issue in commit https://github.com/DarklightGames/DarkestHour/commit/6575d3337cd3f834cca6dd3a94505a1b67833aad.
