### ISSUE TITLE
Squad leader needs to be visually distinct from other squad members

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#753]
Locating and identifying the squad leader is very important, but the menu makes it a bit of a rough task. Two things need to be done (at the very least).

1. Squad leader "player marker" on the situation map needs to be larger and/or a slightly different color (keep consistent with other colors!)
2. Squad leader's HUD name (when looking at him) should have a fancy "squad leader" icon, as well as a slightly different color (keeping consistent with the player marker color et al.)

**Comment by ReichsFuhrerSS** [comment]
Cool

**Comment by cmbasnett** [comment]
Implemented in commit d0e60d92787e436ccfe97dbe533f2d202b519002.

![image](https://user-images.githubusercontent.com/5035660/30244359-43324294-9571-11e7-8f53-49ab2860e33f.png)
