### ISSUE TITLE
"Capture and clear" rules and mechanics are not conveyed to the user in any way

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#757]
The "capture and clear" mechanics have never actually been conveyed to players through the game's interface. In order to learn how it works you basically just have to be told via text or over the microphone and infer how it's supposed to work.

To a regular user, the system makes no sense. This is what happens from the user's perspective, in all likelihood:

1. Objective is captured, but there are still enemies in it (unbeknownst to the user).
2. User sees notification (text and sound) that the objective is captured (hooray!)
3. User checks the map to see what the next objective is, only to find that the only currently active objective is the one they just captured.
4. Confusion ensues, questions start racing through our poor user's mind such as: "What do I do?", "Are we defending now?" and "Is the game bugged?"

This is terrible conveyance of the systems and a solution needs to be found.

**Comment by AndrewTheel** [comment]
Yea even I fall into this, "wait is it bugged?" example.  We need a sound and indication when the objective is cleared.  In addition, if the objective is cleared on capture it should indicate both in the same indication and use the clear sound instead of the capture sound.

This is my world, so I'll do the work on it, but what else can we do to improve how intuitive it is?

**Comment by cmbasnett** [comment]
I would say a few things need to happen regarding the immediate UI (sitmap and capture bar)

1. We need to show the "flashing" icon on the map if it's still waiting to be cleared.
2. Indicate *on* or around the capture bar (maybe re-purpose the old "ratio" box?) that an enemy is inside the capture. We don't need to show how many there are, just that there *are* people. Perhaps have this _flashing_ to draw attention to it.
3. Perhaps have the words "(Not Clear)" or "(Not Secured)" or something similar be literally on the screen on/around the capture bar.

The last one is a bit heavy-handed, but all three in concert should eliminate _all_ confusion as to what is going on.

In terms of notifications. We should change how it works slightly:

If the cap needs to be cleared and the objective is "captured" but not yet clear, display a notification that the objective was "captured", with a slightly less bombastic sound. When the objective is fully secured, display another notification with the usual drum-roll sound and message. The sound alone should be different enough so that more experienced users will be able to pick up on what's going on without actually having to read anything at all.

**Comment by AndrewTheel** [comment]
Okay will work on the sound first as I think that is priority.  Then look into the capture bar and notifications.

**Comment by AndrewTheel** [comment]
1, 2, and 3 should be completed in the above commit.

Okay now all that is left is to obtain the sounds.

**Comment by cmbasnett** [comment]
Taking myself off this one since this is all yours now @AndrewTheel

**Comment by AndrewTheel** [comment]
I think this is done, the sounds are fine, perhaps will need to be tweaked later at some point, but they are worthy of release now I think.
