### ISSUE TITLE
Players can hop squads too easily

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#763]
Players are able to hop between squads without any delays, allowing them to cherry-pick the squad with the best spawn points and then hop squads immediately after. A solution needs to be found for this that involves some sort of time delay for squad swapping.

**Comment by cmbasnett** [comment]
Actually I'm going to sideline this for 8.0, since the interface sort of throttles the user from doing this. If it becomes a large problem in public play then it can be revisited.

**Comment by AndrewTheel** [comment]
Not really a big issue, closing.
