### ISSUE TITLE
Constructions can pop in and out due to out-of-sync bounding boxes

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#775]
This is a very annoying bug. Many constructions can appear to pop in and out of view depending on how you're looking at them with no real obvious reason.

# Cause
After much humming and hawing, we found that the reason is the first time the actor becomes relevant on your machine, it is added to the game's internal scene graph with the current bounding boxes that are use for view frustum (camera) culling. When a construction gets built up, the construction will generally change (to be larger), but the underlying bounding box in the scene graph is not updated at all.

There doesn't appear to be any code-only options here, but here are some relevant bits in `Actor` just for the curious:

    var const transient Box   OctreeBox;     // Actor bounding box cached when added to Octree. Internal use only.

As far as I know there is no way to get this value updated after it's already been added to the world.

# Solutions
The sure-fire way to re-update the bounding box would be to delete the actor on the client and then place it down again. However this is expensive and not exactly an elegant solution.

The other solution is equally cheesy, but 100% foolproof and doesn't require and code magic at all. For the static meshes of each stage of the construction, we ensure that there is *invisible* geometry that extends to at least the largest size the constructions can get:

![image](https://user-images.githubusercontent.com/5035660/29244956-ab07d1b8-7f7d-11e7-8b3e-423b08a2dd3d.png)

> The black box around the construction is geometry with a completely transparent texture and no collision.

This adds a bunch of annoying work, but it will also fix the bug completely.

- [x] Concertina Wire
- [x] Hedgehog
- [x] Sandbags (Line)
- [x] Sandbags (Crescent)

**Comment by AndrewTheel** [comment]
Question: Do I only need to do the first stage of the construction, or also the middle one?

**Comment by cmbasnett** [comment]
You'll need to do all of the intermediate stages, since it can be replicated at basically at any time. Luckily a lot of the intermediate stages are shared (especially for the sandbags).

**Comment by AndrewTheel** [comment]
Hmmm why aren't Platoon HQs on this checklist?

**Comment by cmbasnett** [comment]
The problems aren't really noticeable on that one since the "unpacked" version takes up roughly the same footprint as the others. If you wanna be thorough, this could be done as well but TMK it's never really been an issue for the HQs.
