### ISSUE TITLE
Cromwell tank has various geometry issues

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#78]
Originally reported by: **Colin Basnett (Bitbucket: [cmbasnett](http://bitbucket.org/cmbasnett), GitHub: [cmbasnett](http://github.com/cmbasnett))**

----------------------------------------

----------------------------------------
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/79

**Comment by handsm** [comment]
For the record, I subsequently fixed the sunken turret with a code fix, using new CannonAttachmentOffset variable, and I also added the driver's view improvement.

Mesh geometry bugs still need fixing.

**Comment by handsm** [comment]
All mesh geometry bugs fixed as part of substantial model re-work committed in SVN update no.1161.

See https://github.com/DarklightGames/DarkestHour/issues/530 for more details (duplication between these 2 issues, but all resolved).
