### ISSUE TITLE
Supply cache construction needs new meshes

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#786]
We need a unique static mesh set for the "Supply Cache" construction. This is a construction that simply holds construction supplies.

It needs to have a couple of characteristics:

1. Able to fit neatly into the back of a GMC and Opel truck.
2. Has at least 2 "stages" (full & not-so-full)
3. Able to be easily re-skinned for different nations (Germany, USA, USSR, Commonwealth)
4. Has a square "footprint".

Here are some reference shots:

![](http://www.valuegeardetails.com/images/OB2A-1000FULL.jpg)

![](https://i.pinimg.com/originals/b5/78/ec/b578ecb7b3d1e74ff64522fd02f52a34.jpg)

![](http://www.valuegeardetails.com/images/UT1A-1000FULL.jpg)

![](http://www.valuegeardetails.com/images/OB1A-1000FULL.jpg)

**Comment by cmbasnett** [comment]
This is a note for myself, the Opel Blitz has an incorrectly rotated supply attachment bone; this will need to be manually fixed in code.

![20170826210528_1](https://user-images.githubusercontent.com/5035660/29747078-8b53fcb8-8aa2-11e7-8e01-00a4163fb48a.jpg)

**Comment by AndrewTheel** [comment]
Marking this complete as TMK this looks completed.

**Comment by AndrewTheel** [comment]
Oh, so Basnett informed me that we were supposed to have an intermediate mesh to show less supplies.  But I actually don't see a point in that, especially if we just display the supply value above the thing.

**Comment by AndrewTheel** [comment]
Closing this as it is done.
