### ISSUE TITLE
Supply count needs to be displayed in a more aesthetically pleasing way

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#788]
Currently, for debug, we are just drawing (in very tiny text at the top of the screen) the supply count. We need to display it in a more appealing way, perhaps borrowing from the new style of the objective capture bar.

**Comment by AndrewTheel** [comment]
@cmbasnett is there an issue regarding displaying supplies via the floating above head text for supplies?
So we can know how much supply is in various things nearby?

Obviously I think this issue should be extended to cover that as well.

**Comment by cmbasnett** [comment]
Imlemented in commit b16b5fb.
