### ISSUE TITLE
RocketWeapons reload animations stutter (fix included).

### ISSUE THREAD

**Issue by dynamittt** [DarklightGames/DarkestHour#790]
@cmbasnett @AndrewTheel @handsm

- [ ] approve
- [ ] import 

Hello. There is a problem with the reload animations for the rocket weapons.
There is a nasty jerky/'skip/stuttery' movement around frame 145, when the right arm reaches down to pocket/pouch/whatever, in order to take projectile...
I have actually had this fixed last year, but I forgot about it until I found it while looking for something else.
Here is the anim sequence, I have included the animations mentioned above and the old ones to compare.
https://yadi.sk/d/H3_tN7YC3MQDDY
Edit: I found problems in some other animations too, so may be they should be fixed first...

**Comment by cmbasnett** [comment]
@dynamittt We'd prefer if this was submitted as a [pull request](https://help.github.com/articles/about-pull-requests/). This would allow us to preview the changes and essentially just hit a button and it would be integrated into the master branch. If you need help doing this just let us know. Once you master the pull request, integrating your fixes will be a snap.
