### ISSUE TITLE
Foxholes have problems on maps with larger terrain scales

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#791]
These screenshots were taken on Putot en Bessin and they demonstrate the problem pretty clearly. If we want to have the foxholes work on maps with this terrain scale, we will need a mesh that extends further out and down below the terrain.

![20170827022920_1](https://user-images.githubusercontent.com/5035660/29808635-c4aab28e-8c4d-11e7-87c9-8d89a9666696.jpg)
![20170827022936_1](https://user-images.githubusercontent.com/5035660/29808633-c4a964ec-8c4d-11e7-98b2-157df827ea88.jpg)
![20170827022942_1](https://user-images.githubusercontent.com/5035660/29808634-c4aa52b2-8c4d-11e7-8a98-b3d9d3af8cf0.jpg)

**Comment by cmbasnett** [comment]
This is all on @AndrewTheel now!

**Comment by AndrewTheel** [comment]
I asked @piotrlukasik86 for help on this, as I can't seem to open the max file without errors

**Comment by AndrewTheel** [comment]
Added Basnett to this as once there is another foxhole version, the code will need to use the proper foxhole depending on the terrain scale. I'll leave myself assigned as I may help test and make sure this gets done.

**Comment by cmbasnett** [comment]
This was completed in a series of commits (a133c4cc, 41f00467, 578124ec, 6bbef018, 383fcb58).
