### ISSUE TITLE
Spawn kill "protection" time is too short

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#802]
I was killed after spawning on a RP, took about 2 steps forward and was killed, didn't count as spawn kill.

**Comment by cmbasnett** [comment]
Hmm, did you fire your gun? I think it removes your spawn protection if you fire.

**Comment by AndrewTheel** [comment]
Nope. didn't fire

**Comment by AndrewTheel** [comment]
Should be fixed in https://github.com/DarklightGames/DarkestHour/commit/f0c6a7199e2771c2f2641a461f09060200216060
