### ISSUE TITLE
Spectator mode is broken in a number of ways

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#803]
There's a whole bunch of problems with the spectator mode, it behaves without any real rhyme or reason. Sometimes the screen is completely black even though spectator mode is allowed, other times it won't let you cycle through players. This should be sorted out if the Cutoff mode is released into 8.0, otherwise it can be kicked down the road.

**Comment by cmbasnett** [comment]
Well, I found the culprit, sort of. This isn't actually *broken*, but it's a mix of terrible conveyance, clunky controls, and not giving the user a sensible default.

There's a block of logic in `DarkestHourGame` that concerns the forcible setting of various server-side spectator variables that govern the player's ability to roam around and not have their screens blacked out. This is all fine, but the user is never told about what these restrictions are, and the user can be cycling between multiple different views (with the clunky controls) that don't even allow the user to see anything in the first place.

There's a few things we can do to mitigate this:

1. Don't start the user in a spectate mode that blacks out their screen.
2. Don't allow the user to switch to a spectate mode that blacks out their screen.
3. If spectating of any kind of prohibited, show a message on the screen so the user's not wondering why the game is broken!

**Comment by cmbasnett** [comment]
After more investigation it does look there is actually a logic bug here (in addition to some of the other problems inherent in the spectator mode). There's this block of code here:

    if (bPublicPlay)
    {
        NewPlayer.bLockedBehindView = true;
        NewPlayer.bFirstPersonSpectateOnly = true;
        NewPlayer.bAllowRoamWhileSpectating = true;
        NewPlayer.bViewBlackWhenDead = false;
        NewPlayer.bViewBlackOnDeadNotViewingPlayers = true;
        NewPlayer.bAllowRoamWhileDeadSpectating = false;
    }
    else
    {
        NewPlayer.bLockedBehindView = bSpectateLockedBehindView;
        NewPlayer.bFirstPersonSpectateOnly = bSpectateFirstPersonOnly;
        NewPlayer.bAllowRoamWhileSpectating = bSpectateAllowRoaming;
        NewPlayer.bViewBlackWhenDead = bSpectateBlackoutWhenDead;
        NewPlayer.bViewBlackOnDeadNotViewingPlayers = bSpectateBlackoutWhenNotViewingPlayers;
        NewPlayer.bAllowRoamWhileDeadSpectating = bSpectateAllowDeadRoaming;
    }

This looks fine, but it becomes apparent what the problem is when you look at `GetNextValidSpecMode` in `ROPlayer`. It is using the *game's* version of these settings to determine the next view mode, but in the above code you're going and setting the player controller's settings. This results in a desync between the two sets of settings. This is the reason why it allows you to switch to spectator modes where you can't see anything.

**Comment by AndrewTheel** [comment]
But that really isn't the bug that we have.  The bug we have is you can't spectate everyone alive on your team.  Sometimes it just stops looping players and you can't spectate at all, then suddenly it seems to work again, but often just never works once you are "bugged"

**Comment by cmbasnett** [comment]
Well yea, like I said there's a *lot* of problems, this is just one of them.

**Comment by cmbasnett** [comment]
One of the problems with the spectator mode instructions is that the actual button you're supposed to press isn't prompted, just the "action". For example:

    SpectateInstructionText2="Press Alt-Fire to switch Spectating Modes"

The user then has to go "okay now what is my alt-fire button?" An small improvement would be to just display the name of the actual button.

**Comment by cmbasnett** [comment]
One of the problems with the spectator mode instructions is that the actual button you're supposed to press isn't prompted, just the "action". For example:

    SpectateInstructionText2="Press Alt-Fire to switch Spectating Modes"

The user then has to go "okay now what is my alt-fire button?"

An small improvement has been added in commit 76b83b5 to just display the name of the actual button (eg. MOUSE1, SPACE etc.)

**Comment by cmbasnett** [comment]
Another thing that need to be done is removing irrelevant control hints when in certain modes (for example, when in roaming mode, it prompts you to click to cycle through viewpoints, which is impossible).

**Comment by cmbasnett** [comment]
Another bug discovered: the game allows you to cycle spectating controllers that don't have pawns, leaving you with a black screen until you cycle to a controller that does have a pawn. I have a fix, but just writing it down so I don't forget all the crap that was broken.

**Comment by cmbasnett** [comment]
Fixed in commit dc3d8ac9c4f38f69927613c1bd970f7ed98ac42a.

Many changes, fixes and improvements to the spectator system:

To summarize, the spectator system has been a mostly unusable mess for a long time, staying virtually untouched since Red Orchestra. The following changes fix a number of objective bugs as well as improving the behaviour and usability of the system.

## Prompts
The spectator interface would display input prompts that had no function or contextual relevance.

* The prompt and ability to press `%JUMP%` to move directly to the "Self" spectating mode has been removed, as 99.9% of the time it was completely pointless and resulted in nonsensical behaviour.
* The prompt to press `%ALTFIRE%` to switch spectating modes is no longer displayed if there are no other valid spectating modes to switch to.
* The prompt to press `%ROIRONSIGHTS%` to switch between first and third person view modes is no longer displayed if the spectator is not in the "Players" spectating mode or third-person spectating is disabled.
* The prompt to press `%FIRE%` to swap between viewpoints/players is no longer displayed if the user is not in either "Viewpoints" or "Players" modes.

## Changes

* The "Self" spectating mode has been made un-selectable unless the player has an actual "self" pawn to view, which is only really the case immediately after dying.
* Spectator modes that are going to be "blacked out" when viewed are now considered "invalid" and won't be switched to when cycling through spectator modes.
* The spectator interface is not shown until the user is *actually* spectating (it would previously show when viewing your death from first person, and would erroneously say things like "Viewing Viewpoints" because the user hadn't been properly put into the spectating state).
* If you are put into a mode that is blacked out, the words `(BLACKOUT)` will appear below the name of the mode. This will help to let the user know that the game isn't bugged, but that it's indeed intended behaviour.
* Player names are now correctly colourized when spectating players in the first-person.
* Removed the `bPublicPlay` variable as it was an ineffectual way of enforcing consistent spectator rules.

## Bug Fixes
* Fixed a bug where spectators in the "Players" mode could cycle through player controllers that didn't have pawns, resulting in black screens and confusion.
