### ISSUE TITLE
Mysterious raptor actor is visible at the center of the map

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#806]
The raptor returns! Not sure which actor this is, but we gotta kill it with fire!

**Comment by AndrewTheel** [comment]
Did you find a way to get this to show up?

**Comment by AndrewTheel** [comment]
Could it be a `DHResupplyPoint` ?

Could it be a `DHArtillerySpawner` ?

**Comment by dynamittt** [comment]
Just an idea....
Could it be a Dynamic Actor that gets spawned without proper coords, so it's location is set to be (0,0,0), hence it appears in the 'middle' of the map?

**Comment by AndrewTheel** [comment]
Yep, the idea is to figure out which actor.

**Comment by cmbasnett** [comment]
Okay, there's a new `DebugRaptor` exec function that anyone can run. It will spit out the name of any non-hidden, sprite-rendered actor that's at world origin. We were unable to reproduce this at the current build snapshot, so we're gonna call it fixed. Can be re-opened if it pops up again.
