### ISSUE TITLE
Players can resupply teammates with captured anti-tank rockets

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#81]
Originally reported by: **Andrew Theel (Bitbucket: [AndrewTheel](http://bitbucket.org/AndrewTheel), GitHub: [AndrewTheel](http://github.com/AndrewTheel))**

---

Should not be able to resupply enemy AT weapons that have been captured.  

Currently you can pick up a Bazooka as an Axis and be resupplied by both resupply zones and friendlies. 

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/82

**Comment by AndrewTheel** [comment]
Reopening as this should be fixed ASAP imo.
