### ISSUE TITLE
Phase 1 Logistics Changes (Solution for ineffectual supply caches)

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#820]
**Problem:**
Currently there is little purpose for the supply cache, unless you plan on leaving with the truck right away. IMO, the only reason I see to use the cache is as a SAFER storage of supplies than the truck. The truck can be killed with small arms, but the cache must be shoveled (close quarters). But overall, the supply cache holds little purpose as our system really places priority on the truck.

**Solution:**
The solution comes from several different approaches, mostly to fix other problems that reside in the current setup.

Here is a break down of the solution:
1) Trucks will no longer generate supplies over time
2) Supply caches will generate supplies over time
3) Supply caches must be placed 250m apparently (same distance as the HQ)
4) Trucks can drop 250 supplies into the nearest cache with `Q` (2 second ability delay)
5) Trucks can pickup 250 supplies from the nearest cache with `E` (2 second ability delay)
6) In addition to the delay, the truck must have zero velocity (not moving) and when a load or unload is successful a sound is made (helps indicate that something was done).
7) Trucks spawn with full supply during setup phase, but only 250 supply when round is live
8) Supply caches show up on the map (and will link to a nearby HQ)

Number 7 specifically deals with another related issue, which is why we actually changed from cache generation to truck generating supplies in the first place. That is there is value in killing one's own truck to generate more supplies quicker. However, with only generating 250 supplies and losing the reinforcements from the truck loss, its just not worth it!

Number 8 makes it so trucks and players can find caches to re-supply at. Also inform players of any advantages a supply cache gives to the nearby HQ.

**Another look at the problem:**
The supply cache doesn't affect or change the battle or combat in any way. In my opinion, this is the fundamental reason for the supply cache not having a significant role in the game play. The solution above won't affect game play beyond making it an additional requirement to generate supplies for the SLs and truck drivers. Basically making it only important to SLs and "builders," otherwise it will have ZERO consequence. If we want the supply cache to matter to every player, then we should have it affect every player. 

**Another solution which is symbiotic with the first solution:**
Go ahead and implement basic ammo logistics in phase 1, but simplify it a bit. How it should work:
Platoon HQs will normally spawn players with only 25% ammo, which is not much at all, but enough to  have a short firefight. However, it will become noticeable to many players and they'll learn how important it is to have an HQ with supply caches linked. If a supply cache is built nearby the HQ, the HQ then will spawn players with 100% ammo. This drastic and clearly advantageous ability of the cache will pretty much lead to each HQ having a nearby supply cache. Which will have both game play and strategic value, which affects every player, and make it a valuable construction in our game.

Losing the HQ is one thing, but what if the HQ loses the supply cache, it becomes weaker, which will create a new dynamic really never seen before in DH. Feel free to comment or chat more about this in discord.

**Comment by cmbasnett** [comment]
After some discussion, we won't be doing this for 8.0. We'll just have much better conveyance for current system. We can revisit this for a later update if we need to fix the mechanics.

**Comment by AndrewTheel** [comment]
Closing, was somewhat implemented already.
