### ISSUE TITLE
Players can destroy friendly Platoon HQs without any punishment

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#822]
I don't think a teammate should be able to destroy your team's own Plt HQ.  That or we need a huge punishment for doing so. Currently I'm able to drive around in a flak truck and freely murder my own team's HQs.

But where do we stop? Should a teammate be able to friendly fire an AT gun or Sandbags?

**Comment by cmbasnett** [comment]
Fixed in commit 58ecb9d.
