### ISSUE TITLE
Display settings screen has a number of problems

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#827]
I've noticed that the display options have a number of problems.

1. The `Show Advanced Options` button will sometimes not work, toggling it on and off does nothing.
2. Game details will be set to "Highest" even if it's quite obviously not on the highest setting.

As an added observation, my graphical settings seem to reset upon re-entering the game sometimes, no idea what causes it.

I also think that the "Show Advanced Options" button should be removed, and we should just...always show them, They take up all that screen real-state anyways, but then we gray it out and the user has to go hunting for a way to enable them.

![20170916162619_1](https://user-images.githubusercontent.com/5035660/30517979-2d602904-9b25-11e7-9f31-16f5f496bca8.jpg)

**Comment by AndrewTheel** [comment]
Yea the Show Advanced Options is odd and unneeded.

**Comment by cmbasnett** [comment]
The last remaining problem is that the "Game details" option allows some strange behavior. You are able to select one of the game details options, then proceed to go and change all of the advanced options, thus making the value in the "Game details" combo box completely meaningless and confusing.

The solution here is to detect when any of the advanced options are changed, and then flip the value over to `Custom` thereafter.

**Comment by cmbasnett** [comment]
Fixed in commits c6a055e and 67051a2.
