### ISSUE TITLE
Constructions placed in-editor can be invisible

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#829]
Seems to happen consistently across clients (the same ones are invisible), but no apparent rhyme or reason as to why (maybe they being spawned inside solid geometry?) The collision is exists at least on the server, but it's visually completely absent on the client.

**Comment by AndrewTheel** [comment]
I'm gonna say yea to the spawned inside solid geometry as the problem.

**Comment by cmbasnett** [comment]
Okay, we've confirmed that it's a problem with spawning the constructions too far inside solid geometry. I'll leave this issue open but I probably won't get to it for 8.0 since it can be easily fixed by the leveler when encountered.

**Comment by AndrewTheel** [comment]
Gonna close this and accept this "bug" as just a limitation of the constructions.
