### ISSUE TITLE
"Contested" objective indicator shows for inactive objectives

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#830]
![20170917013954_1](https://user-images.githubusercontent.com/16300108/30518886-57c08ff2-9b4f-11e7-9aa6-af22c66f6dae.jpg)

Just need a simple check.

**Comment by cmbasnett** [comment]
Fixed in commit afba574d9e53de6637c803cc23cecb8d3a20e81e.
