### ISSUE TITLE
Add a grenade crate construction

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#832]
In the future we will want to have a grenade crate that an SL can plop down to supply his teammates with additional grenades. This addition will coincide with a change that sets the initial grenade load-out to 1 instead of 2 (to reduce grenade spam and reward teams that establish good bases). The mesh itself will need to have bone positions defined for each "slot" so that I can add the grenade static meshes in code easily.

We'll need boxes for each nation, as usual. Here are some references photos:

Soviet
![](http://www.rusmilitary.com/images/f1_box.jpg)

Commonwealth
![](http://c8.alamy.com/comp/F7XE8N/a-full-box-of-number-36-mills-hand-grenades-with-a-tin-of-detonators-F7XE8N.jpg)

German
![](https://i.pinimg.com/originals/34/43/0a/34430a406bc8e0a9712416c6e56a64d0.jpg)

American
![](http://bcafilmservices.com/content/uploads/S0135-grenade-box-and-grenades.jpg)

**Comment by AndrewTheel** [comment]
Done.
