### ISSUE TITLE
German Radio Operator is unable to switch weapons until his primary weapon is dropped

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#834]
This seems to be a single-player only bug. There is one interesting symptom. Spawn as a Funktruppe squad leader (you'll be given a Kar98, shovel, and binoculars).

If you drop your primary weapon then pick it up again, then cycle weapons using `MOUSEWHEELUP` (`NextWeapon`), you will cycle between all 3 weapons. However, if you cycle weapon using `MOUSEWHEELDOWN` (`PrevWeapon`), it skips the binoculars entirely.

**Comment by AndrewTheel** [comment]
> If you drop your primary weapon then pick it up again, then cycle weapons using MOUSEWHEELUP (NextWeapon), you will cycle between all 3 weapons. However, if you cycle weapon using MOUSEWHEELDOWN (PrevWeapon), it skips the binoculars entirely.

^ that has been fixed
