### ISSUE TITLE
Tanks can become unresponsive

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#840]
Was reported by a community member; I've never seen this myself, but here's some video evidence!

https://www.youtube.com/watch?v=66fQnbQjEnM

No one else has reported this, my theory is that it's a selective networking problem on the user's end. Let me know if you have any other ideas. If nothing, we can just close this.

**Comment by AndrewTheel** [comment]
I think this happens on Linux, I've heard of other reports from Linux users.

**Comment by cmbasnett** [comment]
Confirmed that the user was on a Linux machine.

**Comment by handsm** [comment]
No ideas I'm afraid. No knowledge or experience of Linux or why that would behave differently. Appears two unrelated issues in the video: (1) vehicle won't move (although clientside RPM needle moves) and (2) player can't enter vehicle/vehicle appears to be in different locations on client and server. Don't see any connection between those things, suggesting general networking breakdown.

**Comment by AndrewTheel** [comment]
My guess is that this is some deep level bug, way in there, perhaps a network communication error between Linux and Windows. This is very likely not fixable from our POV.

**Comment by AndrewTheel** [comment]
I actually recently ran into this problem (on windows 7). I was testing, spawned about 50 tiger tanks, minimized a bunch, crashed, and then came back and one of the tigers was not where the server said the collision was.

![20171015185350_1](https://user-images.githubusercontent.com/16300108/31655558-da2896ae-b2ee-11e7-91dc-246ed71a0382.jpg)
![20171015185422_1](https://user-images.githubusercontent.com/16300108/31655559-da3d7826-b2ee-11e7-984e-2a6a513bc18a.jpg)

**Comment by AndrewTheel** [comment]
Ran into this problem on Lutremange, parked a truck on a hill side, visually the truck was sliding down the hill, but I couldn't enter, so I ran up the hill and hit use key a bunch and then got in, then it updated its location.

**Comment by cmbasnett** [comment]
I don't think this is within our capabilities of fixing. Closing.
