### ISSUE TITLE
"Setup phase" boundary is invisible when the round resets

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#841]
When the round rests, the setup phase boundary is invisible.

**Comment by cmbasnett** [comment]
This shows that it seems to disappear but only if you are looking at it "the wrong way":

![20171001145852_2](https://user-images.githubusercontent.com/5035660/31060065-042a9cd4-a6c1-11e7-955c-f662d1d01591.jpg)
![20171001145852_1](https://user-images.githubusercontent.com/5035660/31060066-043ab02e-a6c1-11e7-8c41-c52e29474daf.jpg)

**Comment by cmbasnett** [comment]
The problem was that the `RODestroyableStaticMesh` class that was being used has a bug in it that causes this exact behavior if `bUseDamagedMesh` is set to `true`, probably because it doesn't like having it's `StaticMesh` set to `none`. Setting this to `false` fixes the problem entirely.

**Comment by AndrewTheel** [comment]
List of things that need completed to close this issue off:

- [ ] Update the text for Advance spawns
- [ ] DH-Baranovka_Advance
- [ ] DH-Barashka_Advance
- [ ] DH-Black_Day_July_Advance
- [ ] DH-Bridgehead_Advance
- [ ] DH-Cambes-En-Plaine_Advance
- [ ] DH-Carpiquet_Airfield_Advance
- [ ] DH-Hattert_Advance
- [ ] DH-Hedgerow_Hell_Advance
- [ ] DH-La_Cambe_Advance
- [ ] DH-Lutremange_Advance
- [ ] DH-Nuenen_Advance
- [ ] DH-Oosterbeek_Advance
- [ ] DH-Putot-en-Bessin_Advance
- [ ] DH-Rhine_River_Advance
- [ ] DH-Staub_Zwei_Cutoff
- [ ] DH-Stoumont_Cutoff
- [ ] DH-Varaville_Advance

**Comment by AndrewTheel** [comment]
Yeaa everything done!
