### ISSUE TITLE
Terrain poking results in enormous portal to hell on Mac machines

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#851]
This is an enormous problem. There is obviously a bug on the Mac version of the executable that causes this to happen with the terrain poke functionality. There's a couple of steps we can TRY to take, but debugging this is going to be a horrible experience. I can get access to a Mac but this is going to be a multi-day project.

![schermafbeelding_2017-10-01_om_16 30 19](https://user-images.githubusercontent.com/5035660/31154359-73e2206a-a85b-11e7-94a7-f9f4ee05ae1d.png)

The best case scenario is that the terrain poke inputs are being interpreted differently on Macs, perhaps expecting absolute height values instead of deltas. I'm not holding my breath on it.

The other, more likely scenario, is that the terrain poking functionality is a bit of half-finished experimental functionality (evident in how many bugs there are that we've had to work around) that wasn't ever tested on anything other than a Windows machine.

If the latter end up being true and the functionality isn't salvageable on Macs, we only really have 3 options:

1. Don't poke the terrain on Macs, making them completely useless and bizarre to Mac players, but having a slightly less obvious visual bug.
2. Do nothing and leave the bug in, encouraging people to not play on Macs.
3. Remove Foxholes entirely until we can get engine access and fix the engine code.

I don't want to do 3, but I fear it's what we might have to end up doing; a perfect example of "killing your darlings".

**Comment by AndrewTheel** [comment]
Did you fail to do #1, because #1 will probably end up being fine if we get it to actually detect Mac users specifically?

**Comment by cmbasnett** [comment]
Fixed in commit 7426c89. Was fixed by simply setting the terrain poke radius to `1.0` on Mac platforms. While it doesn't look as good as on Windows, the foxhole is still entirely functional and the portal-to-hell has been closed.
