### ISSUE TITLE
Several maps do not have a preview images, loading images, map descriptions, and unit descriptions

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#862]
We have a lot of missing information on a bunch of maps. I know lots of people never read these, but the people who do are pretty vocal. For completion's sake and to look like a bit more professional, we should have all of these, even if they're brief.

# DH-Vossenack_November7th
- [ ] Preview Image
- [ ] Map Description
- [ ] Unit Descriptions

# DH-Vieux
- [ ] Map Description

# DH-Varaville_Advance
- [ ] Preview Image
- [ ] Author
- [ ] Map Description

# DH-St-Clement
- [ ] Unit Descriptions

# DH-Simonskall
- [ ] Unit Descriptions

# DH-Reichswald
- [ ] Unit Descriptions

# DH-Pariserplatz
- [ ] Map Description
- [ ] Unit Description

# DH-Oosterbeek
- [ ] Unit Descriptions

# DH-Nuenen
- [x] Unit Descriptions

# DH-Noville
- [ ] Unit Descriptions

# DH-Lutremange
- [x] Unit Descriptions

# DH-La_Monderie
- [ ] Unit Descriptions

# DH-La_Cambe_Advance
- [ ] Map Description
- [ ] Unit Descriptions

# DH-Kreigstadt
- [ ] Map Description
- [ ] Unit Descriptions

# DH-Kommerscheidt
- [ ] Unit Descriptions

# DH-Hurtgenwald
- [ ] Map Description (truncated)

# DH-Hill_400
- [ ] Map Description (truncated)

# DH-Hedgerow_Hell_Advance
- [x] Preview Image
- [x] Map Description
- [x] Loading Screen
- [x] Unit Descriptions

# DH-Hattert_Advance
- [ ] Map Description
- [ ] Unit Names
- [ ] Unit Descriptions

# DH-Gran
- [ ] Loading Screen
- [ ] Unit Descriptions

# DH-Gorlitz
- [ ] Map Description
- [ ] Unit Descriptions

# DH-Foucarville
- [ ] Map Description
- [ ] Unit Descriptions

# DH-Flakturm_Tiergarten
- [ ] Unit Descriptions

# DH-Dead_Man's_Corner
- [ ] Unit Descriptions

# DH-Carpiquet_Airfield_Advance
- [ ] Preview Image
- [ ] Map Description
- [ ] Unit Descriptions

# DH-Cambes_en_Plaine_Advance
- [ ] Author (glik?)

# DH-Black_Day_July_Advance
- [ ] Loading Screen

**Comment by AndrewTheel** [comment]
Not sure why Lutremange was reported to not have unit desc. because it has them.

**Comment by AndrewTheel** [comment]
This issue has a lot of false info, I think it needs re-reported with correct info.
