### ISSUE TITLE
HUD needs to indicate objective capture requirements

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#864]
The overview and hud (capture bar) needs to indicate 2 situations where players cannot capture an active objective they do not control:

- [x] The objective has the pre-cap-prevention timer running also known as the lock down timer.

- [x] The objective is neutral, but the team doesn't control the required objectives to progress capture progress

**Comment by cmbasnett** [comment]
Implemented in commit b6cbf958be216eb69d2771c7f1c1b080f79956f7.
