### ISSUE TITLE
On M16 halftrack the quadmount turret snaps 180 degrees to face forwards when player enters turret

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#872]
Split this off as one of three issues reported in github.com/DarklightGames/DarkestHour/issues/738, as it is major and unrelated to the other two reported issues.

The new M16 halftrack has a 50 cal quadmount 'turret' mounted on the back, which starts facing backwards. This is effected by the turret attachment bone facing backwards in the halftrack mesh rig.

But when a player gets into the turret position, the turret snaps to face forwards.

**Comment by handsm** [comment]
There may not be a quick fix for this as I'm sure it's native code that's doing it. Could well be a way around that, but with time limited the fall back position is to have the M16 start with its quadmount facing forwards. Rear facing is preferable but I wouldn't say it's a huge issue.

**Comment by cmbasnett** [comment]
Alright, not a big deal, let's just have it face forwards.

**Comment by cmbasnett** [comment]
Fixed in commit 4013bc4fd9e424ce1fbbe62f79ea94dc7f7dc373. Re-exported the mesh with the `turret_placement` bone facing forwards.
