### ISSUE TITLE
Players should not be able to view their corpse in 3rd person

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#874]
Players should not be able to view their corpse in 3rd person and their 1st person view should fade to black for dramatic effect.

**Comment by kashash** [comment]
Totally agree but let us players be able to switch to view other players immediately or at least much faster than the 2-3 seconds that is in the current DH version.

**Comment by AndrewTheel** [comment]
@cmbasnett Can we setup the defaults and make sure we have the spectator system how we want it as default?

**Comment by cmbasnett** [comment]
Pretty sure this is already implemented. Closing.
