### ISSUE TITLE
'Received inventory' checks run pointlessly for every other player's pawn, continuously failing throughout the round 

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#882]
In multi-player, each player pawn checks that it has received its full inventory loadout. A net client is making sure it has received all its full loadout and recorded it as its Inventory chain of actor references. When it has the client flags bRecievedInitialLoadout, at which point it can disable its PostNetReceive() notifications and checks, providing a few other initialisation things have also been completed.

Until bRecievedInitialLoadout has been flagged the player cannot switch weapons. bRecievedInitialLoadout is some pretty pesky RO functionality that is the cause of weapon switching bugs, which can happen in several ways. It's probably more trouble than it's worth tbh.

But it is only relevant to your own player pawn, i.e. the pawn of the local player on the net client. It has no relevance whatsoever to the pawns of other players. And in fact those pawns can never pass the inventory checks because the inventory chain only exists on a net client for the player's own pawn. This means that the client keeps attempting an inventory check for every other pawn constantly throughout the round, constantly failing and never disabling its PostNetReceive() notifications, which is meant to happen within a split second when another player's pawn spawns on your machine.

This doesn't cause a noticeable bug in game. But although it only affects the client and the server, it is such a hideous offence against efficient processing that I thought I'd log it as an issue. A billion wasted processing operations per machine per round - no exaggeration! Yuk. :(

**Comment by handsm** [comment]
I written and checked a fix for this and will commit tomorrow. It's pretty simple.

**Comment by cmbasnett** [comment]
Wow I didn't realize this was being run on *other* people's pawns as well. Total waste of time!

**Comment by handsm** [comment]
Fixed in commit https://github.com/DarklightGames/DarkestHour/commit/43bedce1c0d617843a8d938c1b0f72f624cb3297.

PostNetReceive() now checks whether the pawn is controlled by the local net player. If it's another player's pawn then it simply flags bRecievedInitialLoadout true, which stops any loadout checks on that pawn. Then, when bInitializedPlayer and bInitializedWeaponAttachment have also been flagged true, PostNetReceive() gets disabled. So now PostNetReceive() only runs for a second or so when the pawn spawns, not constantly throughout the whole bloody round!

Note we can't just do an IsLocallyControlled() check and if it's false then assume the pawn is another player, because as this pawn has just spawned we can't assume it has its Controller yet. Possession and Controller come slightly after the pawn spawns. So instead if we can't confirm it IS the local net player, we specifically check whether the local player is controlling a different pawn or is a spectator. If he is then we have safely confirmed this player pawn belongs to another player and so we flag bRecievedInitialLoadout true.
