### ISSUE TITLE
Need HUD indication for dead spectating players to break down their respawn time

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#883]
Need a HUD indicator to explain the total respawn the player has. For example:

You will respawn as a Machine Gunner in 77 seconds at Platoon HQ...
Respawn Time Penalties:
25 Base
+15 Role
+10 Spawn Point
+15 TK(s)
+5 Team Balance
+7 Server Performance

**Comment by cmbasnett** [comment]
Not entirely necessary for the first 8.0 release, moving the milestone.

**Comment by AndrewTheel** [comment]
Though this could be useful to players, it could also confuse them. Closing for now, as there are many factors to determine respawn time and I just don't see it worthwhile to flood player screens trying to explain it.
