### ISSUE TITLE
Voice chat would stop working for players when the player counts were very high

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#887]
Pretty sure this isn't a new problem, but when the player counts got very high (70-80), some players became unable to talk or hear voice at all. The symptoms include:

1. Holding down the chat button doesn't do anything.
2. Unable to hear anyone else.
3. Still able to switch channels.

We will run a test where we disable the chat manager entirely, if the problem still persists then the culprit will likely be elsewhere.

**Comment by AndrewTheel** [comment]
We should try to make sure we see no issues with `VoiceID` assignment or usage before next test and hopefully a combination of doing that and disabling the chat manager entirely will either reveal more about the issue or remove it.

**Comment by AndrewTheel** [comment]
I think this is a separate issue from the chatmanager crash issue. This issue is something to do with VoiceID and I think we should put in some debug, which outputs voiceIDs every once in awhile or something.

**Comment by cmbasnett** [comment]
Added in logging and an increase of the max voice ID to 255 in commit c63becb8462aa5324e7c079969900b0dad6f613f

**Comment by cmbasnett** [comment]
It seems that voice IDs were being incremented and assigned correctly, but I think something deep down is stopping it from working. This *might* be un-fixable unless we get source engine access.

**Comment by AndrewTheel** [comment]
I'm leaning towards unfixable, but I'd like perhaps some new eyes on it. @handsm

**Comment by AndrewTheel** [comment]
Closing, wontfix
