### ISSUE TITLE
Cambes En Plaine Advance

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#888]
- [ ] ![20171022115027_1](https://user-images.githubusercontent.com/16300108/32015788-c0b546dc-b987-11e7-8a29-87d8ca5c0877.jpg)
- [ ] ![20171027200614_1](https://user-images.githubusercontent.com/16300108/32153932-5c2c7b46-bcfb-11e7-8239-b29b1a6c004d.jpg)
- [ ] ![20171027195216_1](https://user-images.githubusercontent.com/16300108/32153940-5cdf5b30-bcfb-11e7-9e31-59e42c72ea2f.jpg)

**Comment by kashash** [comment]
I've optimized it as much as I could, added some more bsp to cut the nets on the map, but when it comes to the fps, the map is optimized as it can, all the statics have strictly low cull distance set on them, and any less trees and the map would lose its realistic appearance of how it was in real life, if any players have problems with fps they should lower the fog distance
Fixed almost all the github issues that were for cambes, but like ladder I tried and couldn't fix it, I've set up ladders before but this one I couldn't fix

**Comment by AndrewTheel** [comment]
Okay so first of all about optimization. After reviewing one of the laggiest parts of the map, I noticed 80% of the problem is the deco layers. Running at 5ms with only 100,000 triangles.  The static time is only 2ms and running at 400,000 tri.  

![20171118114728_1](https://user-images.githubusercontent.com/16300108/32983420-e06f6428-cc59-11e7-84e0-17f768a3398b.jpg)

Notice how the deco is nearly 5 ms, the total ms is nearly 16 (sorry its hard to read). Anyways, I think if we remove

- [ ] You should replace the decos with statics, except for the road rocks.  Which should be turned down significantly.  Doing this I think will shave off ~4ms from that high 16ms.

Here we have portals that are doing absolutely nothing but chopping up the BSP (very bad)
- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983515-653144c8-cc5b-11e7-8cfe-8c981d54da74.png)

I also noticed a very high texture count (above 400 textures is too high). All hidden and "unlit" surfaces on BSP buildings should be black and UNLIT. The reason being is that you reduce the chance that one of these hidden surfaces uses a texture not used in the level. But setting it unlit you reduce the lightmap complications, which can improve build time and lesson level size.
- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983534-afdb25c0-cc5b-11e7-8225-323d285f3fc3.png)

There is no reason to use such a big blocking volume to block the window. Blocking volumes also block free roaming spectators, those who parachute from the sky, etc.  With a blocking volume this large, it would break the map from having parachuting, which sure it doesn't have them now, but there might be situations where units want to use the map in that way. Also having a blocking volume, but an opening the player can obviously get out is annoying. Imagine being alone in the house and having an entire squad come into the house after they've shot at you etc. and you try to escape to the roof only to find out that you can't and then you are shot because you were blocked by an invisible wall.
- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983222-e17ae552-cc56-11e7-8d0b-4082f7286666.png)

You can find it easy by searching the objectname of the static I have selected.
- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983270-9dcce4b2-cc57-11e7-9dc0-e12c4abbf26a.png)

The lamp does not have a cull distance set
- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983284-d319a2ae-cc57-11e7-8851-4c43523771de.png)

No cull distance on outhouse, but have them on larger shed
- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983297-07d16752-cc58-11e7-913b-a729b2c44d68.png)

No cull distance(s)
- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983303-179b349c-cc58-11e7-9294-e64e88a7661b.png)

- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983308-30b1e426-cc58-11e7-93b5-ee316e946380.png)

- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983312-4562a41e-cc58-11e7-882c-85474020a128.png)

- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983317-53debcd0-cc58-11e7-9dab-de45101899e2.png)

You can prob put a high cull distance on these window frames
- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983327-6fe3aba2-cc58-11e7-81d4-c92389863b7f.png)

- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983338-9b6ab946-cc58-11e7-8547-2374f2a7e1fd.png)

- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983342-b05ff9e2-cc58-11e7-9f18-f028b18047da.png)

- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983354-c3f8e25c-cc58-11e7-8659-2fa739af7f00.png)

- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983362-d61214e0-cc58-11e7-9a7a-c69d4eb778cc.png)

Use a high value like the trees
- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983370-f673a7c6-cc58-11e7-98df-4daae1d639c4.png)

- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983377-0a79b1e8-cc59-11e7-9d6d-ec594069c78c.png)

- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983382-260fad04-cc59-11e7-9a6f-9325930c0088.png)

- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983603-cf85d220-cc5c-11e7-9025-0e44602695e0.png)

Found some palette
- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983746-5a9ea2a4-cc5f-11e7-9111-f940f76d65ab.png)

This is very concerning, not sure why this BSP bottom/face is not appearing, can't even select it like I can select invis BSP faces. Yikes!
- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983557-1da04194-cc5c-11e7-8d1a-f556cd86ad60.png)

This roof should not be BSP
- [ ] ![image](https://user-images.githubusercontent.com/16300108/32983568-5221b150-cc5c-11e7-9ec1-edc035272d6b.png)

Vegetation bAcceptProjectors I still found some with it on!
Groups should be used sparingly and kept organized and updated.  Otherwise they are not useful.  I can't trust any of these groups.  They don't include all of the statics they should AND there are just too many groups.  I've recently discovered objects/actors have a limit to their groups string, so if its in 2-4 groups with long names, it'll cull them and the **groups thing wont' even work**. 
![image](https://user-images.githubusercontent.com/16300108/32983651-7aa61b7e-cc5d-11e7-9e7d-2013284bae25.png)

- [ ] Delete the grid statics you have on the hidden group

- [ ] I'd start by removing all the groups and start over (as if you don't you may run into the above problem)

- [ ] Make sure to be descriptive with your group names

To make sure you have all the vegetation selected before making the vegetation bAcceptProjectors=false, you should begin by selecting as many different trees, hedges, bushes, grass, etc.  Then slowly add them to a group. You can append a group by the plus button.  Once you've added a bunch, turn off terrain and roam around in perspective looking for additional vegetation.

![image](https://user-images.githubusercontent.com/16300108/32983681-1df3c25e-cc5e-11e7-9432-5928aee5c2bc.png)

Add the next selections to the new veg group then, click the veg group to show and hide again (will update it). Do this until you cannot find ANY vegetation after roaming around for awhile.

Don't forget to check up against buildings or even inside them!

![image](https://user-images.githubusercontent.com/16300108/32983691-4dc0d40e-cc5e-11e7-8465-dbc93780a2b1.png)

Once you have all the vegetation on one group, you can select all in the group and set the bAcceptProjectors to false.

**Conclusion:**
I think after you've gutted the deco layer, the render MS will be 12 max, which is much better than 16. However, I bet it'll avg more like 10.  

If I'm wrong then we can further improve FPS after that by making billboard trees and reducing fog, but lets hope I'm right.
