### ISSUE TITLE
Oosterbeek Advance

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#890]
- [x] Make 1^1
- [x] Make completely advance ready
- [x] Make sure values are default for Advance
- [x] ![20171029153549_1](https://user-images.githubusercontent.com/16300108/32153658-f1c6e38c-bcf9-11e7-85f4-44be0826e9fe.jpg)
- [x] Artillery Observers are unlimited on the Allied side

**Comment by cmbasnett** [comment]
Pretty sure this was done ages ago.
