### ISSUE TITLE
FALVoiceModule::Decode GPF crash

### ISSUE THREAD

**Issue by IanTangney** [DarklightGames/DarkestHour#908]
I was just playing in a Churchill tank in a squad of two people, I think the other squad member was in a different tank. Not sure if that's useful info.

```
Build RedOrchestra_Build_[2005-11-27_10.48]

OS: Windows NT 6.2 (Build: 9200)
CPU: GenuineIntel PentiumPro-class processor @ 3401 MHz with 4095MB RAM
Video: NVIDIA GeForce GTX 1060 6GB (8813)

General protection fault!

History: PlayBack <- FALVoiceModule::Decode <- UALAudioSubsystem::PlayVoicePacket <- UVoiceChannel::ReceivedBunch <- UChannel::ReceivedSequencedBunch <- Direct <- UChannel::ReceivedRawBunch <- DispatchDataToChannel <- BunchData <- UNetConnection::ReceivedPacket <- UNetConnection::ReceivedRawPacket <- UTcpNetDriver::TickDispatch <- UpdatePreNet <- ULevel::Tick <- (NetMode=3) <- TickLevel <- UGameEngine::Tick <- Level Bridgehead <- UpdateWorld <- MainLoop <- FMallocWindows::Free <- FMallocWindows::Realloc <- 00000013 0 FArray <- FArray::Realloc <- 0*2 <- FMallocWindows::Free
```

**Comment by cmbasnett** [comment]
This might have been a one-off. General protection fault (GPF) crashes usually point to a bug in the underlying engine code, or some confluence of external factors that cause the game to crash; as a result it might not something that we can fix directly. If this is a persistent crash, please let us know.

**Comment by dynamittt** [comment]
Had similar issues long time ago when I had a dying GPU.....after reballing the GPU in the oven the problems are gone. Now the game rarely gets a GPF.....

**Comment by AndrewTheel** [comment]
Gonna close this as it looks like an individual problem, likely brought on by hardware issue or something to that extent.
