### ISSUE TITLE
Rally Points should be able to take damage and easily destroyed by small arm fire & explosives

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#910]
I saw an enemy RP in the distance and wanted to destroy it, but had to wait until enemy spawned on it and combat spawn killed him.

As for how hard it should be to kill:
- 2-3 shots from Rifles
- 5-8 pistol shots (basically not worth shooting at with pistol)
- 1 very close grenade or 2 somewhat at grenade max damage range
- 1 medium range HE tank, mortar, or artillery blast

**Comment by cmbasnett** [comment]
Implemented in commit afd59c867b9e56c9eb97fa781ee048e532648e1f.
