### ISSUE TITLE
Hit Detection Issue

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#927]
Okay first let me state... THIS IS NOT A WEAPON ISSUE.  Weapons perform fine.

After experiencing the worst hit detection issue I ever have in DH, or any game for that matter, Basnett and I came to the agreement that it has nothing to do with the server tick rate (we both already knew it has nothing to do with the weapons).  We also feel it has nothing to do with PLT (pre-launch trace), as the MP40 has PLT completely turned off and it happened to all weapons and to all players at roughly the same time.

We think this is a new bottleneck, or rather a new bottle neck we are reaching because of MORE players, larger maps, and larger fog distances.

We think it might be a network bottleneck where packets are dropping EXTENSIVELY when too many players are relevant too one another.  Caen is a map without any network optimization and at the beginning of the round all the players are alive and right when the first engagement happened is when the hit detection issue happened.  This does not seem to happen as bad or at all with levels like Hedgerow Hell which has good network optimization.

This means, the issue can be resolved with level optimization.  However because there are many levels not yet optimized.  We feel the server should be toned down a bit to have less max players, perhaps 72.  Because fog can network-cull, it is also advisable, until extensive net cuts can be put in, to lower the max fog on several levels.

There is one more thing to maybe try and that is lowered the max allowed client net rate from 15k to perhaps 7-8k or at least play with the setting.

**Comment by cmbasnett** [comment]
I will lower the maximum player slots to 72 over the weekend and see how it goes.

**Comment by AndrewTheel** [comment]
I'd lower fog distances on culprit maps also.  And try playing with the max client rate, lowering it to maybe 8k and see what happens.  64 slots would mean no more voice bugs :D

**Comment by AndrewTheel** [comment]
Actually I'd go the extent of replicating 2 variables and having the scoreboard show the average server tick rate and whatever you come up with to show the network strength of the server.

**Comment by cmbasnett** [comment]
That's actually a pretty good idea. And we can show a color for the "server load".

Red: (0-10)
Orange: (11-20)
Green: (21+)

**Comment by AndrewTheel** [comment]
Have any clue how to detect the server net load?

**Comment by cmbasnett** [comment]
Not specifically packet loss etc, but a decent metric would be the average tickrate, which we've already calculated for debug purposes. We'd just use that and occasionally update a value in GRI so it can be displayed on the scoreboard.

**Comment by cmbasnett** [comment]
I don't think it's possible to get that packet information, at least not easily. And since there's no documentation on this stuff I don't want to spend a week trying to find it.

**Comment by AndrewTheel** [comment]
I spent a few hours looking around for any way the server or client could access network performance info, but found nothing.  The only other idea is to look at the network load on the server, and compare/contrast the culprit maps at known bad parts (first engagement on Caen) vs very optimized maps (Hedgerow Hell).

If the net load is much much higher on Caen, then we know for sure (100% certain) that it is in fact a network issue.  And the only solution is to optimize maps, starting with the worst culprits (Caen) and see if it has any positive effect.

**Comment by AndrewTheel** [comment]
For testing I've made some changes to the server network settings.

The tick rate on the official now caps at 32 instead of 40.  The higher the tick rate, the higher the bandwidth overhead there is.  We should probably adjust other optimization values to expect slightly less tick rate.  The tick rate limit can be changed dynamically, so one thing we could do is dynamically adjust the server's max tick rate based on how many players are on the server.

Also I've lowered the netplayer's net rate to 10000, it was 15000.  This will lower our player's max frame rates, but should reduce the bandwidth overhead.

**Comment by AndrewTheel** [comment]
So far those changes have had no noticeable negative effect and I have not seen packet loss or hit detection issues since.

**Comment by AndrewTheel** [comment]
Things are looking good in regards to hit detection.  I think those issues are gone.  That said, it really still depends on the map.  I will continue to keep an eye out for packet loss.

**Comment by AndrewTheel** [comment]
I'm gonna close this issue as its not specific enough.  If repeated hit detection issues occur, then its the level's fault and it needs to be optimized.
