### ISSUE TITLE
Most vehicle gunsights and similar overlays are set up with incorrect magnification and visible field of view

### ISSUE THREAD

**Issue by handsm** [DarklightGames/DarkestHour#930]
Most vehicle cannon and MG gunsights are over-magnified and many also show a wider field of view than they should, i.e. the area of the world you can see inside the circle of the sight view.

A note about FOV (field of view) degrees: We tend to think as FOV as the zoom setting, i.e. lower the FOV to show a zoomed in view. That's how magnification/zoom is controlled in the game engine. In the game a sight's magnification is set by the ViewFOV setting for the gunsight position. But when looking at gunsight information, the sight's real world FOV means how wide a view of the world you can see through it, not how magnified it is. FOV for zoom/magnification is only a game engine concept. In the game a sight's visible field of view is set by the GunsightSize setting, where for example a value of 0.5 means the sight circle fills half of the width of the screen.

Sight magnification is based on the neutral/normal player view of the world, which is 85 degrees (a standard RO setting), meaning you can see an 85 degree horizontal arc from the left to right side of your screen. If the sight has 2.5x magnification we would set it up with a sight ViewFOV of 34, i.e. 85 divided by 2.5. If that sight offered a 15 degree FOV we would set it up with a GunsightSize of 0.441, i.e. 15 degrees of view divided by its zoomed ViewFOV of 34.

Looks like most sights were set up in DH v5.0 when the normal player view FOV was set to a pretty zoomed in value of 72 degrees. A more zoomed in default FOV for a starting point means that magnified overlays like gunsights had to be more zoomed in as well. As the DH normal player FOV is no longer anywhere near 72 (that only lasted a few months until DH 5.1 was released), the old gunsight settings now give an over-magnified view.

Some other sights have settings that are just wrong. A good/bad example is the sight for the flakvierling and flak 38 guns, which is a flak version of the German ZF 3x8 sight. The name of the 3x8 family of sights is descriptive: they give 3x magnification and a 8 degree field of view. That magnification is about the same as most late war sights, but the 8 degree field of view is quite restricted. The current settings are from the old mod version of the flakvierling and offer huge magnification and visible FOV. The magnification is over 7x, with
an enormous field of view, almost filling the screen.

As well as cannon sights, the same applies to vehicle MGs with gunsights and also to binoculars and any magnified periscope, although binocs and periscopes don't currently have any setting to control the visible field of view through them.

**Comment by handsm** [comment]
Corrected all the cannon and MG sights, plus magnified German periscope (on Stug etc), in commit https://github.com/DarklightGames/DarkestHour/commit/04463c50f14fd5f8209c8eca01ffcb9fb1b62df5.

I've marked queries on a few, although sometimes it's just the exact sight model and doesn't affect magnification and visible FOV, which are known.

Not sure about jagdpanther as sources quote three different sights with different properties. I believe there was an early and a later version with different sights, and possible a mid production variant with another type.

Jagdtiger needs a solution to a strange problem where shell tracers aren't visible if the view FOV drops below 10.67 (equivalent to approx 8x magnification). The problem now manifests itself on the jagdtiger because it had 10x magnification on the gunsight (so view FOV is 8.5) and there no other gunsight like that in game. So need to either (1) fudge magnification or (2) use tracer static mesh for projectile SM (like German 20mm).

Similar problem affects German SF14Z periscope that also had 10x magnification, but as that's only a periscope I've already fudged it to approx 8x magnification by setting view FOB to 10.67 so you can see your shot's tracer through it.

Now need to make corrections to binoculars FOV, which are set to a FOV of 12 for all nations, but I need to check binocs magnification first. Binocs would have been set to x6 magnification when they were originally set up for the general view FOV of 72 in DH 5.0.

The range settings for sights with mechanical range adjustment (British, Soviet guns and later tanks, nearly all German) are not affected by these changes. That's, because the aim point is always centred, so changes in view FOV or gunsight size don't affect the aim point. But it does affect sights without any range settings (German 20mm flak and all US sights) or with optical range adjustments (earlier Soviet tanks). That's because the aim point on these sights changes based on range, so if you change view FOV or sight size it does affect where you're aiming at, so the range corrections need adjustment. On optical sights you set this for each range setting, but on simple sights with no range settings you only have a global pitch adjustment setting and have to make the best of that over all common ranges.

I've included accurate corrections for all ranges for shells fired by the ISU-152. Actually all the range adjustments disappear and the sight works nicely at all ranges with one global pitch adjustment. The T-34  and KV-1S haven't changed as I'd already recently set them up with the correct gunsight properties and range adjustments. For the German 20mm flak sight I've made the best of a bad job and assigned a global pitch adjustment that works pretty well at ranges up to 1000m. But the adjustments necessary for this sight vary greatly, up and down between ranges, so there's no one size fits all solution and it would need the sight texture editing to make all the ranges work.

I haven't touched the various US gunsights, which also only have one global pitch adjustment, because they were generally completely off in aim anyway and needed a thorough review and correction. So now they will just be innacurate in a different way to before. I'll log an issue for that and try to work through it fairly soon, preferably before another DH release.

**Comment by handsm** [comment]
Forgot to include vehicle optics texture file, where I've re-sized all sights that were not made to the standard circle diameter, which meant that the GunsightSize property had to be fudged to correct for the incorrectly sized circle in the sight overlay texture. The corrections I committed for visible FOV rely on these sight being resized to the standard, as the GunsightSize functionality relies on all sight textures being made to a standard circle size, regardless of how big or small the world view was through the sight, i.e. its visible FOV. GunsightSize then draws the sight texture at the correct size to give the correct visible FOV.

Corrected optics texture file in commit https://github.com/DarklightGames/DarkestHour/commit/ecb99bd84e4102d05afc8d209ecef7280b7060d2.

**Comment by AndrewTheel** [comment]
Players have really not liked this change, for the sake of gameplay I suggest we not do any more and maybe undo the ones we did.
