### ISSUE TITLE
RPG43 anti-tank grenade is not very effective especially when used properly

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#934]
When I was researching the RPG43 grenades and coded them, I discovered it was awkward and very dangerous, but actually effective. Veterans had to risk getting close to the tank, so they could throw the grenade up into the air over the tank to have it fall and impact on the top of the tank.

They did this for 3 reasons:
1) There is less armor thickness on the top armor of all tanks
2) It was more likely the grenade would hit the tank at the desired angle
3) They could stay in cover when throwing the grenade

Throwing directly was risky because the grenade might not orientate properly and thus not go off.  It is hard to throw an objective with a specific orientation and even more difficult to do so with distance/speed as a goal.

Here is a diagram of my thoughts on using the grenade (the different methods, using common sense).
![rpg43_throwingmethods](https://user-images.githubusercontent.com/16300108/36360430-6984c096-14e9-11e8-86cd-b3d2097a29d1.png)

My desire was to have it so if players throw it up into the air and it came down on top of the tank (which takes skill), it would always result in a kill on smaller tanks and heavy damage on large tanks.

However, as it stands now it is the opposite.  Throwing it up into the air to have it come down results in zero or very little damage.  Because of how the grenade is coded, direct throws always result with explosions and doing damage.

I suggest we implement bonus damage for top armor impacts and debug the top armor impacts because currently they don't seem to work.

**Comment by AndrewTheel** [comment]
Like my little image I made? 😄

**Comment by AndrewTheel** [comment]
The code starting on line `208` with `if (ROPawn(Wall) == none)` in class `DH_RPG43GrenadeProjectile` is a bit messy and I think the culprit to why indirect (top armor) hits (which do impact) don't actually do any damage.  If it hits the side, it never runs the `ShouldPenetrate()` function, but if it hits the top it does, which is why I think that bit is the culprit or the `ShouldPenetrate()` function.

**Comment by AndrewTheel** [comment]
Did some more testing, discovered the RPG43 AT grenade does 0 damage to every tank if it lands on top-armor.  This is straight up a bug then.

**Comment by dynamittt** [comment]
Hi guys haven't been here for quite some time, Theel is kinda right that the RPG 40 Grenade _could_ be used to be thrown on top of the tank, while this is more "true" for late Soviet cumulative (shaped charge) AT grenades (RPG 43 is also a shaped charge grenade)
But the late post-war soviet AT grenades based on the RPG 43 used kinda different "chute" design, that would slow the grenade more. So I think that the 'standard' throwing mechanic should be lleft (the 'flat' 'horizontal-like' trajectory), while a secondary throwing option for 'lobbing" the grenade upwards could be added. This would of course make it possible to hit tanks weak top-armor as Theel mentioned, while it is worthy to mention that the grenade has 70-75 mm of armor penetration(according to various sources) capability(while some even claim up to 90 mm), which is completely enough for most tanks, given the fact that the thrower would always try to flank the tank and hit it from the side/rear. 
If I search some Russian weapon databases and contact few people and could come up with even more detailed info....
Also the so called 'parachute' I mentioned is actually a stabilizer: it is said to be used to orient the warhead in the direction of throwing, not to slow it down. (while on  some later post-war soviet shaped charge AT nades the stabilizer was significantly bigger and would slow down the grenade quite a bit), but then again they used completely different tossing technique, where the thrower would throw it upward and forward......

**Comment by dynamittt** [comment]
As for coding, a simple calculation of the angle at which the nade hit the armor plate using HitNormal should be enough? The bigger the angle (from 90 degrees aka 'normal') the lower the penetration value?

**Comment by AndrewTheel** [comment]
Fixed.
