### ISSUE TITLE
Team Forfeit Vote

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#936]
Need to consider the negatives to having this. Imagine your team giving up when you want to continue, etc. However, I think to prevent matches that are stagnant is more beneficial than the rare case of you wanting to continue when you team has given up or fallen apart and why are you more important than the majority of the players on your team?

Just some issues to consider, I would like to run the idea by the community as well before I get into designing it and then implementing it.

**Comment by AndrewTheel** [comment]
Some ideas on restricting this vote to be useful but not demoralizing or hurtful to the game.  

Vote Start Requirements:
- Must be a Squad Leader
- Must be in a squad with at least 3 others
- Round time must be elapsed for at least 10 minutes
- Reinforcements must be below 66% (2/3s)
- Must not control the majority of objectives
- Your team's reinforcements must be below 200 compared to enemy team
- Must have 2 different SLs to initiate the vote

These are pretty restricting and thus the vote will be hard to pass.  But here is some good news.
The vote pops up for everyone on the team and it must be voted or else it'll remain on screen (like other votes and TK forgiving, etc).

F1 to Retreat
F2 to Go On Fighting

The vote just needs majority or equal.  So if 16 players vote yes on a 32 player team, it will pass.

If the vote passes, the enemy team will be announced the winner (later more will be revealed with after-action-reporting).

**Comment by AndrewTheel** [comment]
Working on this again:
I decided to keep it simple and make it so anyone can "Request Surrender" if more than 5 players do it on a team, it starts a vote for the entire team, if it fails the vote goes on cooldown.

**Comment by AndrewTheel** [comment]
Bumping this

**Comment by kashash** [comment]
Would be nice if we could slip this in somehow for the next update.

**Comment by AndrewTheel** [comment]
Has been implemented.
