### ISSUE TITLE
SquadSay messages are not able to be sent from OSX clients

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#945]
For some reason, every Mac user seems to be unable to send `SquadSay` messages. It's not understood why this is the case.

**Comment by AndrewTheel** [comment]
Does OSX have some sort of admin priv. for programs, like Window's Admin mode? If so it could be that the program is not allowed to change its configuration file.

**Comment by rodeje25** [comment]
Never noticed this issue myself and i'm on an incredibly out of date mac. suppose this is fixed?

**Comment by AndrewTheel** [comment]
Fixed.
