### ISSUE TITLE
Garbage collection is taking a long time

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#946]
The longer loading time is likely caused by having to garbage collect a lot of data, likely from constructions.

**Comment by AndrewTheel** [comment]
There is a command you can type in console which outputs all the resources the client is using at the time. Might be a good idea to load a very blank level after playing 15 or so different levels with players in them, then seeing what is loaded in resources on the blank map, might give us an idea of what isn't being garbage collected.

**Comment by AndrewTheel** [comment]
I put my money on construction resources!

**Comment by AndrewTheel** [comment]
Hmm how does sound work in regards to it loading?

In regards to the victory music, are all the sounds being precached? If not all, then how does it randomize just 1 to play?  If this is the case, I think we should change the victory music system.

**Comment by cmbasnett** [comment]
I don’t believe the audio is being precached at all.

**Comment by AndrewTheel** [comment]
So we could have millions of victory music on our package and it wouldn't harm the resources usage of DH?

**Comment by cmbasnett** [comment]
Only one way to find out.

**Comment by AndrewTheel** [comment]
Closing this for now as there isn't much we can do to resolve it.
