### ISSUE TITLE
v8.0.10 Level Updates

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#948]
- [x] DH-La_Gleize_Advance
- [x] DH-Lutremange_Advance
- [x] DH-Makhnovo_Advance
- [x] DH-Nuenen_Advance
- [x] DH-Oosterbeek_Advance
- [x] DH-Putot-en-Bessin_Advance
- [x] DH-Varaville_Advance

**Comment by cmbasnett** [comment]
Seems we're done!
