### ISSUE TITLE
The 2 minutes round end time should not activate if reinforcements are too far apart

### ISSUE THREAD

**Issue by kashash** [DarklightGames/DarkestHour#955]
I finally got to write it on github in a hope this would be agreed on.

The feature can be add a nice intense extra feeling if both teams are fighting each other to the last man and the match is very close.

But a lot of the times if the attacker pushed the defender to the last cap and completely smashed them. The 2 minute waiting can be excruciatingly long and tedious as it just makes ppl say god please just end this already.

It would be a lot more unique and special if the 2 minutes happened not everytime the reinf hit 0 because sometimes it's nice to finish the map right away (especially when the team completely got wrecked) and sometimes is nice to fight for another 2 minutes (like in a football match) if there is likely to be a draw.

That 2 minute would then be happening only if one team hit reinf 0 and the other team is below 50 tickets.

Would it be possible please.

**Comment by AndrewTheel** [comment]
What do you think about having it 100 reinforcements, but extend the 2 minutes to 4?

**Comment by AndrewTheel** [comment]
Hmm actually, I think extending the time, sorta hurts the "winning" team and I think realistically speaking doesn't make sense. Simply because the best tactic for the team with reinforcements left is to run away or hide. Perhaps 50 and 2 minutes is the best.

**Comment by kashash** [comment]
I honestly feel like the current 2 minutes is already very very long, I actually was thinking about being only 1 minute Even. But honestly I think 2 minute is perfect because a lot of the times it already feels very long after a very long-wearisome battle, and the battle is practically finished so any more than 2 minutes would be just overly long.
