### ISSUE TITLE
Finish Patreon Tasks

### ISSUE THREAD

**Issue by aTheel86** [DarklightGames/DarkestHour#961]
- [ ] Finish discord bot (system for players to submit their ROID for in-game rewards)

- [x] Setup .php and mySQL database for servers to 'get' patron ROIDs

- [ ] Create Patreon Video

- [x] Finish map vote system (include patron rewards)

- [x] Put in icons for patrons in-game

- [x] Have scoreboard draw patron icon for patrons

**Comment by AndrewTheel** [comment]
I think v8.2 and the patreon announcement will lack the automation of the discord bot, so I will have to manually add ROIDs into the SQL database until that is completed. Video can come later as well.
