### ISSUE TITLE
Make it so anyone in a squad can place a foxhole

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#986]

**Comment by cmbasnett** [comment]
This would require the creation of a 'squad member' menu.

**Comment by AndrewTheel** [comment]
That should be done anyways, as we can add to it for the Radio Artillery ability.

**Comment by AndrewTheel** [comment]
Trying out Patrons only first, to see if too many foxholes get created with a few additional foxhole placers present. Closing as this is not a task unless we determine still too many foxholes are not present.
